<?php

declare(strict_types=1);

namespace SqlSemantics\Platform\MySql\Lowering\Leaf;

/**
 * The keywords MySQL 5.6 and 5.7 accept as identifiers: the rules `keyword` and `keyword_sp`.
 *
 * Each signature is a production whose only symbol is a keyword terminal; at
 * such a production the keyword is the identifier it spells. The list is the
 * union over every shipped release that has the rule.
 * Source: https://dev.mysql.com/doc/refman/5.7/en/keywords.html.
 *
 * @visibility SqlSemantics\Platform\MySql
 */
final class LegacyKeywords
{
    /**
     * The keyword-as-identifier productions.
     */
    public const SIGNATURES = [
        'keyword: ASCII_SYM', 'keyword: BACKUP_SYM', 'keyword: BEGIN_SYM',
        'keyword: BYTE_SYM', 'keyword: CACHE_SYM', 'keyword: CHARSET',
        'keyword: CHECKSUM_SYM', 'keyword: CLOSE_SYM', 'keyword: COMMENT_SYM',
        'keyword: COMMIT_SYM', 'keyword: CONTAINS_SYM', 'keyword: DEALLOCATE_SYM',
        'keyword: DO_SYM', 'keyword: END', 'keyword: EXECUTE_SYM',
        'keyword: FLUSH_SYM', 'keyword: FORMAT_SYM', 'keyword: HANDLER_SYM',
        'keyword: HELP_SYM', 'keyword: HOST_SYM', 'keyword: INSTALL_SYM',
        'keyword: LANGUAGE_SYM', 'keyword: NO_SYM', 'keyword: OPEN_SYM',
        'keyword: OPTIONS_SYM', 'keyword: OWNER_SYM', 'keyword: PARSER_SYM',
        'keyword: PORT_SYM', 'keyword: PREPARE_SYM', 'keyword: REMOVE_SYM',
        'keyword: REPAIR', 'keyword: RESET_SYM', 'keyword: RESTORE_SYM',
        'keyword: ROLLBACK_SYM', 'keyword: SAVEPOINT_SYM', 'keyword: SECURITY_SYM',
        'keyword: SERVER_SYM', 'keyword: SIGNED_SYM', 'keyword: SOCKET_SYM',
        'keyword: SLAVE', 'keyword: SONAME_SYM', 'keyword: START_SYM',
        'keyword: STOP_SYM', 'keyword: TRUNCATE_SYM', 'keyword: UNICODE_SYM',
        'keyword: UNINSTALL_SYM', 'keyword: WRAPPER_SYM', 'keyword: XA_SYM',
        'keyword: UPGRADE_SYM', 'keyword: ACCOUNT_SYM', 'keyword: ALWAYS_SYM',
        'keyword: FOLLOWS_SYM', 'keyword: GROUP_REPLICATION', 'keyword: PARSE_GCOL_EXPR_SYM',
        'keyword: PRECEDES_SYM', 'keyword: SHUTDOWN', 'keyword_sp: ACTION',
        'keyword_sp: ADDDATE_SYM', 'keyword_sp: AFTER_SYM', 'keyword_sp: AGAINST',
        'keyword_sp: AGGREGATE_SYM', 'keyword_sp: ALGORITHM_SYM', 'keyword_sp: ANALYSE_SYM',
        'keyword_sp: ANY_SYM', 'keyword_sp: AT_SYM', 'keyword_sp: AUTO_INC',
        'keyword_sp: AUTOEXTEND_SIZE_SYM', 'keyword_sp: AVG_ROW_LENGTH', 'keyword_sp: AVG_SYM',
        'keyword_sp: BINLOG_SYM', 'keyword_sp: BIT_SYM', 'keyword_sp: BLOCK_SYM',
        'keyword_sp: BOOL_SYM', 'keyword_sp: BOOLEAN_SYM', 'keyword_sp: BTREE_SYM',
        'keyword_sp: CASCADED', 'keyword_sp: CATALOG_NAME_SYM', 'keyword_sp: CHAIN_SYM',
        'keyword_sp: CHANGED', 'keyword_sp: CIPHER_SYM', 'keyword_sp: CLIENT_SYM',
        'keyword_sp: CLASS_ORIGIN_SYM', 'keyword_sp: COALESCE', 'keyword_sp: CODE_SYM',
        'keyword_sp: COLLATION_SYM', 'keyword_sp: COLUMN_NAME_SYM', 'keyword_sp: COLUMN_FORMAT_SYM',
        'keyword_sp: COLUMNS', 'keyword_sp: COMMITTED_SYM', 'keyword_sp: COMPACT_SYM',
        'keyword_sp: COMPLETION_SYM', 'keyword_sp: COMPRESSED_SYM', 'keyword_sp: CONCURRENT',
        'keyword_sp: CONNECTION_SYM', 'keyword_sp: CONSISTENT_SYM', 'keyword_sp: CONSTRAINT_CATALOG_SYM',
        'keyword_sp: CONSTRAINT_SCHEMA_SYM', 'keyword_sp: CONSTRAINT_NAME_SYM', 'keyword_sp: CONTEXT_SYM',
        'keyword_sp: CPU_SYM', 'keyword_sp: CUBE_SYM', 'keyword_sp: CURRENT_SYM',
        'keyword_sp: CURSOR_NAME_SYM', 'keyword_sp: DATA_SYM', 'keyword_sp: DATAFILE_SYM',
        'keyword_sp: DATETIME', 'keyword_sp: DATE_SYM', 'keyword_sp: DAY_SYM',
        'keyword_sp: DEFAULT_AUTH_SYM', 'keyword_sp: DEFINER_SYM', 'keyword_sp: DELAY_KEY_WRITE_SYM',
        'keyword_sp: DES_KEY_FILE', 'keyword_sp: DIAGNOSTICS_SYM', 'keyword_sp: DIRECTORY_SYM',
        'keyword_sp: DISABLE_SYM', 'keyword_sp: DISCARD', 'keyword_sp: DISK_SYM',
        'keyword_sp: DUMPFILE', 'keyword_sp: DUPLICATE_SYM', 'keyword_sp: DYNAMIC_SYM',
        'keyword_sp: ENDS_SYM', 'keyword_sp: ENUM', 'keyword_sp: ENGINE_SYM',
        'keyword_sp: ENGINES_SYM', 'keyword_sp: ERROR_SYM', 'keyword_sp: ERRORS',
        'keyword_sp: ESCAPE_SYM', 'keyword_sp: EVENT_SYM', 'keyword_sp: EVENTS_SYM',
        'keyword_sp: EVERY_SYM', 'keyword_sp: EXCHANGE_SYM', 'keyword_sp: EXPANSION_SYM',
        'keyword_sp: EXPIRE_SYM', 'keyword_sp: EXPORT_SYM', 'keyword_sp: EXTENDED_SYM',
        'keyword_sp: EXTENT_SIZE_SYM', 'keyword_sp: FAULTS_SYM', 'keyword_sp: FAST_SYM',
        'keyword_sp: FOUND_SYM', 'keyword_sp: ENABLE_SYM', 'keyword_sp: FULL',
        'keyword_sp: FILE_SYM', 'keyword_sp: FIRST_SYM', 'keyword_sp: FIXED_SYM',
        'keyword_sp: GENERAL', 'keyword_sp: GEOMETRY_SYM', 'keyword_sp: GEOMETRYCOLLECTION',
        'keyword_sp: GET_FORMAT', 'keyword_sp: GRANTS', 'keyword_sp: GLOBAL_SYM',
        'keyword_sp: HASH_SYM', 'keyword_sp: HOSTS_SYM', 'keyword_sp: HOUR_SYM',
        'keyword_sp: IDENTIFIED_SYM', 'keyword_sp: IGNORE_SERVER_IDS_SYM', 'keyword_sp: INVOKER_SYM',
        'keyword_sp: IMPORT', 'keyword_sp: INDEXES', 'keyword_sp: INITIAL_SIZE_SYM',
        'keyword_sp: IO_SYM', 'keyword_sp: IPC_SYM', 'keyword_sp: ISOLATION',
        'keyword_sp: ISSUER_SYM', 'keyword_sp: INSERT_METHOD', 'keyword_sp: KEY_BLOCK_SIZE',
        'keyword_sp: LAST_SYM', 'keyword_sp: LEAVES', 'keyword_sp: LESS_SYM',
        'keyword_sp: LEVEL_SYM', 'keyword_sp: LINESTRING', 'keyword_sp: LIST_SYM',
        'keyword_sp: LOCAL_SYM', 'keyword_sp: LOCKS_SYM', 'keyword_sp: LOGFILE_SYM',
        'keyword_sp: LOGS_SYM', 'keyword_sp: MAX_ROWS', 'keyword_sp: MASTER_SYM',
        'keyword_sp: MASTER_HEARTBEAT_PERIOD_SYM', 'keyword_sp: MASTER_HOST_SYM', 'keyword_sp: MASTER_PORT_SYM',
        'keyword_sp: MASTER_LOG_FILE_SYM', 'keyword_sp: MASTER_LOG_POS_SYM', 'keyword_sp: MASTER_USER_SYM',
        'keyword_sp: MASTER_PASSWORD_SYM', 'keyword_sp: MASTER_SERVER_ID_SYM', 'keyword_sp: MASTER_CONNECT_RETRY_SYM',
        'keyword_sp: MASTER_RETRY_COUNT_SYM', 'keyword_sp: MASTER_DELAY_SYM', 'keyword_sp: MASTER_SSL_SYM',
        'keyword_sp: MASTER_SSL_CA_SYM', 'keyword_sp: MASTER_SSL_CAPATH_SYM', 'keyword_sp: MASTER_SSL_CERT_SYM',
        'keyword_sp: MASTER_SSL_CIPHER_SYM', 'keyword_sp: MASTER_SSL_CRL_SYM', 'keyword_sp: MASTER_SSL_CRLPATH_SYM',
        'keyword_sp: MASTER_SSL_KEY_SYM', 'keyword_sp: MASTER_AUTO_POSITION_SYM', 'keyword_sp: MAX_CONNECTIONS_PER_HOUR',
        'keyword_sp: MAX_QUERIES_PER_HOUR', 'keyword_sp: MAX_SIZE_SYM', 'keyword_sp: MAX_UPDATES_PER_HOUR',
        'keyword_sp: MAX_USER_CONNECTIONS_SYM', 'keyword_sp: MEDIUM_SYM', 'keyword_sp: MEMORY_SYM',
        'keyword_sp: MERGE_SYM', 'keyword_sp: MESSAGE_TEXT_SYM', 'keyword_sp: MICROSECOND_SYM',
        'keyword_sp: MIGRATE_SYM', 'keyword_sp: MINUTE_SYM', 'keyword_sp: MIN_ROWS',
        'keyword_sp: MODIFY_SYM', 'keyword_sp: MODE_SYM', 'keyword_sp: MONTH_SYM',
        'keyword_sp: MULTILINESTRING', 'keyword_sp: MULTIPOINT', 'keyword_sp: MULTIPOLYGON',
        'keyword_sp: MUTEX_SYM', 'keyword_sp: MYSQL_ERRNO_SYM', 'keyword_sp: NAME_SYM',
        'keyword_sp: NAMES_SYM', 'keyword_sp: NATIONAL_SYM', 'keyword_sp: NCHAR_SYM',
        'keyword_sp: NDBCLUSTER_SYM', 'keyword_sp: NEXT_SYM', 'keyword_sp: NEW_SYM',
        'keyword_sp: NO_WAIT_SYM', 'keyword_sp: NODEGROUP_SYM', 'keyword_sp: NONE_SYM',
        'keyword_sp: NUMBER_SYM', 'keyword_sp: NVARCHAR_SYM', 'keyword_sp: OFFSET_SYM',
        'keyword_sp: OLD_PASSWORD', 'keyword_sp: ONE_SYM', 'keyword_sp: ONLY_SYM',
        'keyword_sp: PACK_KEYS_SYM', 'keyword_sp: PAGE_SYM', 'keyword_sp: PARTIAL',
        'keyword_sp: PARTITIONING_SYM', 'keyword_sp: PARTITIONS_SYM', 'keyword_sp: PASSWORD',
        'keyword_sp: PHASE_SYM', 'keyword_sp: PLUGIN_DIR_SYM', 'keyword_sp: PLUGIN_SYM',
        'keyword_sp: PLUGINS_SYM', 'keyword_sp: POINT_SYM', 'keyword_sp: POLYGON',
        'keyword_sp: PRESERVE_SYM', 'keyword_sp: PREV_SYM', 'keyword_sp: PRIVILEGES',
        'keyword_sp: PROCESS', 'keyword_sp: PROCESSLIST_SYM', 'keyword_sp: PROFILE_SYM',
        'keyword_sp: PROFILES_SYM', 'keyword_sp: PROXY_SYM', 'keyword_sp: QUARTER_SYM',
        'keyword_sp: QUERY_SYM', 'keyword_sp: QUICK', 'keyword_sp: READ_ONLY_SYM',
        'keyword_sp: REBUILD_SYM', 'keyword_sp: RECOVER_SYM', 'keyword_sp: REDO_BUFFER_SIZE_SYM',
        'keyword_sp: REDOFILE_SYM', 'keyword_sp: REDUNDANT_SYM', 'keyword_sp: RELAY',
        'keyword_sp: RELAYLOG_SYM', 'keyword_sp: RELAY_LOG_FILE_SYM', 'keyword_sp: RELAY_LOG_POS_SYM',
        'keyword_sp: RELAY_THREAD', 'keyword_sp: RELOAD', 'keyword_sp: REORGANIZE_SYM',
        'keyword_sp: REPEATABLE_SYM', 'keyword_sp: REPLICATION', 'keyword_sp: RESOURCES',
        'keyword_sp: RESUME_SYM', 'keyword_sp: RETURNED_SQLSTATE_SYM', 'keyword_sp: RETURNS_SYM',
        'keyword_sp: REVERSE_SYM', 'keyword_sp: ROLLUP_SYM', 'keyword_sp: ROUTINE_SYM',
        'keyword_sp: ROWS_SYM', 'keyword_sp: ROW_COUNT_SYM', 'keyword_sp: ROW_FORMAT_SYM',
        'keyword_sp: ROW_SYM', 'keyword_sp: RTREE_SYM', 'keyword_sp: SCHEDULE_SYM',
        'keyword_sp: SCHEMA_NAME_SYM', 'keyword_sp: SECOND_SYM', 'keyword_sp: SERIAL_SYM',
        'keyword_sp: SERIALIZABLE_SYM', 'keyword_sp: SESSION_SYM', 'keyword_sp: SIMPLE_SYM',
        'keyword_sp: SHARE_SYM', 'keyword_sp: SHUTDOWN', 'keyword_sp: SLOW',
        'keyword_sp: SNAPSHOT_SYM', 'keyword_sp: SOUNDS_SYM', 'keyword_sp: SOURCE_SYM',
        'keyword_sp: SQL_AFTER_GTIDS', 'keyword_sp: SQL_AFTER_MTS_GAPS', 'keyword_sp: SQL_BEFORE_GTIDS',
        'keyword_sp: SQL_CACHE_SYM', 'keyword_sp: SQL_BUFFER_RESULT', 'keyword_sp: SQL_NO_CACHE_SYM',
        'keyword_sp: SQL_THREAD', 'keyword_sp: STARTS_SYM', 'keyword_sp: STATS_AUTO_RECALC_SYM',
        'keyword_sp: STATS_PERSISTENT_SYM', 'keyword_sp: STATS_SAMPLE_PAGES_SYM', 'keyword_sp: STATUS_SYM',
        'keyword_sp: STORAGE_SYM', 'keyword_sp: STRING_SYM', 'keyword_sp: SUBCLASS_ORIGIN_SYM',
        'keyword_sp: SUBDATE_SYM', 'keyword_sp: SUBJECT_SYM', 'keyword_sp: SUBPARTITION_SYM',
        'keyword_sp: SUBPARTITIONS_SYM', 'keyword_sp: SUPER_SYM', 'keyword_sp: SUSPEND_SYM',
        'keyword_sp: SWAPS_SYM', 'keyword_sp: SWITCHES_SYM', 'keyword_sp: TABLE_NAME_SYM',
        'keyword_sp: TABLES', 'keyword_sp: TABLE_CHECKSUM_SYM', 'keyword_sp: TABLESPACE',
        'keyword_sp: TEMPORARY', 'keyword_sp: TEMPTABLE_SYM', 'keyword_sp: TEXT_SYM',
        'keyword_sp: THAN_SYM', 'keyword_sp: TRANSACTION_SYM', 'keyword_sp: TRIGGERS_SYM',
        'keyword_sp: TIMESTAMP', 'keyword_sp: TIMESTAMP_ADD', 'keyword_sp: TIMESTAMP_DIFF',
        'keyword_sp: TIME_SYM', 'keyword_sp: TYPES_SYM', 'keyword_sp: TYPE_SYM',
        'keyword_sp: UDF_RETURNS_SYM', 'keyword_sp: FUNCTION_SYM', 'keyword_sp: UNCOMMITTED_SYM',
        'keyword_sp: UNDEFINED_SYM', 'keyword_sp: UNDO_BUFFER_SIZE_SYM', 'keyword_sp: UNDOFILE_SYM',
        'keyword_sp: UNKNOWN_SYM', 'keyword_sp: UNTIL_SYM', 'keyword_sp: USER',
        'keyword_sp: USE_FRM', 'keyword_sp: VARIABLES', 'keyword_sp: VIEW_SYM',
        'keyword_sp: VALUE_SYM', 'keyword_sp: WARNINGS', 'keyword_sp: WAIT_SYM',
        'keyword_sp: WEEK_SYM', 'keyword_sp: WORK_SYM', 'keyword_sp: WEIGHT_STRING_SYM',
        'keyword_sp: X509_SYM', 'keyword_sp: XML_SYM', 'keyword_sp: YEAR_SYM',
        'keyword_sp: CHANNEL_SYM', 'keyword_sp: COMPRESSION_SYM', 'keyword_sp: ENCRYPTION_SYM',
        'keyword_sp: FILE_BLOCK_SIZE_SYM', 'keyword_sp: FILTER_SYM', 'keyword_sp: INSTANCE_SYM',
        'keyword_sp: JSON_SYM', 'keyword_sp: MASTER_TLS_VERSION_SYM', 'keyword_sp: NEVER_SYM',
        'keyword_sp: REPLICATE_DO_DB', 'keyword_sp: REPLICATE_IGNORE_DB', 'keyword_sp: REPLICATE_DO_TABLE',
        'keyword_sp: REPLICATE_IGNORE_TABLE', 'keyword_sp: REPLICATE_WILD_DO_TABLE', 'keyword_sp: REPLICATE_WILD_IGNORE_TABLE',
        'keyword_sp: REPLICATE_REWRITE_DB', 'keyword_sp: ROTATE_SYM', 'keyword_sp: STACKED_SYM',
        'keyword_sp: TABLESPACE_SYM', 'keyword_sp: VALIDATION_SYM', 'keyword_sp: WITHOUT_SYM',
        'keyword_sp: XID_SYM',
    ];
}
