<?php

declare(strict_types=1);

namespace SqlSemantics\Platform\MySql\Lowering\Leaf;

/**
 * The keywords MySQL 8.0 and later accept as identifiers at every identifier position: the rule `ident_keywords_unambiguous`.
 *
 * Each signature is a production whose only symbol is a keyword terminal; at
 * such a production the keyword is the identifier it spells. The list is the
 * union over every shipped release that has the rule.
 * Source: https://dev.mysql.com/doc/refman/8.4/en/keywords.html.
 *
 * @visibility SqlSemantics\Platform\MySql
 */
final class UnambiguousKeywords
{
    /**
     * The keyword-as-identifier productions.
     */
    public const SIGNATURES = [
        'ident_keywords_unambiguous: ACTION', 'ident_keywords_unambiguous: ACCOUNT_SYM', 'ident_keywords_unambiguous: ACTIVE_SYM',
        'ident_keywords_unambiguous: ADDDATE_SYM', 'ident_keywords_unambiguous: ADMIN_SYM', 'ident_keywords_unambiguous: AFTER_SYM',
        'ident_keywords_unambiguous: AGAINST', 'ident_keywords_unambiguous: AGGREGATE_SYM', 'ident_keywords_unambiguous: ALGORITHM_SYM',
        'ident_keywords_unambiguous: ALWAYS_SYM', 'ident_keywords_unambiguous: ANY_SYM', 'ident_keywords_unambiguous: ARRAY_SYM',
        'ident_keywords_unambiguous: AT_SYM', 'ident_keywords_unambiguous: ATTRIBUTE_SYM', 'ident_keywords_unambiguous: AUTHENTICATION_SYM',
        'ident_keywords_unambiguous: AUTOEXTEND_SIZE_SYM', 'ident_keywords_unambiguous: AUTO_INC', 'ident_keywords_unambiguous: AVG_ROW_LENGTH',
        'ident_keywords_unambiguous: AVG_SYM', 'ident_keywords_unambiguous: BACKUP_SYM', 'ident_keywords_unambiguous: BINLOG_SYM',
        'ident_keywords_unambiguous: BIT_SYM', 'ident_keywords_unambiguous: BLOCK_SYM', 'ident_keywords_unambiguous: BOOLEAN_SYM',
        'ident_keywords_unambiguous: BOOL_SYM', 'ident_keywords_unambiguous: BTREE_SYM', 'ident_keywords_unambiguous: BUCKETS_SYM',
        'ident_keywords_unambiguous: BULK_SYM', 'ident_keywords_unambiguous: CASCADED', 'ident_keywords_unambiguous: CATALOG_NAME_SYM',
        'ident_keywords_unambiguous: CHAIN_SYM', 'ident_keywords_unambiguous: CHALLENGE_RESPONSE_SYM', 'ident_keywords_unambiguous: CHANGED',
        'ident_keywords_unambiguous: CHANNEL_SYM', 'ident_keywords_unambiguous: CIPHER_SYM', 'ident_keywords_unambiguous: CLASS_ORIGIN_SYM',
        'ident_keywords_unambiguous: CLIENT_SYM', 'ident_keywords_unambiguous: CLOSE_SYM', 'ident_keywords_unambiguous: COALESCE',
        'ident_keywords_unambiguous: CODE_SYM', 'ident_keywords_unambiguous: COLLATION_SYM', 'ident_keywords_unambiguous: COLUMNS',
        'ident_keywords_unambiguous: COLUMN_FORMAT_SYM', 'ident_keywords_unambiguous: COLUMN_NAME_SYM', 'ident_keywords_unambiguous: COMMITTED_SYM',
        'ident_keywords_unambiguous: COMPACT_SYM', 'ident_keywords_unambiguous: COMPLETION_SYM', 'ident_keywords_unambiguous: COMPONENT_SYM',
        'ident_keywords_unambiguous: COMPRESSED_SYM', 'ident_keywords_unambiguous: COMPRESSION_SYM', 'ident_keywords_unambiguous: CONCURRENT',
        'ident_keywords_unambiguous: CONNECTION_SYM', 'ident_keywords_unambiguous: CONSISTENT_SYM', 'ident_keywords_unambiguous: CONSTRAINT_CATALOG_SYM',
        'ident_keywords_unambiguous: CONSTRAINT_NAME_SYM', 'ident_keywords_unambiguous: CONSTRAINT_SCHEMA_SYM', 'ident_keywords_unambiguous: CONTEXT_SYM',
        'ident_keywords_unambiguous: CPU_SYM', 'ident_keywords_unambiguous: CURRENT_SYM', 'ident_keywords_unambiguous: CURSOR_NAME_SYM',
        'ident_keywords_unambiguous: DATAFILE_SYM', 'ident_keywords_unambiguous: DATA_SYM', 'ident_keywords_unambiguous: DATETIME_SYM',
        'ident_keywords_unambiguous: DATE_SYM', 'ident_keywords_unambiguous: DAY_SYM', 'ident_keywords_unambiguous: DEFAULT_AUTH_SYM',
        'ident_keywords_unambiguous: DEFINER_SYM', 'ident_keywords_unambiguous: DEFINITION_SYM', 'ident_keywords_unambiguous: DELAY_KEY_WRITE_SYM',
        'ident_keywords_unambiguous: DESCRIPTION_SYM', 'ident_keywords_unambiguous: DIAGNOSTICS_SYM', 'ident_keywords_unambiguous: DIRECTORY_SYM',
        'ident_keywords_unambiguous: DISABLE_SYM', 'ident_keywords_unambiguous: DISCARD_SYM', 'ident_keywords_unambiguous: DISK_SYM',
        'ident_keywords_unambiguous: DUMPFILE', 'ident_keywords_unambiguous: DUPLICATE_SYM', 'ident_keywords_unambiguous: DYNAMIC_SYM',
        'ident_keywords_unambiguous: ENABLE_SYM', 'ident_keywords_unambiguous: ENCRYPTION_SYM', 'ident_keywords_unambiguous: ENDS_SYM',
        'ident_keywords_unambiguous: ENFORCED_SYM', 'ident_keywords_unambiguous: ENGINES_SYM', 'ident_keywords_unambiguous: ENGINE_SYM',
        'ident_keywords_unambiguous: ENGINE_ATTRIBUTE_SYM', 'ident_keywords_unambiguous: ENUM_SYM', 'ident_keywords_unambiguous: ERRORS',
        'ident_keywords_unambiguous: ERROR_SYM', 'ident_keywords_unambiguous: ESCAPE_SYM', 'ident_keywords_unambiguous: EVENTS_SYM',
        'ident_keywords_unambiguous: EVERY_SYM', 'ident_keywords_unambiguous: EXCHANGE_SYM', 'ident_keywords_unambiguous: EXCLUDE_SYM',
        'ident_keywords_unambiguous: EXPANSION_SYM', 'ident_keywords_unambiguous: EXPIRE_SYM', 'ident_keywords_unambiguous: EXPORT_SYM',
        'ident_keywords_unambiguous: EXTENDED_SYM', 'ident_keywords_unambiguous: EXTENT_SIZE_SYM', 'ident_keywords_unambiguous: FACTOR_SYM',
        'ident_keywords_unambiguous: FAILED_LOGIN_ATTEMPTS_SYM', 'ident_keywords_unambiguous: FAST_SYM', 'ident_keywords_unambiguous: FAULTS_SYM',
        'ident_keywords_unambiguous: FILE_BLOCK_SIZE_SYM', 'ident_keywords_unambiguous: FILTER_SYM', 'ident_keywords_unambiguous: FINISH_SYM',
        'ident_keywords_unambiguous: FIRST_SYM', 'ident_keywords_unambiguous: FIXED_SYM', 'ident_keywords_unambiguous: FOLLOWING_SYM',
        'ident_keywords_unambiguous: FORMAT_SYM', 'ident_keywords_unambiguous: FOUND_SYM', 'ident_keywords_unambiguous: FULL',
        'ident_keywords_unambiguous: GENERAL', 'ident_keywords_unambiguous: GENERATE_SYM', 'ident_keywords_unambiguous: GEOMETRYCOLLECTION_SYM',
        'ident_keywords_unambiguous: GEOMETRY_SYM', 'ident_keywords_unambiguous: GET_FORMAT', 'ident_keywords_unambiguous: GET_MASTER_PUBLIC_KEY_SYM',
        'ident_keywords_unambiguous: GET_SOURCE_PUBLIC_KEY_SYM', 'ident_keywords_unambiguous: GRANTS', 'ident_keywords_unambiguous: GROUP_REPLICATION',
        'ident_keywords_unambiguous: GTID_ONLY_SYM', 'ident_keywords_unambiguous: HASH_SYM', 'ident_keywords_unambiguous: HISTOGRAM_SYM',
        'ident_keywords_unambiguous: HISTORY_SYM', 'ident_keywords_unambiguous: HOSTS_SYM', 'ident_keywords_unambiguous: HOST_SYM',
        'ident_keywords_unambiguous: HOUR_SYM', 'ident_keywords_unambiguous: IDENTIFIED_SYM', 'ident_keywords_unambiguous: IGNORE_SERVER_IDS_SYM',
        'ident_keywords_unambiguous: INACTIVE_SYM', 'ident_keywords_unambiguous: INDEXES', 'ident_keywords_unambiguous: INITIAL_SIZE_SYM',
        'ident_keywords_unambiguous: INITIAL_SYM', 'ident_keywords_unambiguous: INITIATE_SYM', 'ident_keywords_unambiguous: INSERT_METHOD',
        'ident_keywords_unambiguous: INSTANCE_SYM', 'ident_keywords_unambiguous: INVISIBLE_SYM', 'ident_keywords_unambiguous: INVOKER_SYM',
        'ident_keywords_unambiguous: IO_SYM', 'ident_keywords_unambiguous: IPC_SYM', 'ident_keywords_unambiguous: ISOLATION',
        'ident_keywords_unambiguous: ISSUER_SYM', 'ident_keywords_unambiguous: JSON_SYM', 'ident_keywords_unambiguous: JSON_VALUE_SYM',
        'ident_keywords_unambiguous: KEY_BLOCK_SIZE', 'ident_keywords_unambiguous: KEYRING_SYM', 'ident_keywords_unambiguous: LAST_SYM',
        'ident_keywords_unambiguous: LEAVES', 'ident_keywords_unambiguous: LESS_SYM', 'ident_keywords_unambiguous: LEVEL_SYM',
        'ident_keywords_unambiguous: LINESTRING_SYM', 'ident_keywords_unambiguous: LIST_SYM', 'ident_keywords_unambiguous: LOCKED_SYM',
        'ident_keywords_unambiguous: LOCKS_SYM', 'ident_keywords_unambiguous: LOGFILE_SYM', 'ident_keywords_unambiguous: LOGS_SYM',
        'ident_keywords_unambiguous: MASTER_AUTO_POSITION_SYM', 'ident_keywords_unambiguous: MASTER_COMPRESSION_ALGORITHM_SYM', 'ident_keywords_unambiguous: MASTER_CONNECT_RETRY_SYM',
        'ident_keywords_unambiguous: MASTER_DELAY_SYM', 'ident_keywords_unambiguous: MASTER_HEARTBEAT_PERIOD_SYM', 'ident_keywords_unambiguous: MASTER_HOST_SYM',
        'ident_keywords_unambiguous: NETWORK_NAMESPACE_SYM', 'ident_keywords_unambiguous: MASTER_LOG_FILE_SYM', 'ident_keywords_unambiguous: MASTER_LOG_POS_SYM',
        'ident_keywords_unambiguous: MASTER_PASSWORD_SYM', 'ident_keywords_unambiguous: MASTER_PORT_SYM', 'ident_keywords_unambiguous: MASTER_PUBLIC_KEY_PATH_SYM',
        'ident_keywords_unambiguous: MASTER_RETRY_COUNT_SYM', 'ident_keywords_unambiguous: MASTER_SSL_CAPATH_SYM', 'ident_keywords_unambiguous: MASTER_SSL_CA_SYM',
        'ident_keywords_unambiguous: MASTER_SSL_CERT_SYM', 'ident_keywords_unambiguous: MASTER_SSL_CIPHER_SYM', 'ident_keywords_unambiguous: MASTER_SSL_CRLPATH_SYM',
        'ident_keywords_unambiguous: MASTER_SSL_CRL_SYM', 'ident_keywords_unambiguous: MASTER_SSL_KEY_SYM', 'ident_keywords_unambiguous: MASTER_SSL_SYM',
        'ident_keywords_unambiguous: MASTER_SYM', 'ident_keywords_unambiguous: MASTER_TLS_CIPHERSUITES_SYM', 'ident_keywords_unambiguous: MASTER_TLS_VERSION_SYM',
        'ident_keywords_unambiguous: MASTER_USER_SYM', 'ident_keywords_unambiguous: MASTER_ZSTD_COMPRESSION_LEVEL_SYM', 'ident_keywords_unambiguous: MAX_CONNECTIONS_PER_HOUR',
        'ident_keywords_unambiguous: MAX_QUERIES_PER_HOUR', 'ident_keywords_unambiguous: MAX_ROWS', 'ident_keywords_unambiguous: MAX_SIZE_SYM',
        'ident_keywords_unambiguous: MAX_UPDATES_PER_HOUR', 'ident_keywords_unambiguous: MAX_USER_CONNECTIONS_SYM', 'ident_keywords_unambiguous: MEDIUM_SYM',
        'ident_keywords_unambiguous: MEMBER_SYM', 'ident_keywords_unambiguous: MEMORY_SYM', 'ident_keywords_unambiguous: MERGE_SYM',
        'ident_keywords_unambiguous: MESSAGE_TEXT_SYM', 'ident_keywords_unambiguous: MICROSECOND_SYM', 'ident_keywords_unambiguous: MIGRATE_SYM',
        'ident_keywords_unambiguous: MINUTE_SYM', 'ident_keywords_unambiguous: MIN_ROWS', 'ident_keywords_unambiguous: MODE_SYM',
        'ident_keywords_unambiguous: MODIFY_SYM', 'ident_keywords_unambiguous: MONTH_SYM', 'ident_keywords_unambiguous: MULTILINESTRING_SYM',
        'ident_keywords_unambiguous: MULTIPOINT_SYM', 'ident_keywords_unambiguous: MULTIPOLYGON_SYM', 'ident_keywords_unambiguous: MUTEX_SYM',
        'ident_keywords_unambiguous: MYSQL_ERRNO_SYM', 'ident_keywords_unambiguous: NAMES_SYM', 'ident_keywords_unambiguous: NAME_SYM',
        'ident_keywords_unambiguous: NATIONAL_SYM', 'ident_keywords_unambiguous: NCHAR_SYM', 'ident_keywords_unambiguous: NDBCLUSTER_SYM',
        'ident_keywords_unambiguous: NESTED_SYM', 'ident_keywords_unambiguous: NEVER_SYM', 'ident_keywords_unambiguous: NEW_SYM',
        'ident_keywords_unambiguous: NEXT_SYM', 'ident_keywords_unambiguous: NODEGROUP_SYM', 'ident_keywords_unambiguous: NOWAIT_SYM',
        'ident_keywords_unambiguous: NO_WAIT_SYM', 'ident_keywords_unambiguous: NULLS_SYM', 'ident_keywords_unambiguous: NUMBER_SYM',
        'ident_keywords_unambiguous: NVARCHAR_SYM', 'ident_keywords_unambiguous: OFF_SYM', 'ident_keywords_unambiguous: OFFSET_SYM',
        'ident_keywords_unambiguous: OJ_SYM', 'ident_keywords_unambiguous: OLD_SYM', 'ident_keywords_unambiguous: ONE_SYM',
        'ident_keywords_unambiguous: ONLY_SYM', 'ident_keywords_unambiguous: OPEN_SYM', 'ident_keywords_unambiguous: OPTIONAL_SYM',
        'ident_keywords_unambiguous: OPTIONS_SYM', 'ident_keywords_unambiguous: ORDINALITY_SYM', 'ident_keywords_unambiguous: ORGANIZATION_SYM',
        'ident_keywords_unambiguous: OTHERS_SYM', 'ident_keywords_unambiguous: OWNER_SYM', 'ident_keywords_unambiguous: PACK_KEYS_SYM',
        'ident_keywords_unambiguous: PAGE_SYM', 'ident_keywords_unambiguous: PARSER_SYM', 'ident_keywords_unambiguous: PARTIAL',
        'ident_keywords_unambiguous: PARTITIONING_SYM', 'ident_keywords_unambiguous: PARTITIONS_SYM', 'ident_keywords_unambiguous: PASSWORD',
        'ident_keywords_unambiguous: PASSWORD_LOCK_TIME_SYM', 'ident_keywords_unambiguous: PATH_SYM', 'ident_keywords_unambiguous: PHASE_SYM',
        'ident_keywords_unambiguous: PLUGINS_SYM', 'ident_keywords_unambiguous: PLUGIN_DIR_SYM', 'ident_keywords_unambiguous: PLUGIN_SYM',
        'ident_keywords_unambiguous: POINT_SYM', 'ident_keywords_unambiguous: POLYGON_SYM', 'ident_keywords_unambiguous: PORT_SYM',
        'ident_keywords_unambiguous: PRECEDING_SYM', 'ident_keywords_unambiguous: PRESERVE_SYM', 'ident_keywords_unambiguous: PREV_SYM',
        'ident_keywords_unambiguous: PRIVILEGES', 'ident_keywords_unambiguous: PRIVILEGE_CHECKS_USER_SYM', 'ident_keywords_unambiguous: PROCESSLIST_SYM',
        'ident_keywords_unambiguous: PROFILES_SYM', 'ident_keywords_unambiguous: PROFILE_SYM', 'ident_keywords_unambiguous: QUARTER_SYM',
        'ident_keywords_unambiguous: QUERY_SYM', 'ident_keywords_unambiguous: QUICK', 'ident_keywords_unambiguous: RANDOM_SYM',
        'ident_keywords_unambiguous: READ_ONLY_SYM', 'ident_keywords_unambiguous: REBUILD_SYM', 'ident_keywords_unambiguous: RECOVER_SYM',
        'ident_keywords_unambiguous: REDO_BUFFER_SIZE_SYM', 'ident_keywords_unambiguous: REDUNDANT_SYM', 'ident_keywords_unambiguous: REFERENCE_SYM',
        'ident_keywords_unambiguous: REGISTRATION_SYM', 'ident_keywords_unambiguous: RELAY', 'ident_keywords_unambiguous: RELAYLOG_SYM',
        'ident_keywords_unambiguous: RELAY_LOG_FILE_SYM', 'ident_keywords_unambiguous: RELAY_LOG_POS_SYM', 'ident_keywords_unambiguous: RELAY_THREAD',
        'ident_keywords_unambiguous: REMOVE_SYM', 'ident_keywords_unambiguous: ASSIGN_GTIDS_TO_ANONYMOUS_TRANSACTIONS_SYM', 'ident_keywords_unambiguous: REORGANIZE_SYM',
        'ident_keywords_unambiguous: REPEATABLE_SYM', 'ident_keywords_unambiguous: REPLICAS_SYM', 'ident_keywords_unambiguous: REPLICATE_DO_DB',
        'ident_keywords_unambiguous: REPLICATE_DO_TABLE', 'ident_keywords_unambiguous: REPLICATE_IGNORE_DB', 'ident_keywords_unambiguous: REPLICATE_IGNORE_TABLE',
        'ident_keywords_unambiguous: REPLICATE_REWRITE_DB', 'ident_keywords_unambiguous: REPLICATE_WILD_DO_TABLE', 'ident_keywords_unambiguous: REPLICATE_WILD_IGNORE_TABLE',
        'ident_keywords_unambiguous: REPLICA_SYM', 'ident_keywords_unambiguous: REQUIRE_ROW_FORMAT_SYM', 'ident_keywords_unambiguous: REQUIRE_TABLE_PRIMARY_KEY_CHECK_SYM',
        'ident_keywords_unambiguous: RESOURCES', 'ident_keywords_unambiguous: RESPECT_SYM', 'ident_keywords_unambiguous: RESTORE_SYM',
        'ident_keywords_unambiguous: RESUME_SYM', 'ident_keywords_unambiguous: RETAIN_SYM', 'ident_keywords_unambiguous: RETURNED_SQLSTATE_SYM',
        'ident_keywords_unambiguous: RETURNING_SYM', 'ident_keywords_unambiguous: RETURNS_SYM', 'ident_keywords_unambiguous: REUSE_SYM',
        'ident_keywords_unambiguous: REVERSE_SYM', 'ident_keywords_unambiguous: ROLE_SYM', 'ident_keywords_unambiguous: ROLLUP_SYM',
        'ident_keywords_unambiguous: ROTATE_SYM', 'ident_keywords_unambiguous: ROUTINE_SYM', 'ident_keywords_unambiguous: ROW_COUNT_SYM',
        'ident_keywords_unambiguous: ROW_FORMAT_SYM', 'ident_keywords_unambiguous: RTREE_SYM', 'ident_keywords_unambiguous: SCHEDULE_SYM',
        'ident_keywords_unambiguous: SCHEMA_NAME_SYM', 'ident_keywords_unambiguous: SECONDARY_ENGINE_SYM', 'ident_keywords_unambiguous: SECONDARY_ENGINE_ATTRIBUTE_SYM',
        'ident_keywords_unambiguous: SECONDARY_LOAD_SYM', 'ident_keywords_unambiguous: SECONDARY_SYM', 'ident_keywords_unambiguous: SECONDARY_UNLOAD_SYM',
        'ident_keywords_unambiguous: SECOND_SYM', 'ident_keywords_unambiguous: SECURITY_SYM', 'ident_keywords_unambiguous: SERIALIZABLE_SYM',
        'ident_keywords_unambiguous: SERIAL_SYM', 'ident_keywords_unambiguous: SERVER_SYM', 'ident_keywords_unambiguous: SHARE_SYM',
        'ident_keywords_unambiguous: SIMPLE_SYM', 'ident_keywords_unambiguous: SKIP_SYM', 'ident_keywords_unambiguous: SLOW',
        'ident_keywords_unambiguous: SNAPSHOT_SYM', 'ident_keywords_unambiguous: SOCKET_SYM', 'ident_keywords_unambiguous: SONAME_SYM',
        'ident_keywords_unambiguous: SOUNDS_SYM', 'ident_keywords_unambiguous: SOURCE_AUTO_POSITION_SYM', 'ident_keywords_unambiguous: SOURCE_BIND_SYM',
        'ident_keywords_unambiguous: SOURCE_COMPRESSION_ALGORITHM_SYM', 'ident_keywords_unambiguous: SOURCE_CONNECTION_AUTO_FAILOVER_SYM', 'ident_keywords_unambiguous: SOURCE_CONNECT_RETRY_SYM',
        'ident_keywords_unambiguous: SOURCE_DELAY_SYM', 'ident_keywords_unambiguous: SOURCE_HEARTBEAT_PERIOD_SYM', 'ident_keywords_unambiguous: SOURCE_HOST_SYM',
        'ident_keywords_unambiguous: SOURCE_LOG_FILE_SYM', 'ident_keywords_unambiguous: SOURCE_LOG_POS_SYM', 'ident_keywords_unambiguous: SOURCE_PASSWORD_SYM',
        'ident_keywords_unambiguous: SOURCE_PORT_SYM', 'ident_keywords_unambiguous: SOURCE_PUBLIC_KEY_PATH_SYM', 'ident_keywords_unambiguous: SOURCE_RETRY_COUNT_SYM',
        'ident_keywords_unambiguous: SOURCE_SSL_CAPATH_SYM', 'ident_keywords_unambiguous: SOURCE_SSL_CA_SYM', 'ident_keywords_unambiguous: SOURCE_SSL_CERT_SYM',
        'ident_keywords_unambiguous: SOURCE_SSL_CIPHER_SYM', 'ident_keywords_unambiguous: SOURCE_SSL_CRLPATH_SYM', 'ident_keywords_unambiguous: SOURCE_SSL_CRL_SYM',
        'ident_keywords_unambiguous: SOURCE_SSL_KEY_SYM', 'ident_keywords_unambiguous: SOURCE_SSL_SYM', 'ident_keywords_unambiguous: SOURCE_SSL_VERIFY_SERVER_CERT_SYM',
        'ident_keywords_unambiguous: SOURCE_SYM', 'ident_keywords_unambiguous: SOURCE_TLS_CIPHERSUITES_SYM', 'ident_keywords_unambiguous: SOURCE_TLS_VERSION_SYM',
        'ident_keywords_unambiguous: SOURCE_USER_SYM', 'ident_keywords_unambiguous: SOURCE_ZSTD_COMPRESSION_LEVEL_SYM', 'ident_keywords_unambiguous: SQL_AFTER_GTIDS',
        'ident_keywords_unambiguous: SQL_AFTER_MTS_GAPS', 'ident_keywords_unambiguous: SQL_BEFORE_GTIDS', 'ident_keywords_unambiguous: SQL_BUFFER_RESULT',
        'ident_keywords_unambiguous: SQL_NO_CACHE_SYM', 'ident_keywords_unambiguous: SQL_THREAD', 'ident_keywords_unambiguous: SRID_SYM',
        'ident_keywords_unambiguous: STACKED_SYM', 'ident_keywords_unambiguous: STARTS_SYM', 'ident_keywords_unambiguous: STATS_AUTO_RECALC_SYM',
        'ident_keywords_unambiguous: STATS_PERSISTENT_SYM', 'ident_keywords_unambiguous: STATS_SAMPLE_PAGES_SYM', 'ident_keywords_unambiguous: STATUS_SYM',
        'ident_keywords_unambiguous: STORAGE_SYM', 'ident_keywords_unambiguous: STREAM_SYM', 'ident_keywords_unambiguous: STRING_SYM',
        'ident_keywords_unambiguous: ST_COLLECT_SYM', 'ident_keywords_unambiguous: SUBCLASS_ORIGIN_SYM', 'ident_keywords_unambiguous: SUBDATE_SYM',
        'ident_keywords_unambiguous: SUBJECT_SYM', 'ident_keywords_unambiguous: SUBPARTITIONS_SYM', 'ident_keywords_unambiguous: SUBPARTITION_SYM',
        'ident_keywords_unambiguous: SUSPEND_SYM', 'ident_keywords_unambiguous: SWAPS_SYM', 'ident_keywords_unambiguous: SWITCHES_SYM',
        'ident_keywords_unambiguous: TABLES', 'ident_keywords_unambiguous: TABLESPACE_SYM', 'ident_keywords_unambiguous: TABLE_CHECKSUM_SYM',
        'ident_keywords_unambiguous: TABLE_NAME_SYM', 'ident_keywords_unambiguous: TEMPORARY', 'ident_keywords_unambiguous: TEMPTABLE_SYM',
        'ident_keywords_unambiguous: TEXT_SYM', 'ident_keywords_unambiguous: THAN_SYM', 'ident_keywords_unambiguous: THREAD_PRIORITY_SYM',
        'ident_keywords_unambiguous: TIES_SYM', 'ident_keywords_unambiguous: TIMESTAMP_ADD', 'ident_keywords_unambiguous: TIMESTAMP_DIFF',
        'ident_keywords_unambiguous: TIMESTAMP_SYM', 'ident_keywords_unambiguous: TIME_SYM', 'ident_keywords_unambiguous: TLS_SYM',
        'ident_keywords_unambiguous: TRANSACTION_SYM', 'ident_keywords_unambiguous: TRIGGERS_SYM', 'ident_keywords_unambiguous: TYPES_SYM',
        'ident_keywords_unambiguous: TYPE_SYM', 'ident_keywords_unambiguous: UNBOUNDED_SYM', 'ident_keywords_unambiguous: UNCOMMITTED_SYM',
        'ident_keywords_unambiguous: UNDEFINED_SYM', 'ident_keywords_unambiguous: UNDOFILE_SYM', 'ident_keywords_unambiguous: UNDO_BUFFER_SIZE_SYM',
        'ident_keywords_unambiguous: UNKNOWN_SYM', 'ident_keywords_unambiguous: UNREGISTER_SYM', 'ident_keywords_unambiguous: UNTIL_SYM',
        'ident_keywords_unambiguous: UPGRADE_SYM', 'ident_keywords_unambiguous: URL_SYM', 'ident_keywords_unambiguous: USER',
        'ident_keywords_unambiguous: USE_FRM', 'ident_keywords_unambiguous: VALIDATION_SYM', 'ident_keywords_unambiguous: VALUE_SYM',
        'ident_keywords_unambiguous: VARIABLES', 'ident_keywords_unambiguous: VCPU_SYM', 'ident_keywords_unambiguous: VIEW_SYM',
        'ident_keywords_unambiguous: VISIBLE_SYM', 'ident_keywords_unambiguous: WAIT_SYM', 'ident_keywords_unambiguous: WARNINGS',
        'ident_keywords_unambiguous: WEEK_SYM', 'ident_keywords_unambiguous: WEIGHT_STRING_SYM', 'ident_keywords_unambiguous: WITHOUT_SYM',
        'ident_keywords_unambiguous: WORK_SYM', 'ident_keywords_unambiguous: WRAPPER_SYM', 'ident_keywords_unambiguous: X509_SYM',
        'ident_keywords_unambiguous: XID_SYM', 'ident_keywords_unambiguous: XML_SYM', 'ident_keywords_unambiguous: YEAR_SYM',
        'ident_keywords_unambiguous: ZONE_SYM', 'ident_keywords_unambiguous: PARSE_TREE_SYM', 'ident_keywords_unambiguous: GTIDS_SYM',
        'ident_keywords_unambiguous: LOG_SYM', 'ident_keywords_unambiguous: S3_SYM', 'ident_keywords_unambiguous: AUTO_SYM',
        'ident_keywords_unambiguous: BERNOULLI_SYM', 'ident_keywords_unambiguous: VECTOR_SYM',
    ];
}
