<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\PostgreSql\Value;

/**
 * The a_expr SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\PostgreSql\Value\AExprWithAExprSimilarToAExprEscapeAExpr_e2fba479 $value): string => (new \SqlSemantics\Statement\Statement($value))->toString();
 *     $write instanceof \Closure // => true
 */
final class AExprWithAExprSimilarToAExprEscapeAExpr_e2fba479 implements \SqlSemantics\Statement\Model\PostgreSql\Role\AExprForm, \SqlSemantics\Statement\Model\PostgreSql\Role\CaseArgForm, \SqlSemantics\Statement\Model\PostgreSql\Role\ExprListForm, \SqlSemantics\Statement\Model\PostgreSql\Role\FuncArgExprForm, \SqlSemantics\Statement\Model\PostgreSql\Role\FuncArgListForm, \SqlSemantics\Statement\Model\PostgreSql\Role\FuncArgListOptForm, \SqlSemantics\Statement\Model\PostgreSql\Role\GroupByItemForm, \SqlSemantics\Statement\Model\PostgreSql\Role\GroupByListForm, \SqlSemantics\Statement\Model\PostgreSql\Role\OptSliceBoundForm, \SqlSemantics\Statement\Model\PostgreSql\Role\OptTargetListForm, \SqlSemantics\Statement\Model\PostgreSql\Role\SelectLimitValueForm, \SqlSemantics\Statement\Model\PostgreSql\Role\SelectOffsetValueForm, \SqlSemantics\Statement\Model\PostgreSql\Role\TargetElForm, \SqlSemantics\Statement\Model\PostgreSql\Role\TargetListForm, \SqlSemantics\Statement\Model\PostgreSql\Role\TrimListForm, \SqlSemantics\Statement\Model\PostgreSql\Role\XmlAttributeElForm, \SqlSemantics\Statement\Model\PostgreSql\Role\XmlAttributeListForm
{
    /**
     * Supplies the SQL values of this form.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\AExprForm $aExpr,
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\AExprForm $aExpr2,
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\AExprForm $aExpr3,
    ) {
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $this->aExpr->write($writer);
        $writer->append('SIMILAR');
        $writer->append('TO');
        $this->aExpr2->write($writer);
        $writer->append('ESCAPE');
        $this->aExpr3->write($writer);
    }
}
