<?php

declare(strict_types=1);

namespace Tests\Unit\Platform\PostgreSql\Schema;

use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\Attributes\UsesClass;
use PHPUnit\Framework\TestCase;
use SqlFixture\Analysis\CreateTableOperation;
use SqlFixture\Analysis\NumericLiteral;
use SqlFixture\Platform\PostgreSql\Schema\CatalogColumn;
use SqlFixture\Platform\PostgreSql\Schema\ColumnConstraints;
use SqlFixture\Platform\PostgreSql\Schema\ColumnParser as Subject;
use SqlFixture\Platform\PostgreSql\Schema\DefaultExpression;
use SqlFixture\Platform\PostgreSql\Schema\TypeDeclaration;
use SqlFixture\Schema\ColumnDefinition;
use SqlFixture\Schema\TypeShape;
use Tests\Statement\PostgreSqlStatements;

#[CoversClass(Subject::class)]
#[UsesClass(\SqlFixture\Platform\PostgreSql\Schema\TableDefinition::class)]
#[UsesClass(CreateTableOperation::class)]
#[UsesClass(ColumnDefinition::class)]
#[UsesClass(TypeShape::class)]
#[UsesClass(NumericLiteral::class)]
#[UsesClass(CatalogColumn::class)]
#[UsesClass(ColumnConstraints::class)]
#[UsesClass(DefaultExpression::class)]
#[UsesClass(TypeDeclaration::class)]
final class ColumnParserTest extends TestCase
{
    public function testParseReadsTypeConstraintsAndDefault(): void
    {
        $column = PostgreSqlStatements::parsedColumns("CREATE TABLE t (name VARCHAR(30) NOT NULL DEFAULT 'a''b' COLLATE \"C\")")['name'];

        self::assertSame('VARCHAR', $column->type);
        self::assertSame(30, $column->length);
        self::assertFalse($column->nullable);
        self::assertSame("a'b", $column->default);
        self::assertFalse($column->autoIncrement);
        self::assertFalse($column->generated);
        self::assertFalse($column->unsigned);
    }

    public function testParseMarksSequenceFedAndGeneratedColumns(): void
    {
        $columns = PostgreSqlStatements::parsedColumns('CREATE TABLE t (id SERIAL, seq INT GENERATED ALWAYS AS IDENTITY, b INT GENERATED BY DEFAULT AS IDENTITY, g INT GENERATED ALWAYS AS (id + 1) STORED, k INT, n INT)', ['k']);

        self::assertSame(['INTEGER', true, false], [$columns['id']->type, $columns['id']->autoIncrement, $columns['id']->nullable]);
        self::assertSame([true, false], [$columns['seq']->autoIncrement, $columns['seq']->nullable]);
        self::assertTrue($columns['b']->autoIncrement);
        self::assertSame([false, true, true], [$columns['g']->autoIncrement, $columns['g']->generated, $columns['g']->nullable]);
        self::assertFalse($columns['k']->nullable);
        self::assertTrue($columns['n']->nullable);
    }

    public function testParseLeavesAComputedDefaultWithoutAValue(): void
    {
        $columns = PostgreSqlStatements::parsedColumns("CREATE TABLE t (a TIMESTAMPTZ DEFAULT now(), b TEXT DEFAULT 'a' || 'b', c JSONB DEFAULT '{}'::jsonb)");

        self::assertNull($columns['a']->default);
        self::assertNull($columns['b']->default);
        self::assertSame('{}', $columns['c']->default);
    }
}
