<?php

declare(strict_types=1);

namespace Tests\Unit\Statement\Table\Alter\Column;

use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\Attributes\Medium;
use PHPUnit\Framework\TestCase;

#[CoversClass(\SqlSemantics\Platform\PostgreSql\Statement\Table\Alter\Column\AddIdentity::class)]
#[Medium]
final class AddIdentityTest extends TestCase
{
    public function testDeriveClauseChecksTheColumn(): void
    {
        $semantics = new \SqlSemantics\Facade\Semantics(\SqlSemantics\Platform\PostgreSql\Dialect::PostgreSql);
        $context = [];
        array_push($context, ...$semantics->analyze('CREATE TABLE t (a int NOT NULL, b int, c text)')->declarations());
        $statement = $semantics->analyze('ALTER TABLE t ALTER zz ADD GENERATED ALWAYS AS IDENTITY', $context);
        self::assertSame([
          0 => 'column "zz" does not exist',
        ], array_map(static fn ($problem): string => $problem->message(), $statement->facts->diagnostics));
    }

    public function testRenderWritesTheClauseAsWritten(): void
    {
        $semantics = new \SqlSemantics\Facade\Semantics(\SqlSemantics\Platform\PostgreSql\Dialect::PostgreSql);
        $statement = $semantics->analyze('ALTER TABLE t ALTER a ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 1 CACHE 5)', []);
        self::assertSame('ALTER TABLE t ALTER a ADD GENERATED BY DEFAULT AS IDENTITY (START 1 CACHE 5)', $statement->toString());
    }

    public function testDeriveClauseChecksTheTypeOfTheColumn(): void
    {
        $semantics = new \SqlSemantics\Facade\Semantics(\SqlSemantics\Platform\PostgreSql\Dialect::PostgreSql);
        $context = $semantics->analyze('CREATE TABLE t (a int NOT NULL, c text NOT NULL)', [])->declarations();
        $statement = $semantics->analyze('ALTER TABLE t ALTER c ADD GENERATED ALWAYS AS IDENTITY, ALTER a ADD GENERATED ALWAYS AS IDENTITY', $context);
        self::assertSame(['identity column type must be smallint, integer, or bigint'], array_map(static fn ($problem): string => $problem->message(), $statement->facts->diagnostics));
    }
}
