<?php

declare(strict_types=1);

namespace Tests\Integration\PostgreSql;

use PDO;
use PDOException;
use PHPUnit\Framework\Attributes\CoversNothing;
use PHPUnit\Framework\Attributes\Large;
use PHPUnit\Framework\TestCase;
use Tests\Fixtures\PostgreSqlContainer;
use ZtdQuery\Adapter\Pdo\ZtdPdo;

/**
 * @requires extension pdo_pgsql
 * @group integration
 * @group postgres
 */
#[CoversNothing]
#[Large]
final class DomainTypeTest extends TestCase
{
    public function testDomainConstraintsAndDmlRemainNativeInTheShadowStore(): void
    {
        [$schemaName, $rawPdo] = PostgreSqlContainer::createTestSchema();
        $suffix = bin2hex(random_bytes(8));
        $positiveDomain = 'positive_int_' . $suffix;
        $percentageDomain = 'percentage_' . $suffix;
        $table = 'contacts_' . $suffix;

        try {
            $rawPdo->exec("CREATE DOMAIN {$positiveDomain} AS INTEGER CHECK (VALUE > 0)");
            $rawPdo->exec(
                "CREATE DOMAIN {$percentageDomain} AS NUMERIC(5,2) CHECK (VALUE >= 0 AND VALUE <= 100)",
            );
            $rawPdo->exec(
                "CREATE TABLE {$table} (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                . "age {$positiveDomain} NOT NULL, satisfaction {$percentageDomain} NOT NULL)",
            );
            $ztdPdo = ZtdPdo::fromPdo($rawPdo);

            $insert = $ztdPdo->prepare(
                "INSERT INTO {$table} (age, satisfaction) VALUES (\$1, \$2) RETURNING id, age, satisfaction",
            );
            self::assertInstanceOf(\PDOStatement::class, $insert);
            self::assertTrue($insert->execute([30, '85.50']));
            self::assertSame(
                ['id' => 1, 'age' => 30, 'satisfaction' => '85.50'],
                $insert->fetch(PDO::FETCH_ASSOC),
            );

            self::assertSame(1, $ztdPdo->exec("UPDATE {$table} SET satisfaction = 99.99 WHERE id = 1"));
            $updated = $ztdPdo->query("SELECT satisfaction::text FROM {$table} WHERE id = 1");
            self::assertNotFalse($updated);
            self::assertSame('99.99', $updated->fetchColumn());

            self::assertSame(1, $ztdPdo->exec("DELETE FROM {$table} WHERE satisfaction > 90"));
            $remaining = $ztdPdo->query("SELECT COUNT(*) FROM {$table}");
            self::assertNotFalse($remaining);
            self::assertSame(0, (int) $remaining->fetchColumn());

            try {
                $ztdPdo->exec("INSERT INTO {$table} (age, satisfaction) VALUES (-5, 101)");
                self::fail('The domain CHECK constraint must reject invalid shadow data.');
            } catch (PDOException $exception) {
                self::assertStringContainsString('violates check constraint', $exception->getMessage());
            }

            $physical = $rawPdo->query("SELECT COUNT(*) FROM {$table}");
            self::assertNotFalse($physical);
            self::assertSame(0, (int) $physical->fetchColumn());
        } finally {
            $rawPdo->exec(sprintf('DROP SCHEMA IF EXISTS "%s" CASCADE', $schemaName));
        }
    }
}
