<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\PostgreSql\Role;

/**
 * The function_with_argtypes_list SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\PostgreSql\Role\FunctionWithArgtypesListForm $value): string => (new \SqlSemantics\Statement\Statement($value))->toString();
 *     $write instanceof \Closure // => true
 */
interface FunctionWithArgtypesListForm extends \SqlSemantics\Statement\Element
{
}
