<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\PostgreSql\Role;

/**
 * The insert_column_item SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\PostgreSql\Role\InsertColumnItemForm $value): string => (new \SqlSemantics\Statement\Statement($value))->toString();
 *     $write instanceof \Closure // => true
 */
interface InsertColumnItemForm extends \SqlSemantics\Statement\Element
{
}
