<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\PostgreSql\Role;

/**
 * The operator_with_argtypes SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\PostgreSql\Role\OperatorWithArgtypesForm $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
interface OperatorWithArgtypesForm extends \SqlSemantics\Statement\Element
{
}
