<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The add_part_extra SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\AddPartExtraWithPartitionsSymRealUlongNum_d67a0f5e $value): string => (new \SqlSemantics\Statement\Statement($value))->toString();
 *     $write instanceof \Closure // => true
 */
final class AddPartExtraWithPartitionsSymRealUlongNum_d67a0f5e implements \SqlSemantics\Statement\Model\MySql\Role\AddPartExtraForm
{
    /**
     * Supplies the SQL values of this form.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\MySql\Role\RealUlongNumForm $realUlongNum,
    ) {
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->append('PARTITIONS');
        $this->realUlongNum->write($writer);
    }
}
