<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The alter_user_command SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\AlterUserCommandWithAlterUserIfExists_3276589d $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class AlterUserCommandWithAlterUserIfExists_3276589d implements \SqlSemantics\Statement\Model\MySql\Role\AlterUserCommandForm
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form.
     */
    public function __construct(
        public readonly string $user,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\IfExistsForm $ifExists,
    ) {
        $this->assertMatchesPattern($user, \SqlSemantics\Statement\Model\MySql\Contract\Contracts::SPELLINGS['USER'], 'The user must be a complete USER lexical spelling.');
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($ifExists), 'The ifExists must be a generated immutable SQL value.');
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->append('ALTER');
        $writer->append($this->user);
        $this->ifExists->write($writer);
    }

    /**
     * Returns a copy with a new user, preserving every other field.
     */
    public function withUser(string $user): self
    {
        return new self($user, $this->ifExists);
    }

    /**
     * Returns a copy with a new ifExists, preserving every other field.
     */
    public function withIfExists(\SqlSemantics\Statement\Model\MySql\Role\IfExistsForm $ifExists): self
    {
        return new self($this->user, $ifExists);
    }
}
