<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The alter_command_list SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\AlterCommandListWithAlterCommandsModifierListAlterList_9da0d417 $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class AlterCommandListWithAlterCommandsModifierListAlterList_9da0d417 implements \SqlSemantics\Statement\Model\MySql\Role\AlterCommandListForm, \SqlSemantics\Statement\Model\MySql\Role\AlterCommandsForm
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form; comments are kept by the position of the symbol each precedes.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\MySql\Role\AlterCommandsModifierListForm $alterCommandsModifierList,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\AlterListForm $alterList,
        public readonly \SqlSemantics\Statement\Comments $comments = new \SqlSemantics\Statement\Comments(),
    ) {
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($alterCommandsModifierList), 'The alterCommandsModifierList must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($alterList), 'The alterList must be a generated immutable SQL value.');
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->comments($this->comments, 0);
        $this->alterCommandsModifierList->write($writer);
        $writer->comments($this->comments, 1);
        $writer->append(',');
        $writer->comments($this->comments, 2);
        $this->alterList->write($writer);
    }

    /**
     * Lists the values of this form, in writing order.
     *
     * @return list<\SqlSemantics\Statement\Element>
     */
    public function children(): array
    {
        return [$this->alterCommandsModifierList, $this->alterList];
    }

    /**
     * Returns this value rebuilt around what the function answers for each value, keeping lexical fields and comments; itself when every answer is the value it was given.
     *
     * @param callable(\SqlSemantics\Statement\Element): \SqlSemantics\Statement\Element $replace
     */
    public function map(callable $replace): static
    {
        $mapped = [$this->replacement($this->alterCommandsModifierList, \SqlSemantics\Statement\Model\MySql\Role\AlterCommandsModifierListForm::class, $replace), $this->replacement($this->alterList, \SqlSemantics\Statement\Model\MySql\Role\AlterListForm::class, $replace)];

        return $mapped === [$this->alterCommandsModifierList, $this->alterList] ? $this : new self($mapped[0], $mapped[1], $this->comments);
    }

    /**
     * Returns a copy with a new alterCommandsModifierList, preserving every other field.
     */
    public function withAlterCommandsModifierList(\SqlSemantics\Statement\Model\MySql\Role\AlterCommandsModifierListForm $alterCommandsModifierList): self
    {
        return new self($alterCommandsModifierList, $this->alterList, $this->comments);
    }

    /**
     * Returns a copy with a new alterList, preserving every other field.
     */
    public function withAlterList(\SqlSemantics\Statement\Model\MySql\Role\AlterListForm $alterList): self
    {
        return new self($this->alterCommandsModifierList, $alterList, $this->comments);
    }

    /**
     * Returns a copy with a new comments, preserving every other field.
     */
    public function withComments(\SqlSemantics\Statement\Comments $comments): self
    {
        return new self($this->alterCommandsModifierList, $this->alterList, $comments);
    }
}
