<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The alter_table_stmt SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\AlterTableStmtWithAlterTableSymTableIdentStandaloneAlterTableAction_cdacb9cb $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class AlterTableStmtWithAlterTableSymTableIdentStandaloneAlterTableAction_cdacb9cb implements \SqlSemantics\Statement\Model\MySql\Role\AlterTableStmtForm, \SqlSemantics\Statement\Model\MySql\Role\EvSqlStmtForm, \SqlSemantics\Statement\Model\MySql\Role\EvSqlStmtInnerForm, \SqlSemantics\Statement\Model\MySql\Role\SimpleStatementForm, \SqlSemantics\Statement\Model\MySql\Role\SimpleStatementOrBeginForm, \SqlSemantics\Statement\Model\MySql\Role\SpProcStmtForm, \SqlSemantics\Statement\Model\MySql\Role\SpProcStmtStatementForm, \SqlSemantics\Statement\Model\MySql\Role\StoredRoutineBodyForm, \SqlSemantics\Statement\Command
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\MySql\Role\TableIdentForm $tableIdent,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\StandaloneAlterTableActionForm $standaloneAlterTableAction,
    ) {
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($tableIdent), 'The tableIdent must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($standaloneAlterTableAction), 'The standaloneAlterTableAction must be a generated immutable SQL value.');
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->append('ALTER');
        $writer->append('TABLE');
        $this->tableIdent->write($writer);
        $this->standaloneAlterTableAction->write($writer);
    }

    /**
     * Returns a copy with a new tableIdent, preserving every other field.
     */
    public function withTableIdent(\SqlSemantics\Statement\Model\MySql\Role\TableIdentForm $tableIdent): self
    {
        return new self($tableIdent, $this->standaloneAlterTableAction);
    }

    /**
     * Returns a copy with a new standaloneAlterTableAction, preserving every other field.
     */
    public function withStandaloneAlterTableAction(\SqlSemantics\Statement\Model\MySql\Role\StandaloneAlterTableActionForm $standaloneAlterTableAction): self
    {
        return new self($this->tableIdent, $standaloneAlterTableAction);
    }
}
