<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The alter_user SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\AlterUserWithUserIdentifiedWithPluginByRandomPasswordOptRetainCurrentPassword_f4dfac91 $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class AlterUserWithUserIdentifiedWithPluginByRandomPasswordOptRetainCurrentPassword_f4dfac91 implements \SqlSemantics\Statement\Model\MySql\Role\AlterUserForm, \SqlSemantics\Statement\Model\MySql\Role\AlterUserListForm
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form; comments are kept by the position of the symbol each precedes.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\MySql\Role\UserForm $user,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\IdentifiedWithPluginByRandomPasswordForm $identifiedWithPluginByRandomPassword,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\OptRetainCurrentPasswordForm $optRetainCurrentPassword,
        public readonly \SqlSemantics\Statement\Comments $comments = new \SqlSemantics\Statement\Comments(),
    ) {
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($user), 'The user must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($identifiedWithPluginByRandomPassword), 'The identifiedWithPluginByRandomPassword must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($optRetainCurrentPassword), 'The optRetainCurrentPassword must be a generated immutable SQL value.');
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->comments($this->comments, 0);
        $this->user->write($writer);
        $writer->comments($this->comments, 1);
        $this->identifiedWithPluginByRandomPassword->write($writer);
        $writer->comments($this->comments, 2);
        $this->optRetainCurrentPassword->write($writer);
    }

    /**
     * Returns a copy with a new user, preserving every other field.
     */
    public function withUser(\SqlSemantics\Statement\Model\MySql\Role\UserForm $user): self
    {
        return new self($user, $this->identifiedWithPluginByRandomPassword, $this->optRetainCurrentPassword, $this->comments);
    }

    /**
     * Returns a copy with a new identifiedWithPluginByRandomPassword, preserving every other field.
     */
    public function withIdentifiedWithPluginByRandomPassword(\SqlSemantics\Statement\Model\MySql\Role\IdentifiedWithPluginByRandomPasswordForm $identifiedWithPluginByRandomPassword): self
    {
        return new self($this->user, $identifiedWithPluginByRandomPassword, $this->optRetainCurrentPassword, $this->comments);
    }

    /**
     * Returns a copy with a new optRetainCurrentPassword, preserving every other field.
     */
    public function withOptRetainCurrentPassword(\SqlSemantics\Statement\Model\MySql\Role\OptRetainCurrentPasswordForm $optRetainCurrentPassword): self
    {
        return new self($this->user, $this->identifiedWithPluginByRandomPassword, $optRetainCurrentPassword, $this->comments);
    }

    /**
     * Returns a copy with a new comments, preserving every other field.
     */
    public function withComments(\SqlSemantics\Statement\Comments $comments): self
    {
        return new self($this->user, $this->identifiedWithPluginByRandomPassword, $this->optRetainCurrentPassword, $comments);
    }
}
