<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The alter_list_item SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\AlterListItemWithAlterOptColumnFieldIdentSetDefaultSignedLiteral_ce605117 $value): string => (new \SqlSemantics\Statement\Statement($value))->toString();
 *     $write instanceof \Closure // => true
 */
final class AlterListItemWithAlterOptColumnFieldIdentSetDefaultSignedLiteral_ce605117 implements \SqlSemantics\Statement\Model\MySql\Role\AlterCommandListForm, \SqlSemantics\Statement\Model\MySql\Role\AlterCommandsForm, \SqlSemantics\Statement\Model\MySql\Role\AlterListForm, \SqlSemantics\Statement\Model\MySql\Role\AlterListItemForm, \SqlSemantics\Statement\Model\MySql\Role\OptAlterCommandListForm, \SqlSemantics\Statement\Model\MySql\Role\OptAlterTableActionsForm
{
    /**
     * Supplies the SQL values of this form.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\MySql\Role\OptColumnForm $optColumn,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\FieldIdentForm $fieldIdent,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\SignedLiteralForm $signedLiteral,
    ) {
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->append('ALTER');
        $this->optColumn->write($writer);
        $this->fieldIdent->write($writer);
        $writer->append('SET');
        $writer->append('DEFAULT');
        $this->signedLiteral->write($writer);
    }
}
