<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The analyze_table_stmt SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\AnalyzeTableStmtWithAnalyzeSymOptNoWriteToBinlogTableOrTablesTableListOptHistogram_7ee2bab4 $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class AnalyzeTableStmtWithAnalyzeSymOptNoWriteToBinlogTableOrTablesTableListOptHistogram_7ee2bab4 implements \SqlSemantics\Statement\Model\MySql\Role\AnalyzeTableStmtForm, \SqlSemantics\Statement\Model\MySql\Role\EvSqlStmtForm, \SqlSemantics\Statement\Model\MySql\Role\EvSqlStmtInnerForm, \SqlSemantics\Statement\Model\MySql\Role\SimpleStatementForm, \SqlSemantics\Statement\Model\MySql\Role\SimpleStatementOrBeginForm, \SqlSemantics\Statement\Model\MySql\Role\SpProcStmtForm, \SqlSemantics\Statement\Model\MySql\Role\SpProcStmtStatementForm, \SqlSemantics\Statement\Model\MySql\Role\StoredRoutineBodyForm, \SqlSemantics\Statement\Command
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\MySql\Role\OptNoWriteToBinlogForm $optNoWriteToBinlog,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\TableOrTablesForm $tableOrTables,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\TableListForm $tableList,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\OptHistogramForm $optHistogram,
    ) {
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($optNoWriteToBinlog), 'The optNoWriteToBinlog must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($tableOrTables), 'The tableOrTables must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($tableList), 'The tableList must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($optHistogram), 'The optHistogram must be a generated immutable SQL value.');
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->append('ANALYZE');
        $this->optNoWriteToBinlog->write($writer);
        $this->tableOrTables->write($writer);
        $this->tableList->write($writer);
        $this->optHistogram->write($writer);
    }

    /**
     * Returns a copy with a new optNoWriteToBinlog, preserving every other field.
     */
    public function withOptNoWriteToBinlog(\SqlSemantics\Statement\Model\MySql\Role\OptNoWriteToBinlogForm $optNoWriteToBinlog): self
    {
        return new self($optNoWriteToBinlog, $this->tableOrTables, $this->tableList, $this->optHistogram);
    }

    /**
     * Returns a copy with a new tableOrTables, preserving every other field.
     */
    public function withTableOrTables(\SqlSemantics\Statement\Model\MySql\Role\TableOrTablesForm $tableOrTables): self
    {
        return new self($this->optNoWriteToBinlog, $tableOrTables, $this->tableList, $this->optHistogram);
    }

    /**
     * Returns a copy with a new tableList, preserving every other field.
     */
    public function withTableList(\SqlSemantics\Statement\Model\MySql\Role\TableListForm $tableList): self
    {
        return new self($this->optNoWriteToBinlog, $this->tableOrTables, $tableList, $this->optHistogram);
    }

    /**
     * Returns a copy with a new optHistogram, preserving every other field.
     */
    public function withOptHistogram(\SqlSemantics\Statement\Model\MySql\Role\OptHistogramForm $optHistogram): self
    {
        return new self($this->optNoWriteToBinlog, $this->tableOrTables, $this->tableList, $optHistogram);
    }
}
