<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The assign_gtids_to_anonymous_transactions_def SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\AssignGtidsToAnonymousTransactionsDefWithLocalSym_ea6949be $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class AssignGtidsToAnonymousTransactionsDefWithLocalSym_ea6949be implements \SqlSemantics\Statement\Model\MySql\Role\AssignGtidsToAnonymousTransactionsDefForm
{
    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->append('LOCAL');
    }
}
