<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The cast_type SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\CastTypeWithDecimalSymFloatOptions_7b45e7c9 $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class CastTypeWithDecimalSymFloatOptions_7b45e7c9 implements \SqlSemantics\Statement\Model\MySql\Role\CastTypeForm
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form; comments are kept by the position of the symbol each precedes.
     */
    public function __construct(
        public readonly string $decimalSym,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\FloatOptionsForm $floatOptions,
        public readonly \SqlSemantics\Statement\Comments $comments = new \SqlSemantics\Statement\Comments(),
    ) {
        $this->assertMatchesPattern($decimalSym, \SqlSemantics\Statement\Model\MySql\Contract\Contracts::SPELLINGS['DECIMAL_SYM'], 'The decimalSym must be a complete DECIMAL_SYM lexical spelling.');
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($floatOptions), 'The floatOptions must be a generated immutable SQL value.');
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->comments($this->comments, 0);
        $writer->append($this->decimalSym);
        $writer->comments($this->comments, 1);
        $this->floatOptions->write($writer);
    }

    /**
     * Returns a copy with a new decimalSym, preserving every other field.
     */
    public function withDecimalSym(string $decimalSym): self
    {
        return new self($decimalSym, $this->floatOptions, $this->comments);
    }

    /**
     * Returns a copy with a new floatOptions, preserving every other field.
     */
    public function withFloatOptions(\SqlSemantics\Statement\Model\MySql\Role\FloatOptionsForm $floatOptions): self
    {
        return new self($this->decimalSym, $floatOptions, $this->comments);
    }

    /**
     * Returns a copy with a new comments, preserving every other field.
     */
    public function withComments(\SqlSemantics\Statement\Comments $comments): self
    {
        return new self($this->decimalSym, $this->floatOptions, $comments);
    }
}
