<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The common_table_expr SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\CommonTableExprWithIdentOptDerivedColumnListAsTableSubquery_42edd512 $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class CommonTableExprWithIdentOptDerivedColumnListAsTableSubquery_42edd512 implements \SqlSemantics\Statement\Model\MySql\Role\CommonTableExprForm, \SqlSemantics\Statement\Model\MySql\Role\WithListForm
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form; comments are kept by the position of the symbol each precedes.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\MySql\Role\IdentForm $ident,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\OptDerivedColumnListForm $optDerivedColumnList,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\TableSubqueryForm $tableSubquery,
        public readonly \SqlSemantics\Statement\Comments $comments = new \SqlSemantics\Statement\Comments(),
    ) {
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($ident), 'The ident must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($optDerivedColumnList), 'The optDerivedColumnList must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($tableSubquery), 'The tableSubquery must be a generated immutable SQL value.');
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->comments($this->comments, 0);
        $this->ident->write($writer);
        $writer->comments($this->comments, 1);
        $this->optDerivedColumnList->write($writer);
        $writer->comments($this->comments, 2);
        $writer->append('AS');
        $writer->comments($this->comments, 3);
        $this->tableSubquery->write($writer);
    }

    /**
     * Returns a copy with a new ident, preserving every other field.
     */
    public function withIdent(\SqlSemantics\Statement\Model\MySql\Role\IdentForm $ident): self
    {
        return new self($ident, $this->optDerivedColumnList, $this->tableSubquery, $this->comments);
    }

    /**
     * Returns a copy with a new optDerivedColumnList, preserving every other field.
     */
    public function withOptDerivedColumnList(\SqlSemantics\Statement\Model\MySql\Role\OptDerivedColumnListForm $optDerivedColumnList): self
    {
        return new self($this->ident, $optDerivedColumnList, $this->tableSubquery, $this->comments);
    }

    /**
     * Returns a copy with a new tableSubquery, preserving every other field.
     */
    public function withTableSubquery(\SqlSemantics\Statement\Model\MySql\Role\TableSubqueryForm $tableSubquery): self
    {
        return new self($this->ident, $this->optDerivedColumnList, $tableSubquery, $this->comments);
    }

    /**
     * Returns a copy with a new comments, preserving every other field.
     */
    public function withComments(\SqlSemantics\Statement\Comments $comments): self
    {
        return new self($this->ident, $this->optDerivedColumnList, $this->tableSubquery, $comments);
    }
}
