<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The create_table_options SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\CreateTableOptionsWithCreateTableOptionsOptCommaCreateTableOption_1a46c03c $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class CreateTableOptionsWithCreateTableOptionsOptCommaCreateTableOption_1a46c03c implements \SqlSemantics\Statement\Model\MySql\Role\CreateTableOptionsForm, \SqlSemantics\Statement\Model\MySql\Role\OptCreateTableOptionsForm
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form; comments are kept by the position of the symbol each precedes.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\MySql\Role\CreateTableOptionsForm $createTableOptions,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\OptCommaForm $optComma,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\CreateTableOptionForm $createTableOption,
        public readonly \SqlSemantics\Statement\Comments $comments = new \SqlSemantics\Statement\Comments(),
    ) {
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($createTableOptions), 'The createTableOptions must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($optComma), 'The optComma must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($createTableOption), 'The createTableOption must be a generated immutable SQL value.');
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->comments($this->comments, 0);
        $this->createTableOptions->write($writer);
        $writer->comments($this->comments, 1);
        $this->optComma->write($writer);
        $writer->comments($this->comments, 2);
        $this->createTableOption->write($writer);
    }

    /**
     * Returns a copy with a new createTableOptions, preserving every other field.
     */
    public function withCreateTableOptions(\SqlSemantics\Statement\Model\MySql\Role\CreateTableOptionsForm $createTableOptions): self
    {
        return new self($createTableOptions, $this->optComma, $this->createTableOption, $this->comments);
    }

    /**
     * Returns a copy with a new optComma, preserving every other field.
     */
    public function withOptComma(\SqlSemantics\Statement\Model\MySql\Role\OptCommaForm $optComma): self
    {
        return new self($this->createTableOptions, $optComma, $this->createTableOption, $this->comments);
    }

    /**
     * Returns a copy with a new createTableOption, preserving every other field.
     */
    public function withCreateTableOption(\SqlSemantics\Statement\Model\MySql\Role\CreateTableOptionForm $createTableOption): self
    {
        return new self($this->createTableOptions, $this->optComma, $createTableOption, $this->comments);
    }

    /**
     * Returns a copy with a new comments, preserving every other field.
     */
    public function withComments(\SqlSemantics\Statement\Comments $comments): self
    {
        return new self($this->createTableOptions, $this->optComma, $this->createTableOption, $comments);
    }
}
