<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The diagnostics_information SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\DiagnosticsInformationWithConditionSymConditionNumberConditionInformation_7f76f4ff $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class DiagnosticsInformationWithConditionSymConditionNumberConditionInformation_7f76f4ff implements \SqlSemantics\Statement\Model\MySql\Role\DiagnosticsInformationForm
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form; comments are kept by the position of the symbol each precedes.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\MySql\Role\ConditionNumberForm $conditionNumber,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\ConditionInformationForm $conditionInformation,
        public readonly \SqlSemantics\Statement\Comments $comments = new \SqlSemantics\Statement\Comments(),
    ) {
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($conditionNumber), 'The conditionNumber must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($conditionInformation), 'The conditionInformation must be a generated immutable SQL value.');
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->comments($this->comments, 0);
        $writer->append('CONDITION');
        $writer->comments($this->comments, 1);
        $this->conditionNumber->write($writer);
        $writer->comments($this->comments, 2);
        $this->conditionInformation->write($writer);
    }

    /**
     * Returns a copy with a new conditionNumber, preserving every other field.
     */
    public function withConditionNumber(\SqlSemantics\Statement\Model\MySql\Role\ConditionNumberForm $conditionNumber): self
    {
        return new self($conditionNumber, $this->conditionInformation, $this->comments);
    }

    /**
     * Returns a copy with a new conditionInformation, preserving every other field.
     */
    public function withConditionInformation(\SqlSemantics\Statement\Model\MySql\Role\ConditionInformationForm $conditionInformation): self
    {
        return new self($this->conditionNumber, $conditionInformation, $this->comments);
    }

    /**
     * Returns a copy with a new comments, preserving every other field.
     */
    public function withComments(\SqlSemantics\Statement\Comments $comments): self
    {
        return new self($this->conditionNumber, $this->conditionInformation, $comments);
    }
}
