<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The explainable_stmt SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\ExplainableStmtWithOptExplainForSchemaInsertStmt_ae7c1ac8 $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class ExplainableStmtWithOptExplainForSchemaInsertStmt_ae7c1ac8 implements \SqlSemantics\Statement\Model\MySql\Role\ExplainableStmtForm
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form; comments are kept by the position of the symbol each precedes.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\MySql\Role\OptExplainForSchemaForm $optExplainForSchema,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\InsertStmtForm $insertStmt,
        public readonly \SqlSemantics\Statement\Comments $comments = new \SqlSemantics\Statement\Comments(),
    ) {
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($optExplainForSchema), 'The optExplainForSchema must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($insertStmt), 'The insertStmt must be a generated immutable SQL value.');
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->comments($this->comments, 0);
        $this->optExplainForSchema->write($writer);
        $writer->comments($this->comments, 1);
        $this->insertStmt->write($writer);
    }

    /**
     * Lists the values of this form, in writing order.
     *
     * @return list<\SqlSemantics\Statement\Element>
     */
    public function children(): array
    {
        return [$this->optExplainForSchema, $this->insertStmt];
    }

    /**
     * Returns this value rebuilt around what the function answers for each value, keeping lexical fields and comments; itself when every answer is the value it was given.
     *
     * @param callable(\SqlSemantics\Statement\Element): \SqlSemantics\Statement\Element $replace
     */
    public function map(callable $replace): static
    {
        $mapped = [$this->replacement($this->optExplainForSchema, \SqlSemantics\Statement\Model\MySql\Role\OptExplainForSchemaForm::class, $replace), $this->replacement($this->insertStmt, \SqlSemantics\Statement\Model\MySql\Role\InsertStmtForm::class, $replace)];

        return $mapped === [$this->optExplainForSchema, $this->insertStmt] ? $this : new self($mapped[0], $mapped[1], $this->comments);
    }

    /**
     * Returns a copy with a new optExplainForSchema, preserving every other field.
     */
    public function withOptExplainForSchema(\SqlSemantics\Statement\Model\MySql\Role\OptExplainForSchemaForm $optExplainForSchema): self
    {
        return new self($optExplainForSchema, $this->insertStmt, $this->comments);
    }

    /**
     * Returns a copy with a new insertStmt, preserving every other field.
     */
    public function withInsertStmt(\SqlSemantics\Statement\Model\MySql\Role\InsertStmtForm $insertStmt): self
    {
        return new self($this->optExplainForSchema, $insertStmt, $this->comments);
    }

    /**
     * Returns a copy with a new comments, preserving every other field.
     */
    public function withComments(\SqlSemantics\Statement\Comments $comments): self
    {
        return new self($this->optExplainForSchema, $this->insertStmt, $comments);
    }
}
