<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The fields SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\FieldsWithFieldsInsertIdent_655406b3 $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class FieldsWithFieldsInsertIdent_655406b3 implements \SqlSemantics\Statement\Model\MySql\Role\FieldsForm
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form; comments are kept by the position of the symbol each precedes.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\MySql\Role\FieldsForm $fields,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\InsertIdentForm $insertIdent,
        public readonly \SqlSemantics\Statement\Comments $comments = new \SqlSemantics\Statement\Comments(),
    ) {
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($fields), 'The fields must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($insertIdent), 'The insertIdent must be a generated immutable SQL value.');
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->comments($this->comments, 0);
        $this->fields->write($writer);
        $writer->comments($this->comments, 1);
        $writer->append(',');
        $writer->comments($this->comments, 2);
        $this->insertIdent->write($writer);
    }

    /**
     * Returns a copy with a new fields, preserving every other field.
     */
    public function withFields(\SqlSemantics\Statement\Model\MySql\Role\FieldsForm $fields): self
    {
        return new self($fields, $this->insertIdent, $this->comments);
    }

    /**
     * Returns a copy with a new insertIdent, preserving every other field.
     */
    public function withInsertIdent(\SqlSemantics\Statement\Model\MySql\Role\InsertIdentForm $insertIdent): self
    {
        return new self($this->fields, $insertIdent, $this->comments);
    }

    /**
     * Returns a copy with a new comments, preserving every other field.
     */
    public function withComments(\SqlSemantics\Statement\Comments $comments): self
    {
        return new self($this->fields, $this->insertIdent, $comments);
    }
}
