<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The field_length SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\FieldLengthWithUlonglongNum_d7d79f00 $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class FieldLengthWithUlonglongNum_d7d79f00 implements \SqlSemantics\Statement\Model\MySql\Role\FieldLengthForm, \SqlSemantics\Statement\Model\MySql\Role\FloatOptionsForm, \SqlSemantics\Statement\Model\MySql\Role\OptFieldLengthForm, \SqlSemantics\Statement\Model\MySql\Role\StandardFloatOptionsForm
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form; comments are kept by the position of the symbol each precedes.
     */
    public function __construct(
        public readonly string $ulonglongNum,
        public readonly \SqlSemantics\Statement\Comments $comments = new \SqlSemantics\Statement\Comments(),
    ) {
        $this->assertMatchesPattern($ulonglongNum, \SqlSemantics\Statement\Model\MySql\Contract\Contracts::SPELLINGS['ULONGLONG_NUM'], 'The ulonglongNum must be a complete ULONGLONG_NUM lexical spelling.');
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->comments($this->comments, 0);
        $writer->append('(');
        $writer->comments($this->comments, 1);
        $writer->append($this->ulonglongNum);
        $writer->comments($this->comments, 2);
        $writer->append(')');
    }

    /**
     * Returns a copy with a new ulonglongNum, preserving every other field.
     */
    public function withUlonglongNum(string $ulonglongNum): self
    {
        return new self($ulonglongNum, $this->comments);
    }

    /**
     * Returns a copy with a new comments, preserving every other field.
     */
    public function withComments(\SqlSemantics\Statement\Comments $comments): self
    {
        return new self($this->ulonglongNum, $comments);
    }
}
