<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The filter_table_ident SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\FilterTableIdentWithSchemaIdent_3f622d2c $value): string => (new \SqlSemantics\Statement\Statement($value))->toString();
 *     $write instanceof \Closure // => true
 */
final class FilterTableIdentWithSchemaIdent_3f622d2c implements \SqlSemantics\Statement\Model\MySql\Role\FilterTableIdentForm, \SqlSemantics\Statement\Model\MySql\Role\FilterTableListForm
{
    /**
     * Supplies the SQL values of this form.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\MySql\Role\SchemaForm $schema,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\IdentForm $ident,
    ) {
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $this->schema->write($writer);
        $writer->append('.');
        $this->ident->write($writer);
    }
}
