<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The fulltext_options SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\FulltextOptionsWithInSymBooleanSymModeSym_7ade1ced $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class FulltextOptionsWithInSymBooleanSymModeSym_7ade1ced implements \SqlSemantics\Statement\Model\MySql\Role\FulltextOptionsForm
{
    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->append('IN');
        $writer->append('BOOLEAN');
        $writer->append('MODE');
    }
}
