<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The grant_user SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\GrantUserWithUserIdentifiedSymByTextString_46e8e039 $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class GrantUserWithUserIdentifiedSymByTextString_46e8e039 implements \SqlSemantics\Statement\Model\MySql\Role\GrantListForm, \SqlSemantics\Statement\Model\MySql\Role\GrantUserForm
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\MySql\Role\UserForm $user,
        public readonly string $value,
    ) {
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($user), 'The user must be a generated immutable SQL value.');
        $this->assertMatchesPattern($value, \SqlSemantics\Statement\Model\MySql\Contract\Contracts::SPELLINGS['TEXT_STRING'], 'The value must be a complete TEXT_STRING lexical spelling.');
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $this->user->write($writer);
        $writer->append('IDENTIFIED');
        $writer->append('BY');
        $writer->append($this->value);
    }

    /**
     * Returns a copy with a new user, preserving every other field.
     */
    public function withUser(\SqlSemantics\Statement\Model\MySql\Role\UserForm $user): self
    {
        return new self($user, $this->value);
    }

    /**
     * Returns a copy with a new value, preserving every other field.
     */
    public function withValue(string $value): self
    {
        return new self($this->user, $value);
    }
}
