<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The group_list SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\GroupListWithGroupListGroupingExpr_98395124 $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class GroupListWithGroupListGroupingExpr_98395124 implements \SqlSemantics\Statement\Model\MySql\Role\GroupListForm
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form; comments are kept by the position of the symbol each precedes.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\MySql\Role\GroupListForm $groupList,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\GroupingExprForm $groupingExpr,
        public readonly \SqlSemantics\Statement\Comments $comments = new \SqlSemantics\Statement\Comments(),
    ) {
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($groupList), 'The groupList must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($groupingExpr), 'The groupingExpr must be a generated immutable SQL value.');
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->comments($this->comments, 0);
        $this->groupList->write($writer);
        $writer->comments($this->comments, 1);
        $writer->append(',');
        $writer->comments($this->comments, 2);
        $this->groupingExpr->write($writer);
    }

    /**
     * Returns a copy with a new groupList, preserving every other field.
     */
    public function withGroupList(\SqlSemantics\Statement\Model\MySql\Role\GroupListForm $groupList): self
    {
        return new self($groupList, $this->groupingExpr, $this->comments);
    }

    /**
     * Returns a copy with a new groupingExpr, preserving every other field.
     */
    public function withGroupingExpr(\SqlSemantics\Statement\Model\MySql\Role\GroupingExprForm $groupingExpr): self
    {
        return new self($this->groupList, $groupingExpr, $this->comments);
    }

    /**
     * Returns a copy with a new comments, preserving every other field.
     */
    public function withComments(\SqlSemantics\Statement\Comments $comments): self
    {
        return new self($this->groupList, $this->groupingExpr, $comments);
    }
}
