<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The insert_field_spec SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\InsertFieldSpecWithFieldsInsertValues_565b1b70 $value): string => (new \SqlSemantics\Statement\Statement($value))->toString();
 *     $write instanceof \Closure // => true
 */
final class InsertFieldSpecWithFieldsInsertValues_565b1b70 implements \SqlSemantics\Statement\Model\MySql\Role\InsertFieldSpecForm
{
    /**
     * Supplies the SQL values of this form.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\MySql\Role\FieldsForm $fields,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\InsertValuesForm $insertValues,
    ) {
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->append('(');
        $this->fields->write($writer);
        $writer->append(')');
        $this->insertValues->write($writer);
    }
}
