<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The key_def SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\KeyDefWithOptConstraintCheckConstraint_cc3cfb49 $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class KeyDefWithOptConstraintCheckConstraint_cc3cfb49 implements \SqlSemantics\Statement\Model\MySql\Role\CreateFieldListForm, \SqlSemantics\Statement\Model\MySql\Role\FieldListForm, \SqlSemantics\Statement\Model\MySql\Role\FieldListItemForm, \SqlSemantics\Statement\Model\MySql\Role\KeyDefForm
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form; comments are kept by the position of the symbol each precedes.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\MySql\Role\OptConstraintForm $optConstraint,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\CheckConstraintForm $checkConstraint,
        public readonly \SqlSemantics\Statement\Comments $comments = new \SqlSemantics\Statement\Comments(),
    ) {
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($optConstraint), 'The optConstraint must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($checkConstraint), 'The checkConstraint must be a generated immutable SQL value.');
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->comments($this->comments, 0);
        $this->optConstraint->write($writer);
        $writer->comments($this->comments, 1);
        $this->checkConstraint->write($writer);
    }

    /**
     * Returns a copy with a new optConstraint, preserving every other field.
     */
    public function withOptConstraint(\SqlSemantics\Statement\Model\MySql\Role\OptConstraintForm $optConstraint): self
    {
        return new self($optConstraint, $this->checkConstraint, $this->comments);
    }

    /**
     * Returns a copy with a new checkConstraint, preserving every other field.
     */
    public function withCheckConstraint(\SqlSemantics\Statement\Model\MySql\Role\CheckConstraintForm $checkConstraint): self
    {
        return new self($this->optConstraint, $checkConstraint, $this->comments);
    }

    /**
     * Returns a copy with a new comments, preserving every other field.
     */
    public function withComments(\SqlSemantics\Statement\Comments $comments): self
    {
        return new self($this->optConstraint, $this->checkConstraint, $comments);
    }
}
