<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The key_def SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\KeyDefWithSpatialOptKeyOrIndexOptIdentInitKeyOptionsKeyListSpatialKeyOptions_1d3d0c25 $value): string => (new \SqlSemantics\Statement\Statement($value))->toString();
 *     $write instanceof \Closure // => true
 */
final class KeyDefWithSpatialOptKeyOrIndexOptIdentInitKeyOptionsKeyListSpatialKeyOptions_1d3d0c25 implements \SqlSemantics\Statement\Model\MySql\Role\CreateFieldListForm, \SqlSemantics\Statement\Model\MySql\Role\FieldListForm, \SqlSemantics\Statement\Model\MySql\Role\FieldListItemForm, \SqlSemantics\Statement\Model\MySql\Role\KeyDefForm
{
    /**
     * Supplies the SQL values of this form.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\MySql\Role\SpatialForm $spatial,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\OptKeyOrIndexForm $optKeyOrIndex,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\OptIdentForm $optIdent,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\InitKeyOptionsForm $initKeyOptions,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\KeyListForm $keyList,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\SpatialKeyOptionsForm $spatialKeyOptions,
    ) {
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $this->spatial->write($writer);
        $this->optKeyOrIndex->write($writer);
        $this->optIdent->write($writer);
        $this->initKeyOptions->write($writer);
        $writer->append('(');
        $this->keyList->write($writer);
        $writer->append(')');
        $this->spatialKeyOptions->write($writer);
    }
}
