<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The key_def SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\KeyDefWithNormalKeyTypeOptIdentKeyAlgKeyListNormalKeyOptions_ba727e03 $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class KeyDefWithNormalKeyTypeOptIdentKeyAlgKeyListNormalKeyOptions_ba727e03 implements \SqlSemantics\Statement\Model\MySql\Role\CreateFieldListForm, \SqlSemantics\Statement\Model\MySql\Role\FieldListForm, \SqlSemantics\Statement\Model\MySql\Role\FieldListItemForm, \SqlSemantics\Statement\Model\MySql\Role\KeyDefForm
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form; comments are kept by the position of the symbol each precedes.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\MySql\Role\NormalKeyTypeForm $normalKeyType,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\OptIdentForm $optIdent,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\KeyAlgForm $keyAlg,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\KeyListForm $keyList,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\NormalKeyOptionsForm $normalKeyOptions,
        public readonly \SqlSemantics\Statement\Comments $comments = new \SqlSemantics\Statement\Comments(),
    ) {
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($normalKeyType), 'The normalKeyType must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($optIdent), 'The optIdent must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($keyAlg), 'The keyAlg must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($keyList), 'The keyList must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($normalKeyOptions), 'The normalKeyOptions must be a generated immutable SQL value.');
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->comments($this->comments, 0);
        $this->normalKeyType->write($writer);
        $writer->comments($this->comments, 1);
        $this->optIdent->write($writer);
        $writer->comments($this->comments, 2);
        $this->keyAlg->write($writer);
        $writer->comments($this->comments, 3);
        $writer->append('(');
        $writer->comments($this->comments, 4);
        $this->keyList->write($writer);
        $writer->comments($this->comments, 5);
        $writer->append(')');
        $writer->comments($this->comments, 6);
        $this->normalKeyOptions->write($writer);
    }

    /**
     * Returns a copy with a new normalKeyType, preserving every other field.
     */
    public function withNormalKeyType(\SqlSemantics\Statement\Model\MySql\Role\NormalKeyTypeForm $normalKeyType): self
    {
        return new self($normalKeyType, $this->optIdent, $this->keyAlg, $this->keyList, $this->normalKeyOptions, $this->comments);
    }

    /**
     * Returns a copy with a new optIdent, preserving every other field.
     */
    public function withOptIdent(\SqlSemantics\Statement\Model\MySql\Role\OptIdentForm $optIdent): self
    {
        return new self($this->normalKeyType, $optIdent, $this->keyAlg, $this->keyList, $this->normalKeyOptions, $this->comments);
    }

    /**
     * Returns a copy with a new keyAlg, preserving every other field.
     */
    public function withKeyAlg(\SqlSemantics\Statement\Model\MySql\Role\KeyAlgForm $keyAlg): self
    {
        return new self($this->normalKeyType, $this->optIdent, $keyAlg, $this->keyList, $this->normalKeyOptions, $this->comments);
    }

    /**
     * Returns a copy with a new keyList, preserving every other field.
     */
    public function withKeyList(\SqlSemantics\Statement\Model\MySql\Role\KeyListForm $keyList): self
    {
        return new self($this->normalKeyType, $this->optIdent, $this->keyAlg, $keyList, $this->normalKeyOptions, $this->comments);
    }

    /**
     * Returns a copy with a new normalKeyOptions, preserving every other field.
     */
    public function withNormalKeyOptions(\SqlSemantics\Statement\Model\MySql\Role\NormalKeyOptionsForm $normalKeyOptions): self
    {
        return new self($this->normalKeyType, $this->optIdent, $this->keyAlg, $this->keyList, $normalKeyOptions, $this->comments);
    }

    /**
     * Returns a copy with a new comments, preserving every other field.
     */
    public function withComments(\SqlSemantics\Statement\Comments $comments): self
    {
        return new self($this->normalKeyType, $this->optIdent, $this->keyAlg, $this->keyList, $this->normalKeyOptions, $comments);
    }
}
