<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The key_list SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\KeyListWithKeyListKeyPartOrderDir_c89aca51 $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class KeyListWithKeyListKeyPartOrderDir_c89aca51 implements \SqlSemantics\Statement\Model\MySql\Role\KeyListForm
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\MySql\Role\KeyListForm $keyList,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\KeyPartForm $keyPart,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\OrderDirForm $orderDir,
    ) {
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($keyList), 'The keyList must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($keyPart), 'The keyPart must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($orderDir), 'The orderDir must be a generated immutable SQL value.');
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $this->keyList->write($writer);
        $writer->append(',');
        $this->keyPart->write($writer);
        $this->orderDir->write($writer);
    }

    /**
     * Returns a copy with a new keyList, preserving every other field.
     */
    public function withKeyList(\SqlSemantics\Statement\Model\MySql\Role\KeyListForm $keyList): self
    {
        return new self($keyList, $this->keyPart, $this->orderDir);
    }

    /**
     * Returns a copy with a new keyPart, preserving every other field.
     */
    public function withKeyPart(\SqlSemantics\Statement\Model\MySql\Role\KeyPartForm $keyPart): self
    {
        return new self($this->keyList, $keyPart, $this->orderDir);
    }

    /**
     * Returns a copy with a new orderDir, preserving every other field.
     */
    public function withOrderDir(\SqlSemantics\Statement\Model\MySql\Role\OrderDirForm $orderDir): self
    {
        return new self($this->keyList, $this->keyPart, $orderDir);
    }
}
