<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The key_part SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\KeyPartWithIdentOptOrderingDirection_408b0960 $value): string => (new \SqlSemantics\Statement\Statement($value))->toString();
 *     $write instanceof \Closure // => true
 */
final class KeyPartWithIdentOptOrderingDirection_408b0960 implements \SqlSemantics\Statement\Model\MySql\Role\KeyListForm, \SqlSemantics\Statement\Model\MySql\Role\KeyListWithExpressionForm, \SqlSemantics\Statement\Model\MySql\Role\KeyPartForm, \SqlSemantics\Statement\Model\MySql\Role\KeyPartWithExpressionForm
{
    /**
     * Supplies the SQL values of this form.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\MySql\Role\IdentForm $ident,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\OptOrderingDirectionForm $optOrderingDirection,
    ) {
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $this->ident->write($writer);
        $this->optOrderingDirection->write($writer);
    }
}
