<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The key_using_alg SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\KeyUsingAlgWithUsingBtreeOrRtree_1999c2ef $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class KeyUsingAlgWithUsingBtreeOrRtree_1999c2ef implements \SqlSemantics\Statement\Model\MySql\Role\KeyUsingAlgForm, \SqlSemantics\Statement\Model\MySql\Role\NormalKeyOptForm, \SqlSemantics\Statement\Model\MySql\Role\NormalKeyOptionsForm, \SqlSemantics\Statement\Model\MySql\Role\NormalKeyOptsForm
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form; comments are kept by the position of the symbol each precedes.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\MySql\Role\BtreeOrRtreeForm $btreeOrRtree,
        public readonly \SqlSemantics\Statement\Comments $comments = new \SqlSemantics\Statement\Comments(),
    ) {
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($btreeOrRtree), 'The btreeOrRtree must be a generated immutable SQL value.');
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->comments($this->comments, 0);
        $writer->append('USING');
        $writer->comments($this->comments, 1);
        $this->btreeOrRtree->write($writer);
    }

    /**
     * Returns a copy with a new btreeOrRtree, preserving every other field.
     */
    public function withBtreeOrRtree(\SqlSemantics\Statement\Model\MySql\Role\BtreeOrRtreeForm $btreeOrRtree): self
    {
        return new self($btreeOrRtree, $this->comments);
    }

    /**
     * Returns a copy with a new comments, preserving every other field.
     */
    public function withComments(\SqlSemantics\Statement\Comments $comments): self
    {
        return new self($this->btreeOrRtree, $comments);
    }
}
