<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The logfile_group_option_list SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\LogfileGroupOptionListWithLogfileGroupOptionListOptCommaLogfileGroupOption_3e331a47 $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class LogfileGroupOptionListWithLogfileGroupOptionListOptCommaLogfileGroupOption_3e331a47 implements \SqlSemantics\Statement\Model\MySql\Role\LogfileGroupOptionListForm, \SqlSemantics\Statement\Model\MySql\Role\OptLogfileGroupOptionsForm
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form; comments are kept by the position of the symbol each precedes.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\MySql\Role\LogfileGroupOptionListForm $logfileGroupOptionList,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\OptCommaForm $optComma,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\LogfileGroupOptionForm $logfileGroupOption,
        public readonly \SqlSemantics\Statement\Comments $comments = new \SqlSemantics\Statement\Comments(),
    ) {
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($logfileGroupOptionList), 'The logfileGroupOptionList must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($optComma), 'The optComma must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($logfileGroupOption), 'The logfileGroupOption must be a generated immutable SQL value.');
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->comments($this->comments, 0);
        $this->logfileGroupOptionList->write($writer);
        $writer->comments($this->comments, 1);
        $this->optComma->write($writer);
        $writer->comments($this->comments, 2);
        $this->logfileGroupOption->write($writer);
    }

    /**
     * Returns a copy with a new logfileGroupOptionList, preserving every other field.
     */
    public function withLogfileGroupOptionList(\SqlSemantics\Statement\Model\MySql\Role\LogfileGroupOptionListForm $logfileGroupOptionList): self
    {
        return new self($logfileGroupOptionList, $this->optComma, $this->logfileGroupOption, $this->comments);
    }

    /**
     * Returns a copy with a new optComma, preserving every other field.
     */
    public function withOptComma(\SqlSemantics\Statement\Model\MySql\Role\OptCommaForm $optComma): self
    {
        return new self($this->logfileGroupOptionList, $optComma, $this->logfileGroupOption, $this->comments);
    }

    /**
     * Returns a copy with a new logfileGroupOption, preserving every other field.
     */
    public function withLogfileGroupOption(\SqlSemantics\Statement\Model\MySql\Role\LogfileGroupOptionForm $logfileGroupOption): self
    {
        return new self($this->logfileGroupOptionList, $this->optComma, $logfileGroupOption, $this->comments);
    }

    /**
     * Returns a copy with a new comments, preserving every other field.
     */
    public function withComments(\SqlSemantics\Statement\Comments $comments): self
    {
        return new self($this->logfileGroupOptionList, $this->optComma, $this->logfileGroupOption, $comments);
    }
}
