<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The master_defs SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\MasterDefsWithMasterDefsMasterDef_98a7a6bb $value): string => (new \SqlSemantics\Statement\Statement($value))->toString();
 *     $write instanceof \Closure // => true
 */
final class MasterDefsWithMasterDefsMasterDef_98a7a6bb implements \SqlSemantics\Statement\Model\MySql\Role\MasterDefsForm
{
    /**
     * Supplies the SQL values of this form.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\MySql\Role\MasterDefsForm $masterDefs,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\MasterDefForm $masterDef,
    ) {
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $this->masterDefs->write($writer);
        $writer->append(',');
        $this->masterDef->write($writer);
    }
}
