<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The master_def SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\MasterDefWithMasterDelaySymEqUlongNum_69df80cf $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class MasterDefWithMasterDelaySymEqUlongNum_69df80cf implements \SqlSemantics\Statement\Model\MySql\Role\MasterDefForm, \SqlSemantics\Statement\Model\MySql\Role\MasterDefsForm
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form; comments are kept by the position of the symbol each precedes.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\MySql\Role\UlongNumForm $ulongNum,
        public readonly \SqlSemantics\Statement\Comments $comments = new \SqlSemantics\Statement\Comments(),
    ) {
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($ulongNum), 'The ulongNum must be a generated immutable SQL value.');
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->comments($this->comments, 0);
        $writer->append('MASTER_DELAY');
        $writer->comments($this->comments, 1);
        $writer->append('=');
        $writer->comments($this->comments, 2);
        $this->ulongNum->write($writer);
    }

    /**
     * Returns a copy with a new ulongNum, preserving every other field.
     */
    public function withUlongNum(\SqlSemantics\Statement\Model\MySql\Role\UlongNumForm $ulongNum): self
    {
        return new self($ulongNum, $this->comments);
    }

    /**
     * Returns a copy with a new comments, preserving every other field.
     */
    public function withComments(\SqlSemantics\Statement\Comments $comments): self
    {
        return new self($this->ulongNum, $comments);
    }
}
