<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The opt_ev_comment SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\OptEvCommentWithCommentSymTextStringSys_ba4aec74 $value): string => (new \SqlSemantics\Statement\Statement($value))->toString();
 *     $write instanceof \Closure // => true
 */
final class OptEvCommentWithCommentSymTextStringSys_ba4aec74 implements \SqlSemantics\Statement\Model\MySql\Role\OptEvCommentForm
{
    /**
     * Supplies the SQL values of this form.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\MySql\Role\TextStringSysForm $textStringSys,
    ) {
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->append('COMMENT');
        $this->textStringSys->write($writer);
    }
}
