<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The opt_histogram SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\OptHistogramWithUpdateSymHistogramSymOnSymIdentStringListOptHistogramUpdateParam_1ccea86d $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class OptHistogramWithUpdateSymHistogramSymOnSymIdentStringListOptHistogramUpdateParam_1ccea86d implements \SqlSemantics\Statement\Model\MySql\Role\OptHistogramForm
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form; comments are kept by the position of the symbol each precedes.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\MySql\Role\IdentStringListForm $identStringList,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\OptHistogramUpdateParamForm $optHistogramUpdateParam,
        public readonly \SqlSemantics\Statement\Comments $comments = new \SqlSemantics\Statement\Comments(),
    ) {
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($identStringList), 'The identStringList must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($optHistogramUpdateParam), 'The optHistogramUpdateParam must be a generated immutable SQL value.');
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->comments($this->comments, 0);
        $writer->append('UPDATE');
        $writer->comments($this->comments, 1);
        $writer->append('HISTOGRAM');
        $writer->comments($this->comments, 2);
        $writer->append('ON');
        $writer->comments($this->comments, 3);
        $this->identStringList->write($writer);
        $writer->comments($this->comments, 4);
        $this->optHistogramUpdateParam->write($writer);
    }

    /**
     * Lists the values of this form, in writing order.
     *
     * @return list<\SqlSemantics\Statement\Element>
     */
    public function children(): array
    {
        return [$this->identStringList, $this->optHistogramUpdateParam];
    }

    /**
     * Returns this value rebuilt around what the function answers for each value, keeping lexical fields and comments; itself when every answer is the value it was given.
     *
     * @param callable(\SqlSemantics\Statement\Element): \SqlSemantics\Statement\Element $replace
     */
    public function map(callable $replace): static
    {
        $mapped = [$this->replacement($this->identStringList, \SqlSemantics\Statement\Model\MySql\Role\IdentStringListForm::class, $replace), $this->replacement($this->optHistogramUpdateParam, \SqlSemantics\Statement\Model\MySql\Role\OptHistogramUpdateParamForm::class, $replace)];

        return $mapped === [$this->identStringList, $this->optHistogramUpdateParam] ? $this : new self($mapped[0], $mapped[1], $this->comments);
    }

    /**
     * Returns a copy with a new identStringList, preserving every other field.
     */
    public function withIdentStringList(\SqlSemantics\Statement\Model\MySql\Role\IdentStringListForm $identStringList): self
    {
        return new self($identStringList, $this->optHistogramUpdateParam, $this->comments);
    }

    /**
     * Returns a copy with a new optHistogramUpdateParam, preserving every other field.
     */
    public function withOptHistogramUpdateParam(\SqlSemantics\Statement\Model\MySql\Role\OptHistogramUpdateParamForm $optHistogramUpdateParam): self
    {
        return new self($this->identStringList, $optHistogramUpdateParam, $this->comments);
    }

    /**
     * Returns a copy with a new comments, preserving every other field.
     */
    public function withComments(\SqlSemantics\Statement\Comments $comments): self
    {
        return new self($this->identStringList, $this->optHistogramUpdateParam, $comments);
    }
}
