<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The opt_on_update_delete SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\OptOnUpdateDeleteWithOnSymDeleteSymDeleteOptionOnSymUpdateSymDeleteOption_e957a5fd $value): string => (new \SqlSemantics\Statement\Statement($value))->toString();
 *     $write instanceof \Closure // => true
 */
final class OptOnUpdateDeleteWithOnSymDeleteSymDeleteOptionOnSymUpdateSymDeleteOption_e957a5fd implements \SqlSemantics\Statement\Model\MySql\Role\OptOnUpdateDeleteForm
{
    /**
     * Supplies the SQL values of this form.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\MySql\Role\DeleteOptionForm $deleteOption,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\DeleteOptionForm $deleteOption2,
    ) {
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->append('ON');
        $writer->append('DELETE');
        $this->deleteOption->write($writer);
        $writer->append('ON');
        $writer->append('UPDATE');
        $this->deleteOption2->write($writer);
    }
}
