<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The opt_part_option SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\OptPartOptionWithNodegroupSymOptEqualRealUlongNum_2349bcf6 $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class OptPartOptionWithNodegroupSymOptEqualRealUlongNum_2349bcf6 implements \SqlSemantics\Statement\Model\MySql\Role\OptPartOptionForm, \SqlSemantics\Statement\Model\MySql\Role\OptPartOptionListForm, \SqlSemantics\Statement\Model\MySql\Role\OptPartOptionsForm
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\MySql\Role\OptEqualForm $optEqual,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\RealUlongNumForm $realUlongNum,
    ) {
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($optEqual), 'The optEqual must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($realUlongNum), 'The realUlongNum must be a generated immutable SQL value.');
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->append('NODEGROUP');
        $this->optEqual->write($writer);
        $this->realUlongNum->write($writer);
    }

    /**
     * Returns a copy with a new optEqual, preserving every other field.
     */
    public function withOptEqual(\SqlSemantics\Statement\Model\MySql\Role\OptEqualForm $optEqual): self
    {
        return new self($optEqual, $this->realUlongNum);
    }

    /**
     * Returns a copy with a new realUlongNum, preserving every other field.
     */
    public function withRealUlongNum(\SqlSemantics\Statement\Model\MySql\Role\RealUlongNumForm $realUlongNum): self
    {
        return new self($this->optEqual, $realUlongNum);
    }
}
