<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The opt_set_signal_information SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\OptSetSignalInformationWithSetSignalInformationItemList_398bb131 $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class OptSetSignalInformationWithSetSignalInformationItemList_398bb131 implements \SqlSemantics\Statement\Model\MySql\Role\OptSetSignalInformationForm
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form; comments are kept by the position of the symbol each precedes.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\MySql\Role\SignalInformationItemListForm $signalInformationItemList,
        public readonly \SqlSemantics\Statement\Comments $comments = new \SqlSemantics\Statement\Comments(),
    ) {
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($signalInformationItemList), 'The signalInformationItemList must be a generated immutable SQL value.');
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->comments($this->comments, 0);
        $writer->append('SET');
        $writer->comments($this->comments, 1);
        $this->signalInformationItemList->write($writer);
    }

    /**
     * Returns a copy with a new signalInformationItemList, preserving every other field.
     */
    public function withSignalInformationItemList(\SqlSemantics\Statement\Model\MySql\Role\SignalInformationItemListForm $signalInformationItemList): self
    {
        return new self($signalInformationItemList, $this->comments);
    }

    /**
     * Returns a copy with a new comments, preserving every other field.
     */
    public function withComments(\SqlSemantics\Statement\Comments $comments): self
    {
        return new self($this->signalInformationItemList, $comments);
    }
}
