<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The opt_sub_partition SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\OptSubPartitionWithSubPartList_cabd577c $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class OptSubPartitionWithSubPartList_cabd577c implements \SqlSemantics\Statement\Model\MySql\Role\OptSubPartitionForm
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\MySql\Role\SubPartListForm $subPartList,
    ) {
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($subPartList), 'The subPartList must be a generated immutable SQL value.');
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->append('(');
        $this->subPartList->write($writer);
        $writer->append(')');
    }

    /**
     * Returns a copy with a new subPartList, preserving every other field.
     */
    public function withSubPartList(\SqlSemantics\Statement\Model\MySql\Role\SubPartListForm $subPartList): self
    {
        return new self($subPartList);
    }
}
