<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The opt_ts_initial_size SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\OptTsInitialSizeWithInitialSizeSymOptEqualSizeNumber_8698bf6b $value): string => (new \SqlSemantics\Statement\Statement($value))->toString();
 *     $write instanceof \Closure // => true
 */
final class OptTsInitialSizeWithInitialSizeSymOptEqualSizeNumber_8698bf6b implements \SqlSemantics\Statement\Model\MySql\Role\AlterLogfileGroupOptionForm, \SqlSemantics\Statement\Model\MySql\Role\AlterLogfileGroupOptionListForm, \SqlSemantics\Statement\Model\MySql\Role\AlterLogfileGroupOptionsForm, \SqlSemantics\Statement\Model\MySql\Role\AlterTablespaceOptionForm, \SqlSemantics\Statement\Model\MySql\Role\AlterTablespaceOptionListForm, \SqlSemantics\Statement\Model\MySql\Role\AlterTablespaceOptionsForm, \SqlSemantics\Statement\Model\MySql\Role\ChangeTsOptionForm, \SqlSemantics\Statement\Model\MySql\Role\ChangeTsOptionListForm, \SqlSemantics\Statement\Model\MySql\Role\ChangeTsOptionsForm, \SqlSemantics\Statement\Model\MySql\Role\LogfileGroupOptionForm, \SqlSemantics\Statement\Model\MySql\Role\LogfileGroupOptionListForm, \SqlSemantics\Statement\Model\MySql\Role\LogfileGroupOptionsForm, \SqlSemantics\Statement\Model\MySql\Role\OptAlterLogfileGroupOptionsForm, \SqlSemantics\Statement\Model\MySql\Role\OptAlterTablespaceOptionsForm, \SqlSemantics\Statement\Model\MySql\Role\OptLogfileGroupOptionsForm, \SqlSemantics\Statement\Model\MySql\Role\OptTablespaceOptionsForm, \SqlSemantics\Statement\Model\MySql\Role\OptTsInitialSizeForm, \SqlSemantics\Statement\Model\MySql\Role\TablespaceOptionForm, \SqlSemantics\Statement\Model\MySql\Role\TablespaceOptionListForm, \SqlSemantics\Statement\Model\MySql\Role\TablespaceOptionsForm
{
    /**
     * Supplies the SQL values of this form.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\MySql\Role\OptEqualForm $optEqual,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\SizeNumberForm $sizeNumber,
    ) {
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->append('INITIAL_SIZE');
        $this->optEqual->write($writer);
        $this->sizeNumber->write($writer);
    }
}
