<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The opt_table_alias SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\OptTableAliasWithOptAsIdent_35f95dae $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class OptTableAliasWithOptAsIdent_35f95dae implements \SqlSemantics\Statement\Model\MySql\Role\OptTableAliasForm
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\MySql\Role\OptAsForm $optAs,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\IdentForm $ident,
    ) {
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($optAs), 'The optAs must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($ident), 'The ident must be a generated immutable SQL value.');
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $this->optAs->write($writer);
        $this->ident->write($writer);
    }

    /**
     * Returns a copy with a new optAs, preserving every other field.
     */
    public function withOptAs(\SqlSemantics\Statement\Model\MySql\Role\OptAsForm $optAs): self
    {
        return new self($optAs, $this->ident);
    }

    /**
     * Returns a copy with a new ident, preserving every other field.
     */
    public function withIdent(\SqlSemantics\Statement\Model\MySql\Role\IdentForm $ident): self
    {
        return new self($this->optAs, $ident);
    }
}
