<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The opt_ts_engine SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\OptTsEngineWithOptStorageEngineSymOptEqualStorageEngines_cbf76920 $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class OptTsEngineWithOptStorageEngineSymOptEqualStorageEngines_cbf76920 implements \SqlSemantics\Statement\Model\MySql\Role\AlterLogfileGroupOptionForm, \SqlSemantics\Statement\Model\MySql\Role\AlterLogfileGroupOptionListForm, \SqlSemantics\Statement\Model\MySql\Role\AlterLogfileGroupOptionsForm, \SqlSemantics\Statement\Model\MySql\Role\AlterTablespaceOptionForm, \SqlSemantics\Statement\Model\MySql\Role\AlterTablespaceOptionListForm, \SqlSemantics\Statement\Model\MySql\Role\AlterTablespaceOptionsForm, \SqlSemantics\Statement\Model\MySql\Role\DropTsOptionForm, \SqlSemantics\Statement\Model\MySql\Role\DropTsOptionListForm, \SqlSemantics\Statement\Model\MySql\Role\DropTsOptionsForm, \SqlSemantics\Statement\Model\MySql\Role\DropTsOptionsListForm, \SqlSemantics\Statement\Model\MySql\Role\LogfileGroupOptionForm, \SqlSemantics\Statement\Model\MySql\Role\LogfileGroupOptionListForm, \SqlSemantics\Statement\Model\MySql\Role\LogfileGroupOptionsForm, \SqlSemantics\Statement\Model\MySql\Role\OptAlterLogfileGroupOptionsForm, \SqlSemantics\Statement\Model\MySql\Role\OptAlterTablespaceOptionsForm, \SqlSemantics\Statement\Model\MySql\Role\OptDropTsOptionsForm, \SqlSemantics\Statement\Model\MySql\Role\OptLogfileGroupOptionsForm, \SqlSemantics\Statement\Model\MySql\Role\OptTablespaceOptionsForm, \SqlSemantics\Statement\Model\MySql\Role\OptTsEngineForm, \SqlSemantics\Statement\Model\MySql\Role\TablespaceOptionForm, \SqlSemantics\Statement\Model\MySql\Role\TablespaceOptionListForm, \SqlSemantics\Statement\Model\MySql\Role\TablespaceOptionsForm
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\MySql\Role\OptStorageForm $optStorage,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\OptEqualForm $optEqual,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\StorageEnginesForm $storageEngines,
    ) {
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($optStorage), 'The optStorage must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($optEqual), 'The optEqual must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($storageEngines), 'The storageEngines must be a generated immutable SQL value.');
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $this->optStorage->write($writer);
        $writer->append('ENGINE');
        $this->optEqual->write($writer);
        $this->storageEngines->write($writer);
    }

    /**
     * Returns a copy with a new optStorage, preserving every other field.
     */
    public function withOptStorage(\SqlSemantics\Statement\Model\MySql\Role\OptStorageForm $optStorage): self
    {
        return new self($optStorage, $this->optEqual, $this->storageEngines);
    }

    /**
     * Returns a copy with a new optEqual, preserving every other field.
     */
    public function withOptEqual(\SqlSemantics\Statement\Model\MySql\Role\OptEqualForm $optEqual): self
    {
        return new self($this->optStorage, $optEqual, $this->storageEngines);
    }

    /**
     * Returns a copy with a new storageEngines, preserving every other field.
     */
    public function withStorageEngines(\SqlSemantics\Statement\Model\MySql\Role\StorageEnginesForm $storageEngines): self
    {
        return new self($this->optStorage, $this->optEqual, $storageEngines);
    }
}
