<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The part_type_def SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\PartTypeDefWithOptLinearKeySymOptKeyAlgoPartFieldList_f9de8824 $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class PartTypeDefWithOptLinearKeySymOptKeyAlgoPartFieldList_f9de8824 implements \SqlSemantics\Statement\Model\MySql\Role\PartTypeDefForm
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form; comments are kept by the position of the symbol each precedes.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\MySql\Role\OptLinearForm $optLinear,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\OptKeyAlgoForm $optKeyAlgo,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\PartFieldListForm $partFieldList,
        public readonly \SqlSemantics\Statement\Comments $comments = new \SqlSemantics\Statement\Comments(),
    ) {
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($optLinear), 'The optLinear must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($optKeyAlgo), 'The optKeyAlgo must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($partFieldList), 'The partFieldList must be a generated immutable SQL value.');
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->comments($this->comments, 0);
        $this->optLinear->write($writer);
        $writer->comments($this->comments, 1);
        $writer->append('KEY');
        $writer->comments($this->comments, 2);
        $this->optKeyAlgo->write($writer);
        $writer->comments($this->comments, 3);
        $writer->append('(');
        $writer->comments($this->comments, 4);
        $this->partFieldList->write($writer);
        $writer->comments($this->comments, 5);
        $writer->append(')');
    }

    /**
     * Returns a copy with a new optLinear, preserving every other field.
     */
    public function withOptLinear(\SqlSemantics\Statement\Model\MySql\Role\OptLinearForm $optLinear): self
    {
        return new self($optLinear, $this->optKeyAlgo, $this->partFieldList, $this->comments);
    }

    /**
     * Returns a copy with a new optKeyAlgo, preserving every other field.
     */
    public function withOptKeyAlgo(\SqlSemantics\Statement\Model\MySql\Role\OptKeyAlgoForm $optKeyAlgo): self
    {
        return new self($this->optLinear, $optKeyAlgo, $this->partFieldList, $this->comments);
    }

    /**
     * Returns a copy with a new partFieldList, preserving every other field.
     */
    public function withPartFieldList(\SqlSemantics\Statement\Model\MySql\Role\PartFieldListForm $partFieldList): self
    {
        return new self($this->optLinear, $this->optKeyAlgo, $partFieldList, $this->comments);
    }

    /**
     * Returns a copy with a new comments, preserving every other field.
     */
    public function withComments(\SqlSemantics\Statement\Comments $comments): self
    {
        return new self($this->optLinear, $this->optKeyAlgo, $this->partFieldList, $comments);
    }
}
