<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The predicate SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\PredicateWithBitExprLikeSimpleExprEscapeSymSimpleExpr_95bd7cd4 $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class PredicateWithBitExprLikeSimpleExprEscapeSymSimpleExpr_95bd7cd4 implements \SqlSemantics\Statement\Model\MySql\Role\BoolPriForm, \SqlSemantics\Statement\Model\MySql\Role\ExprForm, \SqlSemantics\Statement\Model\MySql\Role\ExprListForm, \SqlSemantics\Statement\Model\MySql\Role\ExprOrDefaultForm, \SqlSemantics\Statement\Model\MySql\Role\GeneratedColumnFuncForm, \SqlSemantics\Statement\Model\MySql\Role\GroupListForm, \SqlSemantics\Statement\Model\MySql\Role\GroupingExprForm, \SqlSemantics\Statement\Model\MySql\Role\InstallSetRvalueForm, \SqlSemantics\Statement\Model\MySql\Role\OptExprForm, \SqlSemantics\Statement\Model\MySql\Role\OptExprListForm, \SqlSemantics\Statement\Model\MySql\Role\OptSpCparamsForm, \SqlSemantics\Statement\Model\MySql\Role\OptValuesForm, \SqlSemantics\Statement\Model\MySql\Role\OrderIdentForm, \SqlSemantics\Statement\Model\MySql\Role\PredicateForm, \SqlSemantics\Statement\Model\MySql\Role\SetExprOrDefaultForm, \SqlSemantics\Statement\Model\MySql\Role\SpCparamsForm, \SqlSemantics\Statement\Model\MySql\Role\ValuesForm
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\MySql\Role\BitExprForm $bitExpr,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\SimpleExprForm $simpleExpr,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\SimpleExprForm $simpleExpr2,
    ) {
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($bitExpr), 'The bitExpr must be a generated immutable SQL value.');
        $this->assertOperandBindingStrength($bitExpr, \SqlSemantics\Statement\Model\MySql\Contract\Contracts::BINDING_POWERS, array (  'mysql-8.0.44' => 14,  'mysql-8.1.0' => 14,  'mysql-8.2.0' => 14,  'mysql-8.3.0' => 14,  'mysql-8.4.7' => 14,  'mysql-9.0.1' => 14,  'mysql-9.1.0' => 14,));
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($simpleExpr), 'The simpleExpr must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($simpleExpr2), 'The simpleExpr2 must be a generated immutable SQL value.');
        $this->assertOperandBindingStrength($simpleExpr2, \SqlSemantics\Statement\Model\MySql\Contract\Contracts::BINDING_POWERS, array (  'mysql-8.0.44' => 15,  'mysql-8.1.0' => 15,  'mysql-8.2.0' => 15,  'mysql-8.3.0' => 15,  'mysql-8.4.7' => 15,  'mysql-9.0.1' => 15,  'mysql-9.1.0' => 15,));
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $this->bitExpr->write($writer);
        $writer->append('LIKE');
        $this->simpleExpr->write($writer);
        $writer->append('ESCAPE');
        $this->simpleExpr2->write($writer);
    }

    /**
     * Returns a copy with a new bitExpr, preserving every other field.
     */
    public function withBitExpr(\SqlSemantics\Statement\Model\MySql\Role\BitExprForm $bitExpr): self
    {
        return new self($bitExpr, $this->simpleExpr, $this->simpleExpr2);
    }

    /**
     * Returns a copy with a new simpleExpr, preserving every other field.
     */
    public function withSimpleExpr(\SqlSemantics\Statement\Model\MySql\Role\SimpleExprForm $simpleExpr): self
    {
        return new self($this->bitExpr, $simpleExpr, $this->simpleExpr2);
    }

    /**
     * Returns a copy with a new simpleExpr2, preserving every other field.
     */
    public function withSimpleExpr2(\SqlSemantics\Statement\Model\MySql\Role\SimpleExprForm $simpleExpr2): self
    {
        return new self($this->bitExpr, $this->simpleExpr, $simpleExpr2);
    }
}
