<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The query_specification SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\QuerySpecificationWithSelectSymSelectInit2Derived_cb2c9ac3 $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class QuerySpecificationWithSelectSymSelectInit2Derived_cb2c9ac3 implements \SqlSemantics\Statement\Model\MySql\Role\QueryExpressionBodyForm, \SqlSemantics\Statement\Model\MySql\Role\QueryPrimaryForm, \SqlSemantics\Statement\Model\MySql\Role\QuerySpecificationForm, \SqlSemantics\Statement\Model\MySql\Role\SubselectForm
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\MySql\Role\SelectInit2DerivedForm $selectInit2Derived,
    ) {
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($selectInit2Derived), 'The selectInit2Derived must be a generated immutable SQL value.');
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->append('SELECT');
        $this->selectInit2Derived->write($writer);
    }

    /**
     * Returns a copy with a new selectInit2Derived, preserving every other field.
     */
    public function withSelectInit2Derived(\SqlSemantics\Statement\Model\MySql\Role\SelectInit2DerivedForm $selectInit2Derived): self
    {
        return new self($selectInit2Derived);
    }
}
