<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The query_specification SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\QuerySpecificationWithSelectParenDerived_a7ed1cea $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class QuerySpecificationWithSelectParenDerived_a7ed1cea implements \SqlSemantics\Statement\Model\MySql\Role\QueryExpressionBodyForm, \SqlSemantics\Statement\Model\MySql\Role\QueryPrimaryForm, \SqlSemantics\Statement\Model\MySql\Role\QuerySpecificationForm, \SqlSemantics\Statement\Model\MySql\Role\SubselectForm
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form; comments are kept by the position of the symbol each precedes.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\MySql\Role\SelectParenDerivedForm $selectParenDerived,
        public readonly \SqlSemantics\Statement\Comments $comments = new \SqlSemantics\Statement\Comments(),
    ) {
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($selectParenDerived), 'The selectParenDerived must be a generated immutable SQL value.');
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->comments($this->comments, 0);
        $writer->append('(');
        $writer->comments($this->comments, 1);
        $this->selectParenDerived->write($writer);
        $writer->comments($this->comments, 2);
        $writer->append(')');
    }

    /**
     * Returns a copy with a new selectParenDerived, preserving every other field.
     */
    public function withSelectParenDerived(\SqlSemantics\Statement\Model\MySql\Role\SelectParenDerivedForm $selectParenDerived): self
    {
        return new self($selectParenDerived, $this->comments);
    }

    /**
     * Returns a copy with a new comments, preserving every other field.
     */
    public function withComments(\SqlSemantics\Statement\Comments $comments): self
    {
        return new self($this->selectParenDerived, $comments);
    }
}
