<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The query_expression_body SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\QueryExpressionBodyWithQuerySpecificationOptUnionOrderOrLimit_c93fd014 $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class QueryExpressionBodyWithQuerySpecificationOptUnionOrderOrLimit_c93fd014 implements \SqlSemantics\Statement\Model\MySql\Role\QueryExpressionBodyForm, \SqlSemantics\Statement\Model\MySql\Role\SubselectForm
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form; comments are kept by the position of the symbol each precedes.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\MySql\Role\QuerySpecificationForm $query,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\OptUnionOrderOrLimitForm $optUnionOrderOrLimit,
        public readonly \SqlSemantics\Statement\Comments $comments = new \SqlSemantics\Statement\Comments(),
    ) {
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($query), 'The query must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($optUnionOrderOrLimit), 'The optUnionOrderOrLimit must be a generated immutable SQL value.');
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->comments($this->comments, 0);
        $this->query->write($writer);
        $writer->comments($this->comments, 1);
        $this->optUnionOrderOrLimit->write($writer);
    }

    /**
     * Lists the values of this form, in writing order.
     *
     * @return list<\SqlSemantics\Statement\Element>
     */
    public function children(): array
    {
        return [$this->query, $this->optUnionOrderOrLimit];
    }

    /**
     * Returns this value rebuilt around what the function answers for each value, keeping lexical fields and comments; itself when every answer is the value it was given.
     *
     * @param callable(\SqlSemantics\Statement\Element): \SqlSemantics\Statement\Element $replace
     */
    public function map(callable $replace): static
    {
        $mapped = [$this->replacement($this->query, \SqlSemantics\Statement\Model\MySql\Role\QuerySpecificationForm::class, $replace), $this->replacement($this->optUnionOrderOrLimit, \SqlSemantics\Statement\Model\MySql\Role\OptUnionOrderOrLimitForm::class, $replace)];

        return $mapped === [$this->query, $this->optUnionOrderOrLimit] ? $this : new self($mapped[0], $mapped[1], $this->comments);
    }

    /**
     * Returns a copy with a new query, preserving every other field.
     */
    public function withQuery(\SqlSemantics\Statement\Model\MySql\Role\QuerySpecificationForm $query): self
    {
        return new self($query, $this->optUnionOrderOrLimit, $this->comments);
    }

    /**
     * Returns a copy with a new optUnionOrderOrLimit, preserving every other field.
     */
    public function withOptUnionOrderOrLimit(\SqlSemantics\Statement\Model\MySql\Role\OptUnionOrderOrLimitForm $optUnionOrderOrLimit): self
    {
        return new self($this->query, $optUnionOrderOrLimit, $this->comments);
    }

    /**
     * Returns a copy with a new comments, preserving every other field.
     */
    public function withComments(\SqlSemantics\Statement\Comments $comments): self
    {
        return new self($this->query, $this->optUnionOrderOrLimit, $comments);
    }
}
