<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The query_spec_option SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\QuerySpecOptionWithSqlSmallResult_8536083c $value): string => (new \SqlSemantics\Statement\Statement($value))->toString();
 *     $write instanceof \Closure // => true
 */
final class QuerySpecOptionWithSqlSmallResult_8536083c implements \SqlSemantics\Statement\Model\MySql\Role\OptQuerySpecOptionsForm, \SqlSemantics\Statement\Model\MySql\Role\QuerySpecOptionForm, \SqlSemantics\Statement\Model\MySql\Role\QuerySpecOptionListForm, \SqlSemantics\Statement\Model\MySql\Role\SelectOptionForm, \SqlSemantics\Statement\Model\MySql\Role\SelectOptionListForm, \SqlSemantics\Statement\Model\MySql\Role\SelectOptionsForm
{
    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->append('SQL_SMALL_RESULT');
    }
}
