<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The reference_list SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\ReferenceListWithReferenceListIdent_53d13dba $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class ReferenceListWithReferenceListIdent_53d13dba implements \SqlSemantics\Statement\Model\MySql\Role\ReferenceListForm
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form; comments are kept by the position of the symbol each precedes.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\MySql\Role\ReferenceListForm $referenceList,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\IdentForm $ident,
        public readonly \SqlSemantics\Statement\Comments $comments = new \SqlSemantics\Statement\Comments(),
    ) {
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($referenceList), 'The referenceList must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($ident), 'The ident must be a generated immutable SQL value.');
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->comments($this->comments, 0);
        $this->referenceList->write($writer);
        $writer->comments($this->comments, 1);
        $writer->append(',');
        $writer->comments($this->comments, 2);
        $this->ident->write($writer);
    }

    /**
     * Returns a copy with a new referenceList, preserving every other field.
     */
    public function withReferenceList(\SqlSemantics\Statement\Model\MySql\Role\ReferenceListForm $referenceList): self
    {
        return new self($referenceList, $this->ident, $this->comments);
    }

    /**
     * Returns a copy with a new ident, preserving every other field.
     */
    public function withIdent(\SqlSemantics\Statement\Model\MySql\Role\IdentForm $ident): self
    {
        return new self($this->referenceList, $ident, $this->comments);
    }

    /**
     * Returns a copy with a new comments, preserving every other field.
     */
    public function withComments(\SqlSemantics\Statement\Comments $comments): self
    {
        return new self($this->referenceList, $this->ident, $comments);
    }
}
