<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The revoke SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\RevokeWithRevokeIfExistsAllOptPrivilegesOnSymOptAclTypeGrantIdentFromUserListOptIgnor_81623cb0 $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class RevokeWithRevokeIfExistsAllOptPrivilegesOnSymOptAclTypeGrantIdentFromUserListOptIgnor_81623cb0 implements \SqlSemantics\Statement\Model\MySql\Role\EvSqlStmtForm, \SqlSemantics\Statement\Model\MySql\Role\EvSqlStmtInnerForm, \SqlSemantics\Statement\Model\MySql\Role\RevokeForm, \SqlSemantics\Statement\Model\MySql\Role\SimpleStatementForm, \SqlSemantics\Statement\Model\MySql\Role\SimpleStatementOrBeginForm, \SqlSemantics\Statement\Model\MySql\Role\SpProcStmtForm, \SqlSemantics\Statement\Model\MySql\Role\SpProcStmtStatementForm, \SqlSemantics\Statement\Model\MySql\Role\StatementForm, \SqlSemantics\Statement\Model\MySql\Role\StoredRoutineBodyForm, \SqlSemantics\Statement\Model\MySql\Role\VerbClauseForm, \SqlSemantics\Statement\Command
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form; comments are kept by the position of the symbol each precedes.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\MySql\Role\IfExistsForm $ifExists,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\OptPrivilegesForm $optPrivileges,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\OptAclTypeForm $optAclType,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\GrantIdentForm $grantIdent,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\UserListForm $userList,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\OptIgnoreUnknownUserForm $optIgnoreUnknownUser,
        public readonly \SqlSemantics\Statement\Comments $comments = new \SqlSemantics\Statement\Comments(),
    ) {
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($ifExists), 'The ifExists must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($optPrivileges), 'The optPrivileges must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($optAclType), 'The optAclType must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($grantIdent), 'The grantIdent must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($userList), 'The userList must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($optIgnoreUnknownUser), 'The optIgnoreUnknownUser must be a generated immutable SQL value.');
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->comments($this->comments, 0);
        $writer->append('REVOKE');
        $writer->comments($this->comments, 1);
        $this->ifExists->write($writer);
        $writer->comments($this->comments, 2);
        $writer->append('ALL');
        $writer->comments($this->comments, 3);
        $this->optPrivileges->write($writer);
        $writer->comments($this->comments, 4);
        $writer->append('ON');
        $writer->comments($this->comments, 5);
        $this->optAclType->write($writer);
        $writer->comments($this->comments, 6);
        $this->grantIdent->write($writer);
        $writer->comments($this->comments, 7);
        $writer->append('FROM');
        $writer->comments($this->comments, 8);
        $this->userList->write($writer);
        $writer->comments($this->comments, 9);
        $this->optIgnoreUnknownUser->write($writer);
    }

    /**
     * Lists the values of this form, in writing order.
     *
     * @return list<\SqlSemantics\Statement\Element>
     */
    public function children(): array
    {
        return [$this->ifExists, $this->optPrivileges, $this->optAclType, $this->grantIdent, $this->userList, $this->optIgnoreUnknownUser];
    }

    /**
     * Returns this value rebuilt around what the function answers for each value, keeping lexical fields and comments; itself when every answer is the value it was given.
     *
     * @param callable(\SqlSemantics\Statement\Element): \SqlSemantics\Statement\Element $replace
     */
    public function map(callable $replace): static
    {
        $mapped = [$this->replacement($this->ifExists, \SqlSemantics\Statement\Model\MySql\Role\IfExistsForm::class, $replace), $this->replacement($this->optPrivileges, \SqlSemantics\Statement\Model\MySql\Role\OptPrivilegesForm::class, $replace), $this->replacement($this->optAclType, \SqlSemantics\Statement\Model\MySql\Role\OptAclTypeForm::class, $replace), $this->replacement($this->grantIdent, \SqlSemantics\Statement\Model\MySql\Role\GrantIdentForm::class, $replace), $this->replacement($this->userList, \SqlSemantics\Statement\Model\MySql\Role\UserListForm::class, $replace), $this->replacement($this->optIgnoreUnknownUser, \SqlSemantics\Statement\Model\MySql\Role\OptIgnoreUnknownUserForm::class, $replace)];

        return $mapped === [$this->ifExists, $this->optPrivileges, $this->optAclType, $this->grantIdent, $this->userList, $this->optIgnoreUnknownUser] ? $this : new self($mapped[0], $mapped[1], $mapped[2], $mapped[3], $mapped[4], $mapped[5], $this->comments);
    }

    /**
     * Returns a copy with a new ifExists, preserving every other field.
     */
    public function withIfExists(\SqlSemantics\Statement\Model\MySql\Role\IfExistsForm $ifExists): self
    {
        return new self($ifExists, $this->optPrivileges, $this->optAclType, $this->grantIdent, $this->userList, $this->optIgnoreUnknownUser, $this->comments);
    }

    /**
     * Returns a copy with a new optPrivileges, preserving every other field.
     */
    public function withOptPrivileges(\SqlSemantics\Statement\Model\MySql\Role\OptPrivilegesForm $optPrivileges): self
    {
        return new self($this->ifExists, $optPrivileges, $this->optAclType, $this->grantIdent, $this->userList, $this->optIgnoreUnknownUser, $this->comments);
    }

    /**
     * Returns a copy with a new optAclType, preserving every other field.
     */
    public function withOptAclType(\SqlSemantics\Statement\Model\MySql\Role\OptAclTypeForm $optAclType): self
    {
        return new self($this->ifExists, $this->optPrivileges, $optAclType, $this->grantIdent, $this->userList, $this->optIgnoreUnknownUser, $this->comments);
    }

    /**
     * Returns a copy with a new grantIdent, preserving every other field.
     */
    public function withGrantIdent(\SqlSemantics\Statement\Model\MySql\Role\GrantIdentForm $grantIdent): self
    {
        return new self($this->ifExists, $this->optPrivileges, $this->optAclType, $grantIdent, $this->userList, $this->optIgnoreUnknownUser, $this->comments);
    }

    /**
     * Returns a copy with a new userList, preserving every other field.
     */
    public function withUserList(\SqlSemantics\Statement\Model\MySql\Role\UserListForm $userList): self
    {
        return new self($this->ifExists, $this->optPrivileges, $this->optAclType, $this->grantIdent, $userList, $this->optIgnoreUnknownUser, $this->comments);
    }

    /**
     * Returns a copy with a new optIgnoreUnknownUser, preserving every other field.
     */
    public function withOptIgnoreUnknownUser(\SqlSemantics\Statement\Model\MySql\Role\OptIgnoreUnknownUserForm $optIgnoreUnknownUser): self
    {
        return new self($this->ifExists, $this->optPrivileges, $this->optAclType, $this->grantIdent, $this->userList, $optIgnoreUnknownUser, $this->comments);
    }

    /**
     * Returns a copy with a new comments, preserving every other field.
     */
    public function withComments(\SqlSemantics\Statement\Comments $comments): self
    {
        return new self($this->ifExists, $this->optPrivileges, $this->optAclType, $this->grantIdent, $this->userList, $this->optIgnoreUnknownUser, $comments);
    }
}
