<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The revoke_command SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\RevokeCommandWithProxySymOnUserFromUserList_e9779a0c $value): string => (new \SqlSemantics\Statement\Statement($value))->toString();
 *     $write instanceof \Closure // => true
 */
final class RevokeCommandWithProxySymOnUserFromUserList_e9779a0c implements \SqlSemantics\Statement\Model\MySql\Role\RevokeCommandForm
{
    /**
     * Supplies the SQL values of this form.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\MySql\Role\UserForm $user,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\UserListForm $userList,
    ) {
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->append('PROXY');
        $writer->append('ON');
        $this->user->write($writer);
        $writer->append('FROM');
        $this->userList->write($writer);
    }
}
