<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The role_or_privilege SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\RoleOrPrivilegeWithRoleIdentOrTextIdentOrText_93b50921 $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class RoleOrPrivilegeWithRoleIdentOrTextIdentOrText_93b50921 implements \SqlSemantics\Statement\Model\MySql\Role\RoleOrPrivilegeForm, \SqlSemantics\Statement\Model\MySql\Role\RoleOrPrivilegeListForm
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form; comments are kept by the position of the symbol each precedes.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\MySql\Role\RoleIdentOrTextForm $roleIdentOrText,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\IdentOrTextForm $identOrText,
        public readonly \SqlSemantics\Statement\Comments $comments = new \SqlSemantics\Statement\Comments(),
    ) {
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($roleIdentOrText), 'The roleIdentOrText must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($identOrText), 'The identOrText must be a generated immutable SQL value.');
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->comments($this->comments, 0);
        $this->roleIdentOrText->write($writer);
        $writer->comments($this->comments, 1);
        $writer->append('@', prefix: true);
        $writer->comments($this->comments, 2);
        $this->identOrText->write($writer);
    }

    /**
     * Returns a copy with a new roleIdentOrText, preserving every other field.
     */
    public function withRoleIdentOrText(\SqlSemantics\Statement\Model\MySql\Role\RoleIdentOrTextForm $roleIdentOrText): self
    {
        return new self($roleIdentOrText, $this->identOrText, $this->comments);
    }

    /**
     * Returns a copy with a new identOrText, preserving every other field.
     */
    public function withIdentOrText(\SqlSemantics\Statement\Model\MySql\Role\IdentOrTextForm $identOrText): self
    {
        return new self($this->roleIdentOrText, $identOrText, $this->comments);
    }

    /**
     * Returns a copy with a new comments, preserving every other field.
     */
    public function withComments(\SqlSemantics\Statement\Comments $comments): self
    {
        return new self($this->roleIdentOrText, $this->identOrText, $comments);
    }
}
