<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The role_or_privilege SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\RoleOrPrivilegeWithRoleIdentOrTextIdentOrText_93b50921 $value): string => (new \SqlSemantics\Statement\Statement($value))->toString();
 *     $write instanceof \Closure // => true
 */
final class RoleOrPrivilegeWithRoleIdentOrTextIdentOrText_93b50921 implements \SqlSemantics\Statement\Model\MySql\Role\RoleOrPrivilegeForm, \SqlSemantics\Statement\Model\MySql\Role\RoleOrPrivilegeListForm
{
    /**
     * Supplies the SQL values of this form.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\MySql\Role\RoleIdentOrTextForm $roleIdentOrText,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\IdentOrTextForm $identOrText,
    ) {
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $this->roleIdentOrText->write($writer);
        $writer->append('@');
        $this->identOrText->write($writer);
    }
}
