<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The searched_when_clause SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\SearchedWhenClauseWithWhenSymExprThenSymSpProcStmts1_2c2671d1 $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class SearchedWhenClauseWithWhenSymExprThenSymSpProcStmts1_2c2671d1 implements \SqlSemantics\Statement\Model\MySql\Role\SearchedWhenClauseForm, \SqlSemantics\Statement\Model\MySql\Role\SearchedWhenClauseListForm
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\MySql\Role\ExprForm $expr,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\SpProcStmts1Form $spProcStmts1,
    ) {
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($expr), 'The expr must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($spProcStmts1), 'The spProcStmts1 must be a generated immutable SQL value.');
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->append('WHEN');
        $this->expr->write($writer);
        $writer->append('THEN');
        $this->spProcStmts1->write($writer);
    }

    /**
     * Returns a copy with a new expr, preserving every other field.
     */
    public function withExpr(\SqlSemantics\Statement\Model\MySql\Role\ExprForm $expr): self
    {
        return new self($expr, $this->spProcStmts1);
    }

    /**
     * Returns a copy with a new spProcStmts1, preserving every other field.
     */
    public function withSpProcStmts1(\SqlSemantics\Statement\Model\MySql\Role\SpProcStmts1Form $spProcStmts1): self
    {
        return new self($this->expr, $spProcStmts1);
    }
}
