<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The select_derived_union SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\SelectDerivedUnionWithSelectDerivedUnionUnionSymUnionOptionQuerySpecification_a25bd810 $value): string => (new \SqlSemantics\Statement\Statement($value))->toString();
 *     $write instanceof \Closure // => true
 */
final class SelectDerivedUnionWithSelectDerivedUnionUnionSymUnionOptionQuerySpecification_a25bd810 implements \SqlSemantics\Statement\Model\MySql\Role\SelectDerivedUnionForm
{
    /**
     * Supplies the SQL values of this form.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\MySql\Role\SelectDerivedUnionForm $selectDerivedUnion,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\UnionOptionForm $unionOption,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\QuerySpecificationForm $query,
    ) {
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $this->selectDerivedUnion->write($writer);
        $writer->append('UNION');
        $this->unionOption->write($writer);
        $this->query->write($writer);
    }
}
