<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The server_option SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\ServerOptionWithUserTextStringSys_0385ab07 $value): string => (new \SqlSemantics\Statement\Statement($value))->toString();
 *     $write instanceof \Closure // => true
 */
final class ServerOptionWithUserTextStringSys_0385ab07 implements \SqlSemantics\Statement\Model\MySql\Role\ServerOptionForm, \SqlSemantics\Statement\Model\MySql\Role\ServerOptionsListForm
{
    /**
     * Supplies the SQL values of this form.
     */
    public function __construct(
        public readonly string $user,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\TextStringSysForm $textStringSys,
    ) {
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->append($this->user);
        $this->textStringSys->write($writer);
    }
}
