<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The show_param SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\ShowParamWithEngineSymKnownStorageEnginesShowEngineParam_02bd4fd5 $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class ShowParamWithEngineSymKnownStorageEnginesShowEngineParam_02bd4fd5 implements \SqlSemantics\Statement\Model\MySql\Role\ShowParamForm
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\MySql\Role\KnownStorageEnginesForm $knownStorageEngines,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\ShowEngineParamForm $showEngineParam,
    ) {
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($knownStorageEngines), 'The knownStorageEngines must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($showEngineParam), 'The showEngineParam must be a generated immutable SQL value.');
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->append('ENGINE');
        $this->knownStorageEngines->write($writer);
        $this->showEngineParam->write($writer);
    }

    /**
     * Returns a copy with a new knownStorageEngines, preserving every other field.
     */
    public function withKnownStorageEngines(\SqlSemantics\Statement\Model\MySql\Role\KnownStorageEnginesForm $knownStorageEngines): self
    {
        return new self($knownStorageEngines, $this->showEngineParam);
    }

    /**
     * Returns a copy with a new showEngineParam, preserving every other field.
     */
    public function withShowEngineParam(\SqlSemantics\Statement\Model\MySql\Role\ShowEngineParamForm $showEngineParam): self
    {
        return new self($this->knownStorageEngines, $showEngineParam);
    }
}
