<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The show_param SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\ShowParamWithProfileSymOptProfileDefsOptProfileArgsOptLimitClauseInit_d011d256 $value): string => (new \SqlSemantics\Statement\Statement($value))->toString();
 *     $write instanceof \Closure // => true
 */
final class ShowParamWithProfileSymOptProfileDefsOptProfileArgsOptLimitClauseInit_d011d256 implements \SqlSemantics\Statement\Model\MySql\Role\ShowParamForm
{
    /**
     * Supplies the SQL values of this form.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\MySql\Role\OptProfileDefsForm $optProfileDefs,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\OptProfileArgsForm $optProfileArgs,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\OptLimitClauseInitForm $optLimitClauseInit,
    ) {
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->append('PROFILE');
        $this->optProfileDefs->write($writer);
        $this->optProfileArgs->write($writer);
        $this->optLimitClauseInit->write($writer);
    }
}
