<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The slave_until_opts SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\SlaveUntilOptsWithSqlAfterGtidsEqTextStringSys_47c5d09b $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class SlaveUntilOptsWithSqlAfterGtidsEqTextStringSys_47c5d09b implements \SqlSemantics\Statement\Model\MySql\Role\SlaveUntilOptsForm
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\MySql\Role\TextStringSysForm $textStringSys,
    ) {
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($textStringSys), 'The textStringSys must be a generated immutable SQL value.');
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->append('SQL_AFTER_GTIDS');
        $writer->append('=');
        $this->textStringSys->write($writer);
    }

    /**
     * Returns a copy with a new textStringSys, preserving every other field.
     */
    public function withTextStringSys(\SqlSemantics\Statement\Model\MySql\Role\TextStringSysForm $textStringSys): self
    {
        return new self($textStringSys);
    }
}
