<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The slave_user_name_opt SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\SlaveUserNameOptWithUserEqTextStringSys_7bc538eb $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class SlaveUserNameOptWithUserEqTextStringSys_7bc538eb implements \SqlSemantics\Statement\Model\MySql\Role\SlaveUserNameOptForm
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form.
     */
    public function __construct(
        public readonly string $user,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\TextStringSysForm $textStringSys,
    ) {
        $this->assertMatchesPattern($user, \SqlSemantics\Statement\Model\MySql\Contract\Contracts::SPELLINGS['USER'], 'The user must be a complete USER lexical spelling.');
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($textStringSys), 'The textStringSys must be a generated immutable SQL value.');
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->append($this->user);
        $writer->append('=');
        $this->textStringSys->write($writer);
    }

    /**
     * Returns a copy with a new user, preserving every other field.
     */
    public function withUser(string $user): self
    {
        return new self($user, $this->textStringSys);
    }

    /**
     * Returns a copy with a new textStringSys, preserving every other field.
     */
    public function withTextStringSys(\SqlSemantics\Statement\Model\MySql\Role\TextStringSysForm $textStringSys): self
    {
        return new self($this->user, $textStringSys);
    }
}
