<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The sp_hcond_list SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\SpHcondListWithSpHcondListSpHcondElement_e7ce5eea $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class SpHcondListWithSpHcondListSpHcondElement_e7ce5eea implements \SqlSemantics\Statement\Model\MySql\Role\SpHcondListForm
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form; comments are kept by the position of the symbol each precedes.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\MySql\Role\SpHcondListForm $spHcondList,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\SpHcondElementForm $spHcondElement,
        public readonly \SqlSemantics\Statement\Comments $comments = new \SqlSemantics\Statement\Comments(),
    ) {
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($spHcondList), 'The spHcondList must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($spHcondElement), 'The spHcondElement must be a generated immutable SQL value.');
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->comments($this->comments, 0);
        $this->spHcondList->write($writer);
        $writer->comments($this->comments, 1);
        $writer->append(',');
        $writer->comments($this->comments, 2);
        $this->spHcondElement->write($writer);
    }

    /**
     * Returns a copy with a new spHcondList, preserving every other field.
     */
    public function withSpHcondList(\SqlSemantics\Statement\Model\MySql\Role\SpHcondListForm $spHcondList): self
    {
        return new self($spHcondList, $this->spHcondElement, $this->comments);
    }

    /**
     * Returns a copy with a new spHcondElement, preserving every other field.
     */
    public function withSpHcondElement(\SqlSemantics\Statement\Model\MySql\Role\SpHcondElementForm $spHcondElement): self
    {
        return new self($this->spHcondList, $spHcondElement, $this->comments);
    }

    /**
     * Returns a copy with a new comments, preserving every other field.
     */
    public function withComments(\SqlSemantics\Statement\Comments $comments): self
    {
        return new self($this->spHcondList, $this->spHcondElement, $comments);
    }
}
