<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The sp_labeled_control SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\SpLabeledControlWithLabelIdentSpUnlabeledControlSpOptLabel_fd2eb6ec $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class SpLabeledControlWithLabelIdentSpUnlabeledControlSpOptLabel_fd2eb6ec implements \SqlSemantics\Statement\Model\MySql\Role\EvSqlStmtForm, \SqlSemantics\Statement\Model\MySql\Role\EvSqlStmtInnerForm, \SqlSemantics\Statement\Model\MySql\Role\SpLabeledControlForm, \SqlSemantics\Statement\Model\MySql\Role\SpProcStmtForm, \SqlSemantics\Statement\Model\MySql\Role\StoredRoutineBodyForm
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form; comments are kept by the position of the symbol each precedes.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\MySql\Role\LabelIdentForm $labelIdent,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\SpUnlabeledControlForm $spUnlabeledControl,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\SpOptLabelForm $spOptLabel,
        public readonly \SqlSemantics\Statement\Comments $comments = new \SqlSemantics\Statement\Comments(),
    ) {
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($labelIdent), 'The labelIdent must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($spUnlabeledControl), 'The spUnlabeledControl must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($spOptLabel), 'The spOptLabel must be a generated immutable SQL value.');
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->comments($this->comments, 0);
        $this->labelIdent->write($writer);
        $writer->comments($this->comments, 1);
        $writer->append(':');
        $writer->comments($this->comments, 2);
        $this->spUnlabeledControl->write($writer);
        $writer->comments($this->comments, 3);
        $this->spOptLabel->write($writer);
    }

    /**
     * Returns a copy with a new labelIdent, preserving every other field.
     */
    public function withLabelIdent(\SqlSemantics\Statement\Model\MySql\Role\LabelIdentForm $labelIdent): self
    {
        return new self($labelIdent, $this->spUnlabeledControl, $this->spOptLabel, $this->comments);
    }

    /**
     * Returns a copy with a new spUnlabeledControl, preserving every other field.
     */
    public function withSpUnlabeledControl(\SqlSemantics\Statement\Model\MySql\Role\SpUnlabeledControlForm $spUnlabeledControl): self
    {
        return new self($this->labelIdent, $spUnlabeledControl, $this->spOptLabel, $this->comments);
    }

    /**
     * Returns a copy with a new spOptLabel, preserving every other field.
     */
    public function withSpOptLabel(\SqlSemantics\Statement\Model\MySql\Role\SpOptLabelForm $spOptLabel): self
    {
        return new self($this->labelIdent, $this->spUnlabeledControl, $spOptLabel, $this->comments);
    }

    /**
     * Returns a copy with a new comments, preserving every other field.
     */
    public function withComments(\SqlSemantics\Statement\Comments $comments): self
    {
        return new self($this->labelIdent, $this->spUnlabeledControl, $this->spOptLabel, $comments);
    }
}
