<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The srs_attributes SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\SrsAttributesWithSrsAttributesOrganizationSymTextStringSysNonewlineIdentifiedSymByRealUlongl_b2332281 $value): string => (new \SqlSemantics\Statement\Statement($value))->toString();
 *     $write instanceof \Closure // => true
 */
final class SrsAttributesWithSrsAttributesOrganizationSymTextStringSysNonewlineIdentifiedSymByRealUlongl_b2332281 implements \SqlSemantics\Statement\Model\MySql\Role\SrsAttributesForm
{
    /**
     * Supplies the SQL values of this form.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\MySql\Role\SrsAttributesForm $srsAttributes,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\TextStringSysNonewlineForm $textStringSysNonewline,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\RealUlonglongNumForm $realUlonglongNum,
    ) {
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $this->srsAttributes->write($writer);
        $writer->append('ORGANIZATION');
        $this->textStringSysNonewline->write($writer);
        $writer->append('IDENTIFIED');
        $writer->append('BY');
        $this->realUlonglongNum->write($writer);
    }
}
