<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The standalone_alter_commands SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\StandaloneAlterCommandsWithExchangeSymPartitionSymIdentWithTableSymTableIdentOptWithValidation_d24efb2a $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class StandaloneAlterCommandsWithExchangeSymPartitionSymIdentWithTableSymTableIdentOptWithValidation_d24efb2a implements \SqlSemantics\Statement\Model\MySql\Role\AlterCommandsForm, \SqlSemantics\Statement\Model\MySql\Role\StandaloneAlterCommandsForm, \SqlSemantics\Statement\Model\MySql\Role\StandaloneAlterTableActionForm
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form; comments are kept by the position of the symbol each precedes.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\MySql\Role\IdentForm $ident,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\TableIdentForm $tableIdent,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\OptWithValidationForm $optWithValidation,
        public readonly \SqlSemantics\Statement\Comments $comments = new \SqlSemantics\Statement\Comments(),
    ) {
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($ident), 'The ident must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($tableIdent), 'The tableIdent must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($optWithValidation), 'The optWithValidation must be a generated immutable SQL value.');
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->comments($this->comments, 0);
        $writer->append('EXCHANGE');
        $writer->comments($this->comments, 1);
        $writer->append('PARTITION');
        $writer->comments($this->comments, 2);
        $this->ident->write($writer);
        $writer->comments($this->comments, 3);
        $writer->append('WITH');
        $writer->comments($this->comments, 4);
        $writer->append('TABLE');
        $writer->comments($this->comments, 5);
        $this->tableIdent->write($writer);
        $writer->comments($this->comments, 6);
        $this->optWithValidation->write($writer);
    }

    /**
     * Returns a copy with a new ident, preserving every other field.
     */
    public function withIdent(\SqlSemantics\Statement\Model\MySql\Role\IdentForm $ident): self
    {
        return new self($ident, $this->tableIdent, $this->optWithValidation, $this->comments);
    }

    /**
     * Returns a copy with a new tableIdent, preserving every other field.
     */
    public function withTableIdent(\SqlSemantics\Statement\Model\MySql\Role\TableIdentForm $tableIdent): self
    {
        return new self($this->ident, $tableIdent, $this->optWithValidation, $this->comments);
    }

    /**
     * Returns a copy with a new optWithValidation, preserving every other field.
     */
    public function withOptWithValidation(\SqlSemantics\Statement\Model\MySql\Role\OptWithValidationForm $optWithValidation): self
    {
        return new self($this->ident, $this->tableIdent, $optWithValidation, $this->comments);
    }

    /**
     * Returns a copy with a new comments, preserving every other field.
     */
    public function withComments(\SqlSemantics\Statement\Comments $comments): self
    {
        return new self($this->ident, $this->tableIdent, $this->optWithValidation, $comments);
    }
}
