<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The start_slave_opts SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\StartSlaveOptsWithSlaveUntilSlaveConnectionOptsOptChannel_c3a8db8c $value): string => (new \SqlSemantics\Statement\Statement($value))->toString();
 *     $write instanceof \Closure // => true
 */
final class StartSlaveOptsWithSlaveUntilSlaveConnectionOptsOptChannel_c3a8db8c implements \SqlSemantics\Statement\Model\MySql\Role\StartSlaveOptsForm
{
    /**
     * Supplies the SQL values of this form.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\MySql\Role\SlaveUntilForm $slaveUntil,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\SlaveConnectionOptsForm $slaveConnectionOpts,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\OptChannelForm $optChannel,
    ) {
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $this->slaveUntil->write($writer);
        $this->slaveConnectionOpts->write($writer);
        $this->optChannel->write($writer);
    }
}
