<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The table_constraint_def SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\TableConstraintDefWithOptConstraintNameConstraintKeyTypeOptIndexNameAndTypeKeyListWithExpressionO_1a05d953 $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class TableConstraintDefWithOptConstraintNameConstraintKeyTypeOptIndexNameAndTypeKeyListWithExpressionO_1a05d953 implements \SqlSemantics\Statement\Model\MySql\Role\TableConstraintDefForm, \SqlSemantics\Statement\Model\MySql\Role\TableElementForm, \SqlSemantics\Statement\Model\MySql\Role\TableElementListForm
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form; comments are kept by the position of the symbol each precedes.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\MySql\Role\OptConstraintNameForm $optConstraintName,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\ConstraintKeyTypeForm $constraintKeyType,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\OptIndexNameAndTypeForm $optIndexNameAndType,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\KeyListWithExpressionForm $keyListWithExpression,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\OptIndexOptionsForm $optIndexOptions,
        public readonly \SqlSemantics\Statement\Comments $comments = new \SqlSemantics\Statement\Comments(),
    ) {
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($optConstraintName), 'The optConstraintName must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($constraintKeyType), 'The constraintKeyType must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($optIndexNameAndType), 'The optIndexNameAndType must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($keyListWithExpression), 'The keyListWithExpression must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($optIndexOptions), 'The optIndexOptions must be a generated immutable SQL value.');
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->comments($this->comments, 0);
        $this->optConstraintName->write($writer);
        $writer->comments($this->comments, 1);
        $this->constraintKeyType->write($writer);
        $writer->comments($this->comments, 2);
        $this->optIndexNameAndType->write($writer);
        $writer->comments($this->comments, 3);
        $writer->append('(');
        $writer->comments($this->comments, 4);
        $this->keyListWithExpression->write($writer);
        $writer->comments($this->comments, 5);
        $writer->append(')');
        $writer->comments($this->comments, 6);
        $this->optIndexOptions->write($writer);
    }

    /**
     * Lists the values of this form, in writing order.
     *
     * @return list<\SqlSemantics\Statement\Element>
     */
    public function children(): array
    {
        return [$this->optConstraintName, $this->constraintKeyType, $this->optIndexNameAndType, $this->keyListWithExpression, $this->optIndexOptions];
    }

    /**
     * Returns this value rebuilt around what the function answers for each value, keeping lexical fields and comments; itself when every answer is the value it was given.
     *
     * @param callable(\SqlSemantics\Statement\Element): \SqlSemantics\Statement\Element $replace
     */
    public function map(callable $replace): static
    {
        $mapped = [$this->replacement($this->optConstraintName, \SqlSemantics\Statement\Model\MySql\Role\OptConstraintNameForm::class, $replace), $this->replacement($this->constraintKeyType, \SqlSemantics\Statement\Model\MySql\Role\ConstraintKeyTypeForm::class, $replace), $this->replacement($this->optIndexNameAndType, \SqlSemantics\Statement\Model\MySql\Role\OptIndexNameAndTypeForm::class, $replace), $this->replacement($this->keyListWithExpression, \SqlSemantics\Statement\Model\MySql\Role\KeyListWithExpressionForm::class, $replace), $this->replacement($this->optIndexOptions, \SqlSemantics\Statement\Model\MySql\Role\OptIndexOptionsForm::class, $replace)];

        return $mapped === [$this->optConstraintName, $this->constraintKeyType, $this->optIndexNameAndType, $this->keyListWithExpression, $this->optIndexOptions] ? $this : new self($mapped[0], $mapped[1], $mapped[2], $mapped[3], $mapped[4], $this->comments);
    }

    /**
     * Returns a copy with a new optConstraintName, preserving every other field.
     */
    public function withOptConstraintName(\SqlSemantics\Statement\Model\MySql\Role\OptConstraintNameForm $optConstraintName): self
    {
        return new self($optConstraintName, $this->constraintKeyType, $this->optIndexNameAndType, $this->keyListWithExpression, $this->optIndexOptions, $this->comments);
    }

    /**
     * Returns a copy with a new constraintKeyType, preserving every other field.
     */
    public function withConstraintKeyType(\SqlSemantics\Statement\Model\MySql\Role\ConstraintKeyTypeForm $constraintKeyType): self
    {
        return new self($this->optConstraintName, $constraintKeyType, $this->optIndexNameAndType, $this->keyListWithExpression, $this->optIndexOptions, $this->comments);
    }

    /**
     * Returns a copy with a new optIndexNameAndType, preserving every other field.
     */
    public function withOptIndexNameAndType(\SqlSemantics\Statement\Model\MySql\Role\OptIndexNameAndTypeForm $optIndexNameAndType): self
    {
        return new self($this->optConstraintName, $this->constraintKeyType, $optIndexNameAndType, $this->keyListWithExpression, $this->optIndexOptions, $this->comments);
    }

    /**
     * Returns a copy with a new keyListWithExpression, preserving every other field.
     */
    public function withKeyListWithExpression(\SqlSemantics\Statement\Model\MySql\Role\KeyListWithExpressionForm $keyListWithExpression): self
    {
        return new self($this->optConstraintName, $this->constraintKeyType, $this->optIndexNameAndType, $keyListWithExpression, $this->optIndexOptions, $this->comments);
    }

    /**
     * Returns a copy with a new optIndexOptions, preserving every other field.
     */
    public function withOptIndexOptions(\SqlSemantics\Statement\Model\MySql\Role\OptIndexOptionsForm $optIndexOptions): self
    {
        return new self($this->optConstraintName, $this->constraintKeyType, $this->optIndexNameAndType, $this->keyListWithExpression, $optIndexOptions, $this->comments);
    }

    /**
     * Returns a copy with a new comments, preserving every other field.
     */
    public function withComments(\SqlSemantics\Statement\Comments $comments): self
    {
        return new self($this->optConstraintName, $this->constraintKeyType, $this->optIndexNameAndType, $this->keyListWithExpression, $this->optIndexOptions, $comments);
    }
}
