<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The table_alias_ref_list SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\TableAliasRefListWithTableAliasRefListTableAliasRef_a6214510 $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class TableAliasRefListWithTableAliasRefListTableAliasRef_a6214510 implements \SqlSemantics\Statement\Model\MySql\Role\TableAliasRefListForm
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form; comments are kept by the position of the symbol each precedes.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\MySql\Role\TableAliasRefListForm $tableAliasRefList,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\TableAliasRefForm $tableAliasRef,
        public readonly \SqlSemantics\Statement\Comments $comments = new \SqlSemantics\Statement\Comments(),
    ) {
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($tableAliasRefList), 'The tableAliasRefList must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($tableAliasRef), 'The tableAliasRef must be a generated immutable SQL value.');
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->comments($this->comments, 0);
        $this->tableAliasRefList->write($writer);
        $writer->comments($this->comments, 1);
        $writer->append(',');
        $writer->comments($this->comments, 2);
        $this->tableAliasRef->write($writer);
    }

    /**
     * Lists the values of this form, in writing order.
     *
     * @return list<\SqlSemantics\Statement\Element>
     */
    public function children(): array
    {
        return [$this->tableAliasRefList, $this->tableAliasRef];
    }

    /**
     * Returns this value rebuilt around what the function answers for each value, keeping lexical fields and comments; itself when every answer is the value it was given.
     *
     * @param callable(\SqlSemantics\Statement\Element): \SqlSemantics\Statement\Element $replace
     */
    public function map(callable $replace): static
    {
        $mapped = [$this->replacement($this->tableAliasRefList, \SqlSemantics\Statement\Model\MySql\Role\TableAliasRefListForm::class, $replace), $this->replacement($this->tableAliasRef, \SqlSemantics\Statement\Model\MySql\Role\TableAliasRefForm::class, $replace)];

        return $mapped === [$this->tableAliasRefList, $this->tableAliasRef] ? $this : new self($mapped[0], $mapped[1], $this->comments);
    }

    /**
     * Returns a copy with a new tableAliasRefList, preserving every other field.
     */
    public function withTableAliasRefList(\SqlSemantics\Statement\Model\MySql\Role\TableAliasRefListForm $tableAliasRefList): self
    {
        return new self($tableAliasRefList, $this->tableAliasRef, $this->comments);
    }

    /**
     * Returns a copy with a new tableAliasRef, preserving every other field.
     */
    public function withTableAliasRef(\SqlSemantics\Statement\Model\MySql\Role\TableAliasRefForm $tableAliasRef): self
    {
        return new self($this->tableAliasRefList, $tableAliasRef, $this->comments);
    }

    /**
     * Returns a copy with a new comments, preserving every other field.
     */
    public function withComments(\SqlSemantics\Statement\Comments $comments): self
    {
        return new self($this->tableAliasRefList, $this->tableAliasRef, $comments);
    }
}
