<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The table_to_table SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\TableToTableWithTableIdentToSymTableIdent_3bc05998 $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class TableToTableWithTableIdentToSymTableIdent_3bc05998 implements \SqlSemantics\Statement\Model\MySql\Role\TableToTableForm, \SqlSemantics\Statement\Model\MySql\Role\TableToTableListForm
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form; comments are kept by the position of the symbol each precedes.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\MySql\Role\TableIdentForm $tableIdent,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\TableIdentForm $tableIdent2,
        public readonly \SqlSemantics\Statement\Comments $comments = new \SqlSemantics\Statement\Comments(),
    ) {
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($tableIdent), 'The tableIdent must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($tableIdent2), 'The tableIdent2 must be a generated immutable SQL value.');
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->comments($this->comments, 0);
        $this->tableIdent->write($writer);
        $writer->comments($this->comments, 1);
        $writer->append('TO');
        $writer->comments($this->comments, 2);
        $this->tableIdent2->write($writer);
    }

    /**
     * Returns a copy with a new tableIdent, preserving every other field.
     */
    public function withTableIdent(\SqlSemantics\Statement\Model\MySql\Role\TableIdentForm $tableIdent): self
    {
        return new self($tableIdent, $this->tableIdent2, $this->comments);
    }

    /**
     * Returns a copy with a new tableIdent2, preserving every other field.
     */
    public function withTableIdent2(\SqlSemantics\Statement\Model\MySql\Role\TableIdentForm $tableIdent2): self
    {
        return new self($this->tableIdent, $tableIdent2, $this->comments);
    }

    /**
     * Returns a copy with a new comments, preserving every other field.
     */
    public function withComments(\SqlSemantics\Statement\Comments $comments): self
    {
        return new self($this->tableIdent, $this->tableIdent2, $comments);
    }
}
