<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The text_or_password SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\TextOrPasswordWithOldPasswordTextString_607b6669 $value): string => (new \SqlSemantics\Statement\Statement($value))->toString();
 *     $write instanceof \Closure // => true
 */
final class TextOrPasswordWithOldPasswordTextString_607b6669 implements \SqlSemantics\Statement\Model\MySql\Role\TextOrPasswordForm
{
    /**
     * Supplies the SQL values of this form.
     */
    public function __construct(
        public readonly string $value,
    ) {
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->append('OLD_PASSWORD');
        $writer->append('(');
        $writer->append($this->value);
        $writer->append(')');
    }
}
