<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The text_or_password SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\TextOrPasswordWithOldPasswordTextString_607b6669 $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class TextOrPasswordWithOldPasswordTextString_607b6669 implements \SqlSemantics\Statement\Model\MySql\Role\TextOrPasswordForm
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form.
     */
    public function __construct(
        public readonly string $value,
    ) {
        $this->assertMatchesPattern($value, \SqlSemantics\Statement\Model\MySql\Contract\Contracts::SPELLINGS['TEXT_STRING'], 'The value must be a complete TEXT_STRING lexical spelling.');
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->append('OLD_PASSWORD');
        $writer->append('(');
        $writer->append($this->value);
        $writer->append(')');
    }

    /**
     * Returns a copy with a new value, preserving every other field.
     */
    public function withValue(string $value): self
    {
        return new self($value);
    }
}
