<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The trigger_tail SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\TriggerTailWithTriggerSymRememberNameSpNameTrgActionTimeTrgEventOnRememberNameTableIdentFo_fb660824 $value): string => (new \SqlSemantics\Statement\Statement($value))->toString();
 *     $write instanceof \Closure // => true
 */
final class TriggerTailWithTriggerSymRememberNameSpNameTrgActionTimeTrgEventOnRememberNameTableIdentFo_fb660824 implements \SqlSemantics\Statement\Model\MySql\Role\DefinerTailForm, \SqlSemantics\Statement\Model\MySql\Role\NoDefinerTailForm, \SqlSemantics\Statement\Model\MySql\Role\TriggerTailForm
{
    /**
     * Supplies the SQL values of this form.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\MySql\Role\RememberNameForm $rememberName,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\SpNameForm $spName,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\TrgActionTimeForm $trgActionTime,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\TrgEventForm $trgEvent,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\RememberNameForm $rememberName2,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\TableIdentForm $tableIdent,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\RememberNameForm $rememberName3,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\SpProcStmtForm $spProcStmt,
    ) {
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->append('TRIGGER');
        $this->rememberName->write($writer);
        $this->spName->write($writer);
        $this->trgActionTime->write($writer);
        $this->trgEvent->write($writer);
        $writer->append('ON');
        $this->rememberName2->write($writer);
        $this->tableIdent->write($writer);
        $writer->append('FOR');
        $this->rememberName3->write($writer);
        $writer->append('EACH');
        $writer->append('ROW');
        $this->spProcStmt->write($writer);
    }
}
