<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The ulong_num SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\UlongNumWithHexNum_e036cef7 $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class UlongNumWithHexNum_e036cef7 implements \SqlSemantics\Statement\Model\MySql\Role\IgnoreServerIdForm, \SqlSemantics\Statement\Model\MySql\Role\IgnoreServerIdListForm, \SqlSemantics\Statement\Model\MySql\Role\SpCondForm, \SqlSemantics\Statement\Model\MySql\Role\SpHcondForm, \SqlSemantics\Statement\Model\MySql\Role\SpHcondElementForm, \SqlSemantics\Statement\Model\MySql\Role\SpHcondListForm, \SqlSemantics\Statement\Model\MySql\Role\TernaryOptionForm, \SqlSemantics\Statement\Model\MySql\Role\UlongNumForm
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form; comments are kept by the position of the symbol each precedes.
     */
    public function __construct(
        public readonly string $hexNum,
        public readonly \SqlSemantics\Statement\Comments $comments = new \SqlSemantics\Statement\Comments(),
    ) {
        $this->assertMatchesPattern($hexNum, \SqlSemantics\Statement\Model\MySql\Contract\Contracts::SPELLINGS['HEX_NUM'], 'The hexNum must be a complete HEX_NUM lexical spelling.');
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->comments($this->comments, 0);
        $writer->append($this->hexNum);
    }

    /**
     * Returns a copy with a new hexNum, preserving every other field.
     */
    public function withHexNum(string $hexNum): self
    {
        return new self($hexNum, $this->comments);
    }

    /**
     * Returns a copy with a new comments, preserving every other field.
     */
    public function withComments(\SqlSemantics\Statement\Comments $comments): self
    {
        return new self($this->hexNum, $comments);
    }
}
