<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The values_row_list SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\ValuesRowListWithValuesRowListRowValueExplicit_734510f7 $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class ValuesRowListWithValuesRowListRowValueExplicit_734510f7 implements \SqlSemantics\Statement\Model\MySql\Role\ValuesRowListForm
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\MySql\Role\ValuesRowListForm $valuesRowList,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\RowValueExplicitForm $rowValueExplicit,
    ) {
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($valuesRowList), 'The valuesRowList must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($rowValueExplicit), 'The rowValueExplicit must be a generated immutable SQL value.');
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $this->valuesRowList->write($writer);
        $writer->append(',');
        $this->rowValueExplicit->write($writer);
    }

    /**
     * Returns a copy with a new valuesRowList, preserving every other field.
     */
    public function withValuesRowList(\SqlSemantics\Statement\Model\MySql\Role\ValuesRowListForm $valuesRowList): self
    {
        return new self($valuesRowList, $this->rowValueExplicit);
    }

    /**
     * Returns a copy with a new rowValueExplicit, preserving every other field.
     */
    public function withRowValueExplicit(\SqlSemantics\Statement\Model\MySql\Role\RowValueExplicitForm $rowValueExplicit): self
    {
        return new self($this->valuesRowList, $rowValueExplicit);
    }
}
