<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The view_or_trigger_or_sp_or_event SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\ViewOrTriggerOrSpOrEventWithNoDefinerInitLexCreateInfoNoDefinerTail_fbd4fea0 $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class ViewOrTriggerOrSpOrEventWithNoDefinerInitLexCreateInfoNoDefinerTail_fbd4fea0 implements \SqlSemantics\Statement\Model\MySql\Role\ViewOrTriggerOrSpOrEventForm
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form; comments are kept by the position of the symbol each precedes.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\MySql\Role\NoDefinerForm $noDefiner,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\InitLexCreateInfoForm $initLexCreateInfo,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\NoDefinerTailForm $noDefinerTail,
        public readonly \SqlSemantics\Statement\Comments $comments = new \SqlSemantics\Statement\Comments(),
    ) {
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($noDefiner), 'The noDefiner must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($initLexCreateInfo), 'The initLexCreateInfo must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($noDefinerTail), 'The noDefinerTail must be a generated immutable SQL value.');
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->comments($this->comments, 0);
        $this->noDefiner->write($writer);
        $writer->comments($this->comments, 1);
        $this->initLexCreateInfo->write($writer);
        $writer->comments($this->comments, 2);
        $this->noDefinerTail->write($writer);
    }

    /**
     * Returns a copy with a new noDefiner, preserving every other field.
     */
    public function withNoDefiner(\SqlSemantics\Statement\Model\MySql\Role\NoDefinerForm $noDefiner): self
    {
        return new self($noDefiner, $this->initLexCreateInfo, $this->noDefinerTail, $this->comments);
    }

    /**
     * Returns a copy with a new initLexCreateInfo, preserving every other field.
     */
    public function withInitLexCreateInfo(\SqlSemantics\Statement\Model\MySql\Role\InitLexCreateInfoForm $initLexCreateInfo): self
    {
        return new self($this->noDefiner, $initLexCreateInfo, $this->noDefinerTail, $this->comments);
    }

    /**
     * Returns a copy with a new noDefinerTail, preserving every other field.
     */
    public function withNoDefinerTail(\SqlSemantics\Statement\Model\MySql\Role\NoDefinerTailForm $noDefinerTail): self
    {
        return new self($this->noDefiner, $this->initLexCreateInfo, $noDefinerTail, $this->comments);
    }

    /**
     * Returns a copy with a new comments, preserving every other field.
     */
    public function withComments(\SqlSemantics\Statement\Comments $comments): self
    {
        return new self($this->noDefiner, $this->initLexCreateInfo, $this->noDefinerTail, $comments);
    }
}
