<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The view_or_trigger_or_sp_or_event SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\ViewOrTriggerOrSpOrEventWithDefinerInitLexCreateInfoDefinerTail_a6c43105 $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class ViewOrTriggerOrSpOrEventWithDefinerInitLexCreateInfoDefinerTail_a6c43105 implements \SqlSemantics\Statement\Model\MySql\Role\ViewOrTriggerOrSpOrEventForm
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form; comments are kept by the position of the symbol each precedes.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\MySql\Role\DefinerForm $definer,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\InitLexCreateInfoForm $initLexCreateInfo,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\DefinerTailForm $definerTail,
        public readonly \SqlSemantics\Statement\Comments $comments = new \SqlSemantics\Statement\Comments(),
    ) {
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($definer), 'The definer must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($initLexCreateInfo), 'The initLexCreateInfo must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\MySql\Contract\Contracts::contains($definerTail), 'The definerTail must be a generated immutable SQL value.');
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->comments($this->comments, 0);
        $this->definer->write($writer);
        $writer->comments($this->comments, 1);
        $this->initLexCreateInfo->write($writer);
        $writer->comments($this->comments, 2);
        $this->definerTail->write($writer);
    }

    /**
     * Lists the values of this form, in writing order.
     *
     * @return list<\SqlSemantics\Statement\Element>
     */
    public function children(): array
    {
        return [$this->definer, $this->initLexCreateInfo, $this->definerTail];
    }

    /**
     * Returns this value rebuilt around what the function answers for each value, keeping lexical fields and comments; itself when every answer is the value it was given.
     *
     * @param callable(\SqlSemantics\Statement\Element): \SqlSemantics\Statement\Element $replace
     */
    public function map(callable $replace): static
    {
        $mapped = [$this->replacement($this->definer, \SqlSemantics\Statement\Model\MySql\Role\DefinerForm::class, $replace), $this->replacement($this->initLexCreateInfo, \SqlSemantics\Statement\Model\MySql\Role\InitLexCreateInfoForm::class, $replace), $this->replacement($this->definerTail, \SqlSemantics\Statement\Model\MySql\Role\DefinerTailForm::class, $replace)];

        return $mapped === [$this->definer, $this->initLexCreateInfo, $this->definerTail] ? $this : new self($mapped[0], $mapped[1], $mapped[2], $this->comments);
    }

    /**
     * Returns a copy with a new definer, preserving every other field.
     */
    public function withDefiner(\SqlSemantics\Statement\Model\MySql\Role\DefinerForm $definer): self
    {
        return new self($definer, $this->initLexCreateInfo, $this->definerTail, $this->comments);
    }

    /**
     * Returns a copy with a new initLexCreateInfo, preserving every other field.
     */
    public function withInitLexCreateInfo(\SqlSemantics\Statement\Model\MySql\Role\InitLexCreateInfoForm $initLexCreateInfo): self
    {
        return new self($this->definer, $initLexCreateInfo, $this->definerTail, $this->comments);
    }

    /**
     * Returns a copy with a new definerTail, preserving every other field.
     */
    public function withDefinerTail(\SqlSemantics\Statement\Model\MySql\Role\DefinerTailForm $definerTail): self
    {
        return new self($this->definer, $this->initLexCreateInfo, $definerTail, $this->comments);
    }

    /**
     * Returns a copy with a new comments, preserving every other field.
     */
    public function withComments(\SqlSemantics\Statement\Comments $comments): self
    {
        return new self($this->definer, $this->initLexCreateInfo, $this->definerTail, $comments);
    }
}
