<?php

declare(strict_types=1);

namespace Tests\Unit\Binding\Schema;

use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\Attributes\Medium;
use PHPUnit\Framework\TestCase;
use SqlSemantics\Binder;
use SqlSemantics\Dialect;
use SqlSemantics\SchemaBuilder;

#[CoversClass(\SqlSemantics\Binding\Schema\ColumnBinder::class)]
#[Medium]
final class ColumnBinderTest extends TestCase
{
    public function testBindClassifiesMySqlColumnAttributes(): void
    {
        $table = (new SchemaBuilder(Dialect::MySql))->build("CREATE TABLE t(name VARCHAR(20) COLLATE utf8mb4_bin COMMENT 'n' INVISIBLE COLUMN_FORMAT FIXED STORAGE MEMORY SRID 4326, n INT UNSIGNED ZEROFILL VISIBLE)")->tables[0];
        $attributes = $table->columns[0]->attributes;
        self::assertSame(['utf8mb4_bin'], $attributes->collation?->parts);
        self::assertSame('n', $attributes->comment);
        self::assertFalse($attributes->visible);
        self::assertSame(\SqlSemantics\Schema\Column\Format::Fixed, $attributes->format);
        self::assertSame(\SqlSemantics\Schema\Column\Storage::Memory, $attributes->storage);
        self::assertSame(4326, $attributes->spatialReferenceId);
        self::assertTrue($table->columns[1]->attributes->zeroFill);
        self::assertTrue($table->columns[1]->attributes->visible);
        self::assertNull($attributes->characterSet);
    }

    public function testBindLeavesEncodingToTypesThatOwnIt(): void
    {
        $table = (new SchemaBuilder(Dialect::MySql))->build("CREATE TABLE t(a VARCHAR(10) CHARACTER SET latin1 BINARY, b ENUM('x') CHARACTER SET utf8mb4)")->tables[0];
        self::assertNull($table->columns[0]->attributes->characterSet);
        self::assertFalse($table->columns[0]->attributes->binary);
        self::assertNull($table->columns[1]->attributes->characterSet);
        self::assertInstanceOf(\SqlSemantics\Type\Identity\StringStorage::class, $table->columns[0]->type->identity);
        self::assertSame('latin1', $table->columns[0]->type->identity->characterSet);
        self::assertTrue($table->columns[0]->type->identity->binary);
    }

    public function testBindDiagnosesAnUnresolvableDefaultReference(): void
    {
        $binder = new Binder((new SchemaBuilder(Dialect::MySql))->build());
        $this->expectException(\SqlSemantics\SemanticException::class);
        $binder->bind('CREATE TABLE t(a INT, b INT AS (missing + 1))');
    }

    public function testGenerationSelectsOneValueSourceForm(): void
    {
        $table = (new SchemaBuilder(Dialect::MySql))->build('CREATE TABLE t(id INT AUTO_INCREMENT PRIMARY KEY, total INT AS (id * 2) STORED, n INT DEFAULT 1, ts TIMESTAMP)')->tables[0];
        self::assertInstanceOf(\SqlSemantics\Schema\Column\AutoIncrementColumn::class, $table->columns[0]->generation);
        self::assertInstanceOf(\SqlSemantics\Schema\Column\ComputedColumn::class, $table->columns[1]->generation);
        self::assertSame(\SqlSemantics\Schema\Column\GeneratedStorage::Stored, $table->columns[1]->generation->storage);
        self::assertSame('(`id` * 2)', $table->columns[1]->generation->expression->structure()->toString());
        self::assertInstanceOf(\SqlSemantics\Schema\Column\SuppliedColumn::class, $table->columns[2]->generation);
        self::assertSame('1', $table->columns[2]->generation->default?->spelling());
        self::assertInstanceOf(\SqlSemantics\Schema\Column\SuppliedColumn::class, $table->columns[3]->generation);
        self::assertNull($table->columns[3]->generation->default);
    }

    #[\PHPUnit\Framework\Attributes\TestWith(['CREATE TABLE t(id INTEGER PRIMARY KEY DESC AUTOINCREMENT)'])]
    #[\PHPUnit\Framework\Attributes\TestWith(['CREATE TABLE t(id TEXT PRIMARY KEY AUTOINCREMENT)'])]
    #[\PHPUnit\Framework\Attributes\TestWith(['CREATE TABLE t(id INT PRIMARY KEY AUTOINCREMENT)'])]
    public function testGenerationRejectsASqliteAutoincrementWithoutARowidAlias(string $sql): void
    {
        $binder = new Binder((new SchemaBuilder(Dialect::Sqlite))->build());
        $this->expectException(\SqlSemantics\InvalidSql::class);
        $this->expectExceptionMessage(\SqlSemantics\Model\Validation\InputViolation::AutoIncrementKey->message());
        $binder->bind($sql);
    }

    public function testGenerationBindsIdentityModeAndOnUpdateExpressions(): void
    {
        $identity = (new SchemaBuilder(Dialect::PostgreSql))->build('CREATE TABLE t(id INTEGER GENERATED BY DEFAULT AS IDENTITY, n INTEGER GENERATED ALWAYS AS (1) STORED)')->tables[0];
        self::assertInstanceOf(\SqlSemantics\Schema\Column\IdentityColumn::class, $identity->columns[0]->generation);
        self::assertSame(\SqlSemantics\Schema\Column\IdentityMode::ByDefault, $identity->columns[0]->generation->mode);
        self::assertInstanceOf(\SqlSemantics\Schema\Column\ComputedColumn::class, $identity->columns[1]->generation);
        self::assertSame(\SqlSemantics\Schema\Column\GeneratedStorage::Stored, $identity->columns[1]->generation->storage);
        $timestamps = (new SchemaBuilder(Dialect::MySql))->build('CREATE TABLE t(ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)')->tables[0];
        self::assertInstanceOf(\SqlSemantics\Schema\Column\SuppliedColumn::class, $timestamps->columns[0]->generation);
        self::assertSame('CURRENT_TIMESTAMP', $timestamps->columns[0]->generation->onUpdate?->spelling());
        $virtual = (new SchemaBuilder(Dialect::Sqlite))->build('CREATE TABLE t(a INTEGER, b INTEGER GENERATED ALWAYS AS (a * 2))')->tables[0];
        self::assertInstanceOf(\SqlSemantics\Schema\Column\ComputedColumn::class, $virtual->columns[1]->generation);
        self::assertSame(\SqlSemantics\Schema\Column\GeneratedStorage::Virtual, $virtual->columns[1]->generation->storage);
    }


    public function testBindRejectsAnUnknownPostgreSqlStorageStrategy(): void
    {
        $this->expectException(\SqlSemantics\InvalidSql::class);
        $this->expectExceptionMessage(\SqlSemantics\Model\Validation\InputViolation::ColumnStorage->message());
        (new Binder((new SchemaBuilder(Dialect::PostgreSql))->build()))->bind('CREATE TABLE t(c text STORAGE foo)');
    }


    public function testNullConflictReadsTheLastNotNullResolution(): void
    {
        $binder = new Binder((new SchemaBuilder(Dialect::Sqlite))->build('CREATE TABLE t(id INTEGER)'));
        $table = (new SchemaBuilder(Dialect::Sqlite))->build('CREATE TABLE u (a INT NOT NULL ON CONFLICT IGNORE, b INT NOT NULL ON CONFLICT FAIL NOT NULL ON CONFLICT REPLACE, c INT NULL ON CONFLICT ABORT, d INT NOT NULL)')->tables[0];
        $response = \SqlSemantics\Model\Write\Policy\ConstraintResponse::class;
        self::assertSame([$response::Ignore, $response::Replace, $response::Default, $response::Default], array_column($table->columns, 'nullConflict'));
        $expected = 'ALTER TABLE "t" ADD COLUMN "c" "int" NOT NULL ON CONFLICT IGNORE DEFAULT 1';
        self::assertSame($expected, (new \SqlSemantics\SimpleSerializer())->serialize($binder->bind('ALTER TABLE t ADD COLUMN c INT NOT NULL ON CONFLICT IGNORE DEFAULT 1')));
        self::assertSame($expected, (new \SqlSemantics\SimpleSerializer())->serialize($binder->bind($expected)));
    }

    public function testBindKeepsNotSecondaryOnAnAddedColumn(): void
    {
        $statement = (new Binder((new SchemaBuilder(Dialect::MySql))->build('CREATE TABLE t(a INT)')))->bind('ALTER TABLE t ADD COLUMN c INT NOT SECONDARY');
        self::assertSame('ALTER TABLE `t` ADD COLUMN `c` integer NOT SECONDARY', (new \SqlSemantics\SimpleSerializer())->serialize($statement));
    }

    public function testBindRecordsAWrittenNullOnlyForANullableColumn(): void
    {
        $columns = (new SchemaBuilder(Dialect::MySql, grammarVersion: 'mysql-5.6.51'))->build('CREATE TABLE t (a INT NULL, b INT, c INT NULL NOT NULL, e INT NULL PRIMARY KEY)')->tables[0]->columns;
        self::assertSame([true, false, false, false], array_map(static fn (\SqlSemantics\Schema\ColumnDefinition $column): bool => $column->nullDeclared, $columns));
    }

    #[\PHPUnit\Framework\Attributes\TestWith(['CREATE TABLE t (a serial DEFAULT 5)'])]
    #[\PHPUnit\Framework\Attributes\TestWith(['CREATE TABLE t (a bigserial GENERATED BY DEFAULT AS IDENTITY)'])]
    #[\PHPUnit\Framework\Attributes\TestWith(['CREATE TABLE t (a smallserial GENERATED ALWAYS AS (1) STORED)'])]
    public function testGenerationRejectsAnotherValueSourceOnASerialColumn(string $sql): void
    {
        $binder = new Binder((new SchemaBuilder(Dialect::PostgreSql, grammarVersion: 'pg-17.2'))->build());
        $this->expectException(\SqlSemantics\InvalidSql::class);
        $this->expectExceptionMessage(\SqlSemantics\Model\Validation\InputViolation::SerialDefault->message());
        $binder->bind($sql);
    }

    public function testGenerationBindsASerialColumnToItsSequence(): void
    {
        $column = (new SchemaBuilder(Dialect::PostgreSql, grammarVersion: 'pg-17.2'))->build('CREATE TABLE t (a serial8)')->tables[0]->columns[0];
        self::assertInstanceOf(\SqlSemantics\Schema\Column\SerialColumn::class, $column->generation);
        self::assertSame('bigint', $column->type->name);
    }

    public function testGenerationBindsTheMySqlSerialDefaultValueAttribute(): void
    {
        $column = (new SchemaBuilder(Dialect::MySql, grammarVersion: 'mysql-8.4.7'))->build('CREATE TABLE t (a INT SERIAL DEFAULT VALUE)')->tables[0]->columns[0];
        self::assertInstanceOf(\SqlSemantics\Schema\Column\AutoIncrementColumn::class, $column->generation);
        self::assertTrue($column->generation->serialDefault);
    }
}
