<?php

declare(strict_types=1);

namespace SqlSemantics\Platform\PostgreSql\Lowering\Leaf\Keyword;

/**
 * The productions of `bare_label_keyword`: the keywords that may be used as an output name without AS.
 *
 * Rule: PG-KEYWORD-NAME-001 (table). The list is the union of the shipped
 * grammar releases; each production reads one keyword terminal as a name.
 * Source: https://www.postgresql.org/docs/17/sql-keywords-appendix.html.
 * Status: Implemented.
 *
 * @visibility SqlSemantics
 */
final class BareLabelKeywords
{
    /**
     * The production signatures, one per keyword.
     */
    public const SIGNATURES = [
        'bare_label_keyword: ABORT_P', 'bare_label_keyword: ABSENT', 'bare_label_keyword: ABSOLUTE_P', 'bare_label_keyword: ACCESS',
        'bare_label_keyword: ACTION', 'bare_label_keyword: ADD_P', 'bare_label_keyword: ADMIN', 'bare_label_keyword: AFTER',
        'bare_label_keyword: AGGREGATE', 'bare_label_keyword: ALL', 'bare_label_keyword: ALSO', 'bare_label_keyword: ALTER',
        'bare_label_keyword: ALWAYS', 'bare_label_keyword: ANALYSE', 'bare_label_keyword: ANALYZE', 'bare_label_keyword: AND',
        'bare_label_keyword: ANY', 'bare_label_keyword: ASC', 'bare_label_keyword: ASENSITIVE', 'bare_label_keyword: ASSERTION',
        'bare_label_keyword: ASSIGNMENT', 'bare_label_keyword: ASYMMETRIC', 'bare_label_keyword: AT', 'bare_label_keyword: ATOMIC',
        'bare_label_keyword: ATTACH', 'bare_label_keyword: ATTRIBUTE', 'bare_label_keyword: AUTHORIZATION', 'bare_label_keyword: BACKWARD',
        'bare_label_keyword: BEFORE', 'bare_label_keyword: BEGIN_P', 'bare_label_keyword: BETWEEN', 'bare_label_keyword: BIGINT',
        'bare_label_keyword: BINARY', 'bare_label_keyword: BIT', 'bare_label_keyword: BOOLEAN_P', 'bare_label_keyword: BOTH',
        'bare_label_keyword: BREADTH', 'bare_label_keyword: BY', 'bare_label_keyword: CACHE', 'bare_label_keyword: CALL',
        'bare_label_keyword: CALLED', 'bare_label_keyword: CASCADE', 'bare_label_keyword: CASCADED', 'bare_label_keyword: CASE',
        'bare_label_keyword: CAST', 'bare_label_keyword: CATALOG_P', 'bare_label_keyword: CHAIN', 'bare_label_keyword: CHARACTERISTICS',
        'bare_label_keyword: CHECK', 'bare_label_keyword: CHECKPOINT', 'bare_label_keyword: CLASS', 'bare_label_keyword: CLOSE',
        'bare_label_keyword: CLUSTER', 'bare_label_keyword: COALESCE', 'bare_label_keyword: COLLATE', 'bare_label_keyword: COLLATION',
        'bare_label_keyword: COLUMN', 'bare_label_keyword: COLUMNS', 'bare_label_keyword: COMMENT', 'bare_label_keyword: COMMENTS',
        'bare_label_keyword: COMMIT', 'bare_label_keyword: COMMITTED', 'bare_label_keyword: COMPRESSION', 'bare_label_keyword: CONCURRENTLY',
        'bare_label_keyword: CONDITIONAL', 'bare_label_keyword: CONFIGURATION', 'bare_label_keyword: CONFLICT', 'bare_label_keyword: CONNECTION',
        'bare_label_keyword: CONSTRAINT', 'bare_label_keyword: CONSTRAINTS', 'bare_label_keyword: CONTENT_P', 'bare_label_keyword: CONTINUE_P',
        'bare_label_keyword: CONVERSION_P', 'bare_label_keyword: COPY', 'bare_label_keyword: COST', 'bare_label_keyword: CROSS',
        'bare_label_keyword: CSV', 'bare_label_keyword: CUBE', 'bare_label_keyword: CURRENT_CATALOG', 'bare_label_keyword: CURRENT_DATE',
        'bare_label_keyword: CURRENT_P', 'bare_label_keyword: CURRENT_ROLE', 'bare_label_keyword: CURRENT_SCHEMA', 'bare_label_keyword: CURRENT_TIME',
        'bare_label_keyword: CURRENT_TIMESTAMP', 'bare_label_keyword: CURRENT_USER', 'bare_label_keyword: CURSOR', 'bare_label_keyword: CYCLE',
        'bare_label_keyword: DATABASE', 'bare_label_keyword: DATA_P', 'bare_label_keyword: DEALLOCATE', 'bare_label_keyword: DEC',
        'bare_label_keyword: DECIMAL_P', 'bare_label_keyword: DECLARE', 'bare_label_keyword: DEFAULT', 'bare_label_keyword: DEFAULTS',
        'bare_label_keyword: DEFERRABLE', 'bare_label_keyword: DEFERRED', 'bare_label_keyword: DEFINER', 'bare_label_keyword: DELETE_P',
        'bare_label_keyword: DELIMITER', 'bare_label_keyword: DELIMITERS', 'bare_label_keyword: DEPENDS', 'bare_label_keyword: DEPTH',
        'bare_label_keyword: DESC', 'bare_label_keyword: DETACH', 'bare_label_keyword: DICTIONARY', 'bare_label_keyword: DISABLE_P',
        'bare_label_keyword: DISCARD', 'bare_label_keyword: DISTINCT', 'bare_label_keyword: DO', 'bare_label_keyword: DOCUMENT_P',
        'bare_label_keyword: DOMAIN_P', 'bare_label_keyword: DOUBLE_P', 'bare_label_keyword: DROP', 'bare_label_keyword: EACH',
        'bare_label_keyword: ELSE', 'bare_label_keyword: EMPTY_P', 'bare_label_keyword: ENABLE_P', 'bare_label_keyword: ENCODING',
        'bare_label_keyword: ENCRYPTED', 'bare_label_keyword: END_P', 'bare_label_keyword: ENUM_P', 'bare_label_keyword: ERROR_P',
        'bare_label_keyword: ESCAPE', 'bare_label_keyword: EVENT', 'bare_label_keyword: EXCLUDE', 'bare_label_keyword: EXCLUDING',
        'bare_label_keyword: EXCLUSIVE', 'bare_label_keyword: EXECUTE', 'bare_label_keyword: EXISTS', 'bare_label_keyword: EXPLAIN',
        'bare_label_keyword: EXPRESSION', 'bare_label_keyword: EXTENSION', 'bare_label_keyword: EXTERNAL', 'bare_label_keyword: EXTRACT',
        'bare_label_keyword: FALSE_P', 'bare_label_keyword: FAMILY', 'bare_label_keyword: FINALIZE', 'bare_label_keyword: FIRST_P',
        'bare_label_keyword: FLOAT_P', 'bare_label_keyword: FOLLOWING', 'bare_label_keyword: FORCE', 'bare_label_keyword: FOREIGN',
        'bare_label_keyword: FORMAT', 'bare_label_keyword: FORWARD', 'bare_label_keyword: FREEZE', 'bare_label_keyword: FULL',
        'bare_label_keyword: FUNCTION', 'bare_label_keyword: FUNCTIONS', 'bare_label_keyword: GENERATED', 'bare_label_keyword: GLOBAL',
        'bare_label_keyword: GRANTED', 'bare_label_keyword: GREATEST', 'bare_label_keyword: GROUPING', 'bare_label_keyword: GROUPS',
        'bare_label_keyword: HANDLER', 'bare_label_keyword: HEADER_P', 'bare_label_keyword: HOLD', 'bare_label_keyword: IDENTITY_P',
        'bare_label_keyword: IF_P', 'bare_label_keyword: ILIKE', 'bare_label_keyword: IMMEDIATE', 'bare_label_keyword: IMMUTABLE',
        'bare_label_keyword: IMPLICIT_P', 'bare_label_keyword: IMPORT_P', 'bare_label_keyword: INCLUDE', 'bare_label_keyword: INCLUDING',
        'bare_label_keyword: INCREMENT', 'bare_label_keyword: INDENT', 'bare_label_keyword: INDEX', 'bare_label_keyword: INDEXES',
        'bare_label_keyword: INHERIT', 'bare_label_keyword: INHERITS', 'bare_label_keyword: INITIALLY', 'bare_label_keyword: INLINE_P',
        'bare_label_keyword: INNER_P', 'bare_label_keyword: INOUT', 'bare_label_keyword: INPUT_P', 'bare_label_keyword: INSENSITIVE',
        'bare_label_keyword: INSERT', 'bare_label_keyword: INSTEAD', 'bare_label_keyword: INTEGER', 'bare_label_keyword: INTERVAL',
        'bare_label_keyword: INT_P', 'bare_label_keyword: INVOKER', 'bare_label_keyword: IN_P', 'bare_label_keyword: IS',
        'bare_label_keyword: ISOLATION', 'bare_label_keyword: JOIN', 'bare_label_keyword: JSON', 'bare_label_keyword: JSON_ARRAY',
        'bare_label_keyword: JSON_ARRAYAGG', 'bare_label_keyword: JSON_EXISTS', 'bare_label_keyword: JSON_OBJECT', 'bare_label_keyword: JSON_OBJECTAGG',
        'bare_label_keyword: JSON_QUERY', 'bare_label_keyword: JSON_SCALAR', 'bare_label_keyword: JSON_SERIALIZE', 'bare_label_keyword: JSON_TABLE',
        'bare_label_keyword: JSON_VALUE', 'bare_label_keyword: KEEP', 'bare_label_keyword: KEY', 'bare_label_keyword: KEYS',
        'bare_label_keyword: LABEL', 'bare_label_keyword: LANGUAGE', 'bare_label_keyword: LARGE_P', 'bare_label_keyword: LAST_P',
        'bare_label_keyword: LATERAL_P', 'bare_label_keyword: LEADING', 'bare_label_keyword: LEAKPROOF', 'bare_label_keyword: LEAST',
        'bare_label_keyword: LEFT', 'bare_label_keyword: LEVEL', 'bare_label_keyword: LIKE', 'bare_label_keyword: LISTEN',
        'bare_label_keyword: LOAD', 'bare_label_keyword: LOCAL', 'bare_label_keyword: LOCALTIME', 'bare_label_keyword: LOCALTIMESTAMP',
        'bare_label_keyword: LOCATION', 'bare_label_keyword: LOCKED', 'bare_label_keyword: LOCK_P', 'bare_label_keyword: LOGGED',
        'bare_label_keyword: MAPPING', 'bare_label_keyword: MATCH', 'bare_label_keyword: MATCHED', 'bare_label_keyword: MATERIALIZED',
        'bare_label_keyword: MAXVALUE', 'bare_label_keyword: MERGE', 'bare_label_keyword: MERGE_ACTION', 'bare_label_keyword: METHOD',
        'bare_label_keyword: MINVALUE', 'bare_label_keyword: MODE', 'bare_label_keyword: MOVE', 'bare_label_keyword: NAMES',
        'bare_label_keyword: NAME_P', 'bare_label_keyword: NATIONAL', 'bare_label_keyword: NATURAL', 'bare_label_keyword: NCHAR',
        'bare_label_keyword: NESTED', 'bare_label_keyword: NEW', 'bare_label_keyword: NEXT', 'bare_label_keyword: NFC',
        'bare_label_keyword: NFD', 'bare_label_keyword: NFKC', 'bare_label_keyword: NFKD', 'bare_label_keyword: NO',
        'bare_label_keyword: NONE', 'bare_label_keyword: NORMALIZE', 'bare_label_keyword: NORMALIZED', 'bare_label_keyword: NOT',
        'bare_label_keyword: NOTHING', 'bare_label_keyword: NOTIFY', 'bare_label_keyword: NOWAIT', 'bare_label_keyword: NULLIF',
        'bare_label_keyword: NULLS_P', 'bare_label_keyword: NULL_P', 'bare_label_keyword: NUMERIC', 'bare_label_keyword: OBJECT_P',
        'bare_label_keyword: OF', 'bare_label_keyword: OFF', 'bare_label_keyword: OIDS', 'bare_label_keyword: OLD',
        'bare_label_keyword: OMIT', 'bare_label_keyword: ONLY', 'bare_label_keyword: OPERATOR', 'bare_label_keyword: OPTION',
        'bare_label_keyword: OPTIONS', 'bare_label_keyword: OR', 'bare_label_keyword: ORDINALITY', 'bare_label_keyword: OTHERS',
        'bare_label_keyword: OUTER_P', 'bare_label_keyword: OUT_P', 'bare_label_keyword: OVERLAY', 'bare_label_keyword: OVERRIDING',
        'bare_label_keyword: OWNED', 'bare_label_keyword: OWNER', 'bare_label_keyword: PARALLEL', 'bare_label_keyword: PARAMETER',
        'bare_label_keyword: PARSER', 'bare_label_keyword: PARTIAL', 'bare_label_keyword: PARTITION', 'bare_label_keyword: PASSING',
        'bare_label_keyword: PASSWORD', 'bare_label_keyword: PATH', 'bare_label_keyword: PLACING', 'bare_label_keyword: PLAN',
        'bare_label_keyword: PLANS', 'bare_label_keyword: POLICY', 'bare_label_keyword: POSITION', 'bare_label_keyword: PRECEDING',
        'bare_label_keyword: PREPARE', 'bare_label_keyword: PREPARED', 'bare_label_keyword: PRESERVE', 'bare_label_keyword: PRIMARY',
        'bare_label_keyword: PRIOR', 'bare_label_keyword: PRIVILEGES', 'bare_label_keyword: PROCEDURAL', 'bare_label_keyword: PROCEDURE',
        'bare_label_keyword: PROCEDURES', 'bare_label_keyword: PROGRAM', 'bare_label_keyword: PUBLICATION', 'bare_label_keyword: QUOTE',
        'bare_label_keyword: QUOTES', 'bare_label_keyword: RANGE', 'bare_label_keyword: READ', 'bare_label_keyword: REAL',
        'bare_label_keyword: REASSIGN', 'bare_label_keyword: RECHECK', 'bare_label_keyword: RECURSIVE', 'bare_label_keyword: REFERENCES',
        'bare_label_keyword: REFERENCING', 'bare_label_keyword: REFRESH', 'bare_label_keyword: REF_P', 'bare_label_keyword: REINDEX',
        'bare_label_keyword: RELATIVE_P', 'bare_label_keyword: RELEASE', 'bare_label_keyword: RENAME', 'bare_label_keyword: REPEATABLE',
        'bare_label_keyword: REPLACE', 'bare_label_keyword: REPLICA', 'bare_label_keyword: RESET', 'bare_label_keyword: RESTART',
        'bare_label_keyword: RESTRICT', 'bare_label_keyword: RETURN', 'bare_label_keyword: RETURNS', 'bare_label_keyword: REVOKE',
        'bare_label_keyword: RIGHT', 'bare_label_keyword: ROLE', 'bare_label_keyword: ROLLBACK', 'bare_label_keyword: ROLLUP',
        'bare_label_keyword: ROUTINE', 'bare_label_keyword: ROUTINES', 'bare_label_keyword: ROW', 'bare_label_keyword: ROWS',
        'bare_label_keyword: RULE', 'bare_label_keyword: SAVEPOINT', 'bare_label_keyword: SCALAR', 'bare_label_keyword: SCHEMA',
        'bare_label_keyword: SCHEMAS', 'bare_label_keyword: SCROLL', 'bare_label_keyword: SEARCH', 'bare_label_keyword: SECURITY',
        'bare_label_keyword: SELECT', 'bare_label_keyword: SEQUENCE', 'bare_label_keyword: SEQUENCES', 'bare_label_keyword: SERIALIZABLE',
        'bare_label_keyword: SERVER', 'bare_label_keyword: SESSION', 'bare_label_keyword: SESSION_USER', 'bare_label_keyword: SET',
        'bare_label_keyword: SETOF', 'bare_label_keyword: SETS', 'bare_label_keyword: SHARE', 'bare_label_keyword: SHOW',
        'bare_label_keyword: SIMILAR', 'bare_label_keyword: SIMPLE', 'bare_label_keyword: SKIP', 'bare_label_keyword: SMALLINT',
        'bare_label_keyword: SNAPSHOT', 'bare_label_keyword: SOME', 'bare_label_keyword: SOURCE', 'bare_label_keyword: SQL_P',
        'bare_label_keyword: STABLE', 'bare_label_keyword: STANDALONE_P', 'bare_label_keyword: START', 'bare_label_keyword: STATEMENT',
        'bare_label_keyword: STATISTICS', 'bare_label_keyword: STDIN', 'bare_label_keyword: STDOUT', 'bare_label_keyword: STORAGE',
        'bare_label_keyword: STORED', 'bare_label_keyword: STRICT_P', 'bare_label_keyword: STRING_P', 'bare_label_keyword: STRIP_P',
        'bare_label_keyword: SUBSCRIPTION', 'bare_label_keyword: SUBSTRING', 'bare_label_keyword: SUPPORT', 'bare_label_keyword: SYMMETRIC',
        'bare_label_keyword: SYSID', 'bare_label_keyword: SYSTEM_P', 'bare_label_keyword: SYSTEM_USER', 'bare_label_keyword: TABLE',
        'bare_label_keyword: TABLES', 'bare_label_keyword: TABLESAMPLE', 'bare_label_keyword: TABLESPACE', 'bare_label_keyword: TARGET',
        'bare_label_keyword: TEMP', 'bare_label_keyword: TEMPLATE', 'bare_label_keyword: TEMPORARY', 'bare_label_keyword: TEXT_P',
        'bare_label_keyword: THEN', 'bare_label_keyword: TIES', 'bare_label_keyword: TIME', 'bare_label_keyword: TIMESTAMP',
        'bare_label_keyword: TRAILING', 'bare_label_keyword: TRANSACTION', 'bare_label_keyword: TRANSFORM', 'bare_label_keyword: TREAT',
        'bare_label_keyword: TRIGGER', 'bare_label_keyword: TRIM', 'bare_label_keyword: TRUE_P', 'bare_label_keyword: TRUNCATE',
        'bare_label_keyword: TRUSTED', 'bare_label_keyword: TYPES_P', 'bare_label_keyword: TYPE_P', 'bare_label_keyword: UESCAPE',
        'bare_label_keyword: UNBOUNDED', 'bare_label_keyword: UNCOMMITTED', 'bare_label_keyword: UNCONDITIONAL', 'bare_label_keyword: UNENCRYPTED',
        'bare_label_keyword: UNIQUE', 'bare_label_keyword: UNKNOWN', 'bare_label_keyword: UNLISTEN', 'bare_label_keyword: UNLOGGED',
        'bare_label_keyword: UNTIL', 'bare_label_keyword: UPDATE', 'bare_label_keyword: USER', 'bare_label_keyword: USING',
        'bare_label_keyword: VACUUM', 'bare_label_keyword: VALID', 'bare_label_keyword: VALIDATE', 'bare_label_keyword: VALIDATOR',
        'bare_label_keyword: VALUES', 'bare_label_keyword: VALUE_P', 'bare_label_keyword: VARCHAR', 'bare_label_keyword: VARIADIC',
        'bare_label_keyword: VERBOSE', 'bare_label_keyword: VERSION_P', 'bare_label_keyword: VIEW', 'bare_label_keyword: VIEWS',
        'bare_label_keyword: VOLATILE', 'bare_label_keyword: WHEN', 'bare_label_keyword: WHITESPACE_P', 'bare_label_keyword: WORK',
        'bare_label_keyword: WRAPPER', 'bare_label_keyword: WRITE', 'bare_label_keyword: XMLATTRIBUTES', 'bare_label_keyword: XMLCONCAT',
        'bare_label_keyword: XMLELEMENT', 'bare_label_keyword: XMLEXISTS', 'bare_label_keyword: XMLFOREST', 'bare_label_keyword: XMLNAMESPACES',
        'bare_label_keyword: XMLPARSE', 'bare_label_keyword: XMLPI', 'bare_label_keyword: XMLROOT', 'bare_label_keyword: XMLSERIALIZE',
        'bare_label_keyword: XMLTABLE', 'bare_label_keyword: XML_P', 'bare_label_keyword: YES_P', 'bare_label_keyword: ZONE',
    ];
}
