<?php

declare(strict_types=1);

namespace Tests\Unit\Model\Definition\Relation\Identity;

use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\Attributes\Medium;
use PHPUnit\Framework\TestCase;
use SqlSemantics\Binder;
use SqlSemantics\Dialect;
use SqlSemantics\Model\Definition\Relation;
use SqlSemantics\Model\Statement\Definition\PostgreSql\Relation\AlterRelationStatement;
use SqlSemantics\Model\Validation\InvalidStructure;
use SqlSemantics\SchemaBuilder;

#[CoversClass(Relation\Identity\AddColumnIdentity::class)]
#[Medium]
final class AddColumnIdentityTest extends TestCase
{
    public function testBindsAndWritesTheAction(): void
    {
        $statement = (new Binder((new SchemaBuilder(Dialect::PostgreSql))->build('CREATE TABLE t(id INTEGER)')))->bind('ALTER TABLE t ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 10 NO CYCLE AS smallint SEQUENCE NAME app.s OWNED BY t.id CACHE 5 LOGGED)', strict: false);
        self::assertInstanceOf(AlterRelationStatement::class, $statement);
        self::assertInstanceOf(Relation\Identity\AddColumnIdentity::class, $statement->actions[0]);
        self::assertSame(\SqlSemantics\Schema\Column\IdentityMode::ByDefault, $statement->actions[0]->mode);
        self::assertCount(7, $statement->actions[0]->options);
        self::assertSame(Relation\Identity\SequenceFlag::NoCycle, $statement->actions[0]->options[1]);
        self::assertSame(Relation\Identity\SequenceFlag::Logged, $statement->actions[0]->options[6]);
        self::assertSame('ALTER TABLE "t" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY(START WITH 10 NO CYCLE AS smallint SEQUENCE NAME "app"."s" OWNED BY "t"."id" CACHE 5 LOGGED)', $statement->toString());
    }

    public function testRejectsAnEmptyColumn(): void
    {
        $this->expectException(InvalidStructure::class);
        new Relation\Identity\AddColumnIdentity('', \SqlSemantics\Schema\Column\IdentityMode::Always);
    }
}
