<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\PostgreSql\Value;

/**
 * The aggregate_with_argtypes SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\PostgreSql\Value\AggregateWithArgtypesWithFuncNameAggrArgs_32a3351c $value): string => (new \SqlSemantics\Statement\Statement($value))->toString();
 *     $write instanceof \Closure // => true
 */
final class AggregateWithArgtypesWithFuncNameAggrArgs_32a3351c implements \SqlSemantics\Statement\Model\PostgreSql\Role\AggregateWithArgtypesForm, \SqlSemantics\Statement\Model\PostgreSql\Role\AggregateWithArgtypesListForm
{
    /**
     * Supplies the SQL values of this form.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\FuncNameForm $funcName,
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\AggrArgsForm $aggrArgs,
    ) {
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $this->funcName->write($writer);
        $this->aggrArgs->write($writer);
    }
}
