<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\PostgreSql\Value;

/**
 * The AlterTableStmt SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\PostgreSql\Value\AlterTableStmtWithAlterMaterializedViewAllInPTablespaceNameSetTablespaceNameOptNowait_16fd871d $value): string => (new \SqlSemantics\Statement\Statement($value))->toString();
 *     $write instanceof \Closure // => true
 */
final class AlterTableStmtWithAlterMaterializedViewAllInPTablespaceNameSetTablespaceNameOptNowait_16fd871d implements \SqlSemantics\Statement\Model\PostgreSql\Role\AlterTableStmtForm, \SqlSemantics\Statement\Model\PostgreSql\Role\ParseToplevelForm, \SqlSemantics\Statement\Model\PostgreSql\Role\RoutineBodyStmtForm, \SqlSemantics\Statement\Model\PostgreSql\Role\StmtForm, \SqlSemantics\Statement\Model\PostgreSql\Role\StmtmultiForm, \SqlSemantics\Statement\Model\PostgreSql\Role\ToplevelStmtForm
{
    /**
     * Supplies the SQL values of this form.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\NameForm $name,
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\NameForm $name2,
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\OptNowaitForm $optNowait,
    ) {
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->append('ALTER');
        $writer->append('MATERIALIZED');
        $writer->append('VIEW');
        $writer->append('ALL');
        $writer->append('IN');
        $writer->append('TABLESPACE');
        $this->name->write($writer);
        $writer->append('SET');
        $writer->append('TABLESPACE');
        $this->name2->write($writer);
        $this->optNowait->write($writer);
    }
}
