<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\PostgreSql\Value;

/**
 * The AlterRoleSetStmt SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\PostgreSql\Value\AlterRoleSetStmtWithAlterRoleAllOptInDatabaseSetResetClause_c3599227 $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class AlterRoleSetStmtWithAlterRoleAllOptInDatabaseSetResetClause_c3599227 implements \SqlSemantics\Statement\Model\PostgreSql\Role\AlterRoleSetStmtForm, \SqlSemantics\Statement\Model\PostgreSql\Role\ParseToplevelForm, \SqlSemantics\Statement\Model\PostgreSql\Role\RoutineBodyStmtForm, \SqlSemantics\Statement\Model\PostgreSql\Role\StmtForm, \SqlSemantics\Statement\Model\PostgreSql\Role\StmtmultiForm, \SqlSemantics\Statement\Model\PostgreSql\Role\ToplevelStmtForm, \SqlSemantics\Statement\Command
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\OptInDatabaseForm $optInDatabase,
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\SetResetClauseForm $setResetClause,
    ) {
        $this->assert(\SqlSemantics\Statement\Model\PostgreSql\Contract\Contracts::contains($optInDatabase), 'The optInDatabase must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\PostgreSql\Contract\Contracts::contains($setResetClause), 'The setResetClause must be a generated immutable SQL value.');
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->append('ALTER');
        $writer->append('ROLE');
        $writer->append('ALL');
        $this->optInDatabase->write($writer);
        $this->setResetClause->write($writer);
    }

    /**
     * Returns a copy with a new optInDatabase, preserving every other field.
     */
    public function withOptInDatabase(\SqlSemantics\Statement\Model\PostgreSql\Role\OptInDatabaseForm $optInDatabase): self
    {
        return new self($optInDatabase, $this->setResetClause);
    }

    /**
     * Returns a copy with a new setResetClause, preserving every other field.
     */
    public function withSetResetClause(\SqlSemantics\Statement\Model\PostgreSql\Role\SetResetClauseForm $setResetClause): self
    {
        return new self($this->optInDatabase, $setResetClause);
    }
}
