<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\PostgreSql\Value;

/**
 * The alter_table_cmd SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\PostgreSql\Value\AlterTableCmdWithSetAccessMethodSetAccessMethodName_f7df5d5c $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class AlterTableCmdWithSetAccessMethodSetAccessMethodName_f7df5d5c implements \SqlSemantics\Statement\Model\PostgreSql\Role\AlterTableCmdForm, \SqlSemantics\Statement\Model\PostgreSql\Role\AlterTableCmdsForm
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\SetAccessMethodNameForm $setAccessMethodName,
    ) {
        $this->assert(\SqlSemantics\Statement\Model\PostgreSql\Contract\Contracts::contains($setAccessMethodName), 'The setAccessMethodName must be a generated immutable SQL value.');
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->append('SET');
        $writer->append('ACCESS');
        $writer->append('METHOD');
        $this->setAccessMethodName->write($writer);
    }

    /**
     * Returns a copy with a new setAccessMethodName, preserving every other field.
     */
    public function withSetAccessMethodName(\SqlSemantics\Statement\Model\PostgreSql\Role\SetAccessMethodNameForm $setAccessMethodName): self
    {
        return new self($setAccessMethodName);
    }
}
