<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\PostgreSql\Value;

/**
 * The AlterDomainStmt SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\PostgreSql\Value\AlterDomainStmtWithAlterDomainPAnyNameAlterColumnDefault_753474c3 $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class AlterDomainStmtWithAlterDomainPAnyNameAlterColumnDefault_753474c3 implements \SqlSemantics\Statement\Model\PostgreSql\Role\AlterDomainStmtForm, \SqlSemantics\Statement\Model\PostgreSql\Role\ParseToplevelForm, \SqlSemantics\Statement\Model\PostgreSql\Role\RoutineBodyStmtForm, \SqlSemantics\Statement\Model\PostgreSql\Role\StmtForm, \SqlSemantics\Statement\Model\PostgreSql\Role\StmtmultiForm, \SqlSemantics\Statement\Model\PostgreSql\Role\ToplevelStmtForm, \SqlSemantics\Statement\Command
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\AnyNameForm $anyName,
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\AlterColumnDefaultForm $alterColumnDefault,
    ) {
        $this->assert(\SqlSemantics\Statement\Model\PostgreSql\Contract\Contracts::contains($anyName), 'The anyName must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\PostgreSql\Contract\Contracts::contains($alterColumnDefault), 'The alterColumnDefault must be a generated immutable SQL value.');
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->append('ALTER');
        $writer->append('DOMAIN');
        $this->anyName->write($writer);
        $this->alterColumnDefault->write($writer);
    }

    /**
     * Returns a copy with a new anyName, preserving every other field.
     */
    public function withAnyName(\SqlSemantics\Statement\Model\PostgreSql\Role\AnyNameForm $anyName): self
    {
        return new self($anyName, $this->alterColumnDefault);
    }

    /**
     * Returns a copy with a new alterColumnDefault, preserving every other field.
     */
    public function withAlterColumnDefault(\SqlSemantics\Statement\Model\PostgreSql\Role\AlterColumnDefaultForm $alterColumnDefault): self
    {
        return new self($this->anyName, $alterColumnDefault);
    }
}
