<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\PostgreSql\Value;

/**
 * The ColConstraintElem SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\PostgreSql\Value\ColConstraintElemWithGeneratedGeneratedWhenAsAExprStored_3ea03aaa $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class ColConstraintElemWithGeneratedGeneratedWhenAsAExprStored_3ea03aaa implements \SqlSemantics\Statement\Model\PostgreSql\Role\ColConstraintForm, \SqlSemantics\Statement\Model\PostgreSql\Role\ColConstraintElemForm
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\GeneratedWhenForm $generatedWhen,
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\AExprForm $aExpr,
    ) {
        $this->assert(\SqlSemantics\Statement\Model\PostgreSql\Contract\Contracts::contains($generatedWhen), 'The generatedWhen must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\PostgreSql\Contract\Contracts::contains($aExpr), 'The aExpr must be a generated immutable SQL value.');
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->append('GENERATED');
        $this->generatedWhen->write($writer);
        $writer->append('AS');
        $writer->append('(');
        $this->aExpr->write($writer);
        $writer->append(')');
        $writer->append('STORED');
    }

    /**
     * Returns a copy with a new generatedWhen, preserving every other field.
     */
    public function withGeneratedWhen(\SqlSemantics\Statement\Model\PostgreSql\Role\GeneratedWhenForm $generatedWhen): self
    {
        return new self($generatedWhen, $this->aExpr);
    }

    /**
     * Returns a copy with a new aExpr, preserving every other field.
     */
    public function withAExpr(\SqlSemantics\Statement\Model\PostgreSql\Role\AExprForm $aExpr): self
    {
        return new self($this->generatedWhen, $aExpr);
    }
}
