<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\PostgreSql\Value;

/**
 * The columnOptions SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\PostgreSql\Value\ColumnOptionsWithColIdWithOptionsColQualList_b06c9148 $value): string => (new \SqlSemantics\Statement\Statement($value))->toString();
 *     $write instanceof \Closure // => true
 */
final class ColumnOptionsWithColIdWithOptionsColQualList_b06c9148 implements \SqlSemantics\Statement\Model\PostgreSql\Role\TypedTableElementForm, \SqlSemantics\Statement\Model\PostgreSql\Role\TypedTableElementListForm, \SqlSemantics\Statement\Model\PostgreSql\Role\ColumnOptionsForm
{
    /**
     * Supplies the SQL values of this form.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\ColIdForm $colId,
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\ColQualListForm $colQualList,
    ) {
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $this->colId->write($writer);
        $writer->append('WITH');
        $writer->append('OPTIONS');
        $this->colQualList->write($writer);
    }
}
