<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\PostgreSql\Value;

/**
 * The CommentStmt SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\PostgreSql\Value\CommentStmtWithCommentOnLargePObjectPNumericOnlyIsCommentText_53bf8c5f $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class CommentStmtWithCommentOnLargePObjectPNumericOnlyIsCommentText_53bf8c5f implements \SqlSemantics\Statement\Model\PostgreSql\Role\CommentStmtForm, \SqlSemantics\Statement\Model\PostgreSql\Role\ParseToplevelForm, \SqlSemantics\Statement\Model\PostgreSql\Role\RoutineBodyStmtForm, \SqlSemantics\Statement\Model\PostgreSql\Role\StmtForm, \SqlSemantics\Statement\Model\PostgreSql\Role\StmtmultiForm, \SqlSemantics\Statement\Model\PostgreSql\Role\ToplevelStmtForm, \SqlSemantics\Statement\Command
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form; comments are kept by the position of the symbol each precedes.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\NumericOnlyForm $numericOnly,
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\CommentTextForm $commentText,
        public readonly \SqlSemantics\Statement\Comments $comments = new \SqlSemantics\Statement\Comments(),
    ) {
        $this->assert(\SqlSemantics\Statement\Model\PostgreSql\Contract\Contracts::contains($numericOnly), 'The numericOnly must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\PostgreSql\Contract\Contracts::contains($commentText), 'The commentText must be a generated immutable SQL value.');
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->comments($this->comments, 0);
        $writer->append('COMMENT');
        $writer->comments($this->comments, 1);
        $writer->append('ON');
        $writer->comments($this->comments, 2);
        $writer->append('LARGE');
        $writer->comments($this->comments, 3);
        $writer->append('OBJECT');
        $writer->comments($this->comments, 4);
        $this->numericOnly->write($writer);
        $writer->comments($this->comments, 5);
        $writer->append('IS');
        $writer->comments($this->comments, 6);
        $this->commentText->write($writer);
    }

    /**
     * Returns a copy with a new numericOnly, preserving every other field.
     */
    public function withNumericOnly(\SqlSemantics\Statement\Model\PostgreSql\Role\NumericOnlyForm $numericOnly): self
    {
        return new self($numericOnly, $this->commentText, $this->comments);
    }

    /**
     * Returns a copy with a new commentText, preserving every other field.
     */
    public function withCommentText(\SqlSemantics\Statement\Model\PostgreSql\Role\CommentTextForm $commentText): self
    {
        return new self($this->numericOnly, $commentText, $this->comments);
    }

    /**
     * Returns a copy with a new comments, preserving every other field.
     */
    public function withComments(\SqlSemantics\Statement\Comments $comments): self
    {
        return new self($this->numericOnly, $this->commentText, $comments);
    }
}
