<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\PostgreSql\Value;

/**
 * The CopyStmt SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\PostgreSql\Value\CopyStmtWithCopyOptBinaryQualifiedNameOptColumnListCopyFromOptProgramCopyFileNameCopyDe_2b21c137 $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class CopyStmtWithCopyOptBinaryQualifiedNameOptColumnListCopyFromOptProgramCopyFileNameCopyDe_2b21c137 implements \SqlSemantics\Statement\Model\PostgreSql\Role\CopyStmtForm, \SqlSemantics\Statement\Model\PostgreSql\Role\ParseToplevelForm, \SqlSemantics\Statement\Model\PostgreSql\Role\RoutineBodyStmtForm, \SqlSemantics\Statement\Model\PostgreSql\Role\StmtForm, \SqlSemantics\Statement\Model\PostgreSql\Role\StmtmultiForm, \SqlSemantics\Statement\Model\PostgreSql\Role\ToplevelStmtForm, \SqlSemantics\Statement\Command
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\OptBinaryForm $optBinary,
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\QualifiedNameForm $qualifiedName,
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\OptColumnListForm $optColumnList,
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\CopyFromForm $copyFrom,
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\OptProgramForm $optProgram,
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\CopyFileNameForm $copyFileName,
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\CopyDelimiterForm $copyDelimiter,
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\OptWithForm $optWith,
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\CopyOptionsForm $copyOptions,
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\WhereClauseForm $where,
    ) {
        $this->assert(\SqlSemantics\Statement\Model\PostgreSql\Contract\Contracts::contains($optBinary), 'The optBinary must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\PostgreSql\Contract\Contracts::contains($qualifiedName), 'The qualifiedName must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\PostgreSql\Contract\Contracts::contains($optColumnList), 'The optColumnList must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\PostgreSql\Contract\Contracts::contains($copyFrom), 'The copyFrom must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\PostgreSql\Contract\Contracts::contains($optProgram), 'The optProgram must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\PostgreSql\Contract\Contracts::contains($copyFileName), 'The copyFileName must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\PostgreSql\Contract\Contracts::contains($copyDelimiter), 'The copyDelimiter must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\PostgreSql\Contract\Contracts::contains($optWith), 'The optWith must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\PostgreSql\Contract\Contracts::contains($copyOptions), 'The copyOptions must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\PostgreSql\Contract\Contracts::contains($where), 'The where must be a generated immutable SQL value.');
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->append('COPY');
        $this->optBinary->write($writer);
        $this->qualifiedName->write($writer);
        $this->optColumnList->write($writer);
        $this->copyFrom->write($writer);
        $this->optProgram->write($writer);
        $this->copyFileName->write($writer);
        $this->copyDelimiter->write($writer);
        $this->optWith->write($writer);
        $this->copyOptions->write($writer);
        $this->where->write($writer);
    }

    /**
     * Returns a copy with a new optBinary, preserving every other field.
     */
    public function withOptBinary(\SqlSemantics\Statement\Model\PostgreSql\Role\OptBinaryForm $optBinary): self
    {
        return new self($optBinary, $this->qualifiedName, $this->optColumnList, $this->copyFrom, $this->optProgram, $this->copyFileName, $this->copyDelimiter, $this->optWith, $this->copyOptions, $this->where);
    }

    /**
     * Returns a copy with a new qualifiedName, preserving every other field.
     */
    public function withQualifiedName(\SqlSemantics\Statement\Model\PostgreSql\Role\QualifiedNameForm $qualifiedName): self
    {
        return new self($this->optBinary, $qualifiedName, $this->optColumnList, $this->copyFrom, $this->optProgram, $this->copyFileName, $this->copyDelimiter, $this->optWith, $this->copyOptions, $this->where);
    }

    /**
     * Returns a copy with a new optColumnList, preserving every other field.
     */
    public function withOptColumnList(\SqlSemantics\Statement\Model\PostgreSql\Role\OptColumnListForm $optColumnList): self
    {
        return new self($this->optBinary, $this->qualifiedName, $optColumnList, $this->copyFrom, $this->optProgram, $this->copyFileName, $this->copyDelimiter, $this->optWith, $this->copyOptions, $this->where);
    }

    /**
     * Returns a copy with a new copyFrom, preserving every other field.
     */
    public function withCopyFrom(\SqlSemantics\Statement\Model\PostgreSql\Role\CopyFromForm $copyFrom): self
    {
        return new self($this->optBinary, $this->qualifiedName, $this->optColumnList, $copyFrom, $this->optProgram, $this->copyFileName, $this->copyDelimiter, $this->optWith, $this->copyOptions, $this->where);
    }

    /**
     * Returns a copy with a new optProgram, preserving every other field.
     */
    public function withOptProgram(\SqlSemantics\Statement\Model\PostgreSql\Role\OptProgramForm $optProgram): self
    {
        return new self($this->optBinary, $this->qualifiedName, $this->optColumnList, $this->copyFrom, $optProgram, $this->copyFileName, $this->copyDelimiter, $this->optWith, $this->copyOptions, $this->where);
    }

    /**
     * Returns a copy with a new copyFileName, preserving every other field.
     */
    public function withCopyFileName(\SqlSemantics\Statement\Model\PostgreSql\Role\CopyFileNameForm $copyFileName): self
    {
        return new self($this->optBinary, $this->qualifiedName, $this->optColumnList, $this->copyFrom, $this->optProgram, $copyFileName, $this->copyDelimiter, $this->optWith, $this->copyOptions, $this->where);
    }

    /**
     * Returns a copy with a new copyDelimiter, preserving every other field.
     */
    public function withCopyDelimiter(\SqlSemantics\Statement\Model\PostgreSql\Role\CopyDelimiterForm $copyDelimiter): self
    {
        return new self($this->optBinary, $this->qualifiedName, $this->optColumnList, $this->copyFrom, $this->optProgram, $this->copyFileName, $copyDelimiter, $this->optWith, $this->copyOptions, $this->where);
    }

    /**
     * Returns a copy with a new optWith, preserving every other field.
     */
    public function withOptWith(\SqlSemantics\Statement\Model\PostgreSql\Role\OptWithForm $optWith): self
    {
        return new self($this->optBinary, $this->qualifiedName, $this->optColumnList, $this->copyFrom, $this->optProgram, $this->copyFileName, $this->copyDelimiter, $optWith, $this->copyOptions, $this->where);
    }

    /**
     * Returns a copy with a new copyOptions, preserving every other field.
     */
    public function withCopyOptions(\SqlSemantics\Statement\Model\PostgreSql\Role\CopyOptionsForm $copyOptions): self
    {
        return new self($this->optBinary, $this->qualifiedName, $this->optColumnList, $this->copyFrom, $this->optProgram, $this->copyFileName, $this->copyDelimiter, $this->optWith, $copyOptions, $this->where);
    }

    /**
     * Returns a copy with a new where, preserving every other field.
     */
    public function withWhere(\SqlSemantics\Statement\Model\PostgreSql\Role\WhereClauseForm $where): self
    {
        return new self($this->optBinary, $this->qualifiedName, $this->optColumnList, $this->copyFrom, $this->optProgram, $this->copyFileName, $this->copyDelimiter, $this->optWith, $this->copyOptions, $where);
    }
}
