<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\PostgreSql\Value;

/**
 * The CreateFdwStmt SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\PostgreSql\Value\CreateFdwStmtWithCreateForeignDataPWrapperNameOptFdwOptionsCreateGenericOptions_5cf8e4b7 $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class CreateFdwStmtWithCreateForeignDataPWrapperNameOptFdwOptionsCreateGenericOptions_5cf8e4b7 implements \SqlSemantics\Statement\Model\PostgreSql\Role\CreateFdwStmtForm, \SqlSemantics\Statement\Model\PostgreSql\Role\ParseToplevelForm, \SqlSemantics\Statement\Model\PostgreSql\Role\RoutineBodyStmtForm, \SqlSemantics\Statement\Model\PostgreSql\Role\StmtForm, \SqlSemantics\Statement\Model\PostgreSql\Role\StmtmultiForm, \SqlSemantics\Statement\Model\PostgreSql\Role\ToplevelStmtForm, \SqlSemantics\Statement\Command
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form; comments are kept by the position of the symbol each precedes.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\NameForm $name,
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\OptFdwOptionsForm $optFdwOptions,
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\CreateGenericOptionsForm $createGenericOptions,
        public readonly \SqlSemantics\Statement\Comments $comments = new \SqlSemantics\Statement\Comments(),
    ) {
        $this->assert(\SqlSemantics\Statement\Model\PostgreSql\Contract\Contracts::contains($name), 'The name must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\PostgreSql\Contract\Contracts::contains($optFdwOptions), 'The optFdwOptions must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\PostgreSql\Contract\Contracts::contains($createGenericOptions), 'The createGenericOptions must be a generated immutable SQL value.');
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->comments($this->comments, 0);
        $writer->append('CREATE');
        $writer->comments($this->comments, 1);
        $writer->append('FOREIGN');
        $writer->comments($this->comments, 2);
        $writer->append('DATA');
        $writer->comments($this->comments, 3);
        $writer->append('WRAPPER');
        $writer->comments($this->comments, 4);
        $this->name->write($writer);
        $writer->comments($this->comments, 5);
        $this->optFdwOptions->write($writer);
        $writer->comments($this->comments, 6);
        $this->createGenericOptions->write($writer);
    }

    /**
     * Lists the values of this form, in writing order.
     *
     * @return list<\SqlSemantics\Statement\Element>
     */
    public function children(): array
    {
        return [$this->name, $this->optFdwOptions, $this->createGenericOptions];
    }

    /**
     * Returns a copy whose values are replaced by what the function answers for each, keeping lexical fields and comments.
     *
     * @param callable(\SqlSemantics\Statement\Element): \SqlSemantics\Statement\Element $replace
     */
    public function map(callable $replace): static
    {
        return new self($this->replacement($this->name, \SqlSemantics\Statement\Model\PostgreSql\Role\NameForm::class, $replace), $this->replacement($this->optFdwOptions, \SqlSemantics\Statement\Model\PostgreSql\Role\OptFdwOptionsForm::class, $replace), $this->replacement($this->createGenericOptions, \SqlSemantics\Statement\Model\PostgreSql\Role\CreateGenericOptionsForm::class, $replace), $this->comments);
    }

    /**
     * Returns a copy with a new name, preserving every other field.
     */
    public function withName(\SqlSemantics\Statement\Model\PostgreSql\Role\NameForm $name): self
    {
        return new self($name, $this->optFdwOptions, $this->createGenericOptions, $this->comments);
    }

    /**
     * Returns a copy with a new optFdwOptions, preserving every other field.
     */
    public function withOptFdwOptions(\SqlSemantics\Statement\Model\PostgreSql\Role\OptFdwOptionsForm $optFdwOptions): self
    {
        return new self($this->name, $optFdwOptions, $this->createGenericOptions, $this->comments);
    }

    /**
     * Returns a copy with a new createGenericOptions, preserving every other field.
     */
    public function withCreateGenericOptions(\SqlSemantics\Statement\Model\PostgreSql\Role\CreateGenericOptionsForm $createGenericOptions): self
    {
        return new self($this->name, $this->optFdwOptions, $createGenericOptions, $this->comments);
    }

    /**
     * Returns a copy with a new comments, preserving every other field.
     */
    public function withComments(\SqlSemantics\Statement\Comments $comments): self
    {
        return new self($this->name, $this->optFdwOptions, $this->createGenericOptions, $comments);
    }
}
