<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\PostgreSql\Value;

/**
 * The CreateOptRoleElem SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\PostgreSql\Value\CreateOptRoleElemWithAdminRoleList_c5abca90 $value): string => (new \SqlSemantics\Statement\Statement($value))->toString();
 *     $write instanceof \Closure // => true
 */
final class CreateOptRoleElemWithAdminRoleList_c5abca90 implements \SqlSemantics\Statement\Model\PostgreSql\Role\CreateOptRoleElemForm
{
    /**
     * Supplies the SQL values of this form.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\RoleListForm $roleList,
    ) {
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->append('ADMIN');
        $this->roleList->write($writer);
    }
}
