<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\PostgreSql\Value;

/**
 * The CreatedbStmt SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\PostgreSql\Value\CreatedbStmtWithCreateDatabaseNameOptWithCreatedbOptList_b3fc222e $value): string => (new \SqlSemantics\Statement\Statement($value))->toString();
 *     $write instanceof \Closure // => true
 */
final class CreatedbStmtWithCreateDatabaseNameOptWithCreatedbOptList_b3fc222e implements \SqlSemantics\Statement\Model\PostgreSql\Role\CreatedbStmtForm, \SqlSemantics\Statement\Model\PostgreSql\Role\ParseToplevelForm, \SqlSemantics\Statement\Model\PostgreSql\Role\RoutineBodyStmtForm, \SqlSemantics\Statement\Model\PostgreSql\Role\StmtForm, \SqlSemantics\Statement\Model\PostgreSql\Role\StmtmultiForm, \SqlSemantics\Statement\Model\PostgreSql\Role\ToplevelStmtForm
{
    /**
     * Supplies the SQL values of this form.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\NameForm $name,
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\OptWithForm $optWith,
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\CreatedbOptListForm $createdbOptList,
    ) {
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->append('CREATE');
        $writer->append('DATABASE');
        $this->name->write($writer);
        $this->optWith->write($writer);
        $this->createdbOptList->write($writer);
    }
}
