<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\PostgreSql\Value;

/**
 * The cte_list SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\PostgreSql\Value\CteListWithCteListCommonTableExpr_1cee770c $value): string => (new \SqlSemantics\Statement\Statement($value))->toString();
 *     $write instanceof \Closure // => true
 */
final class CteListWithCteListCommonTableExpr_1cee770c implements \SqlSemantics\Statement\Model\PostgreSql\Role\CteListForm
{
    /**
     * Supplies the SQL values of this form.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\CteListForm $cteList,
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\CommonTableExprForm $commonTableExpr,
    ) {
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $this->cteList->write($writer);
        $writer->append(',');
        $this->commonTableExpr->write($writer);
    }
}
