<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\PostgreSql\Value;

/**
 * The DefineStmt SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\PostgreSql\Value\DefineStmtWithCreateOptOrReplaceAggregateFuncNameOldAggrDefinition_c1c37220 $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class DefineStmtWithCreateOptOrReplaceAggregateFuncNameOldAggrDefinition_c1c37220 implements \SqlSemantics\Statement\Model\PostgreSql\Role\DefineStmtForm, \SqlSemantics\Statement\Model\PostgreSql\Role\ParseToplevelForm, \SqlSemantics\Statement\Model\PostgreSql\Role\RoutineBodyStmtForm, \SqlSemantics\Statement\Model\PostgreSql\Role\StmtForm, \SqlSemantics\Statement\Model\PostgreSql\Role\StmtmultiForm, \SqlSemantics\Statement\Model\PostgreSql\Role\ToplevelStmtForm, \SqlSemantics\Statement\Command
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form; comments are kept by the position of the symbol each precedes.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\OptOrReplaceForm $optOrReplace,
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\FuncNameForm $funcName,
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\OldAggrDefinitionForm $oldAggrDefinition,
        public readonly \SqlSemantics\Statement\Comments $comments = new \SqlSemantics\Statement\Comments(),
    ) {
        $this->assert(\SqlSemantics\Statement\Model\PostgreSql\Contract\Contracts::contains($optOrReplace), 'The optOrReplace must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\PostgreSql\Contract\Contracts::contains($funcName), 'The funcName must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\PostgreSql\Contract\Contracts::contains($oldAggrDefinition), 'The oldAggrDefinition must be a generated immutable SQL value.');
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->comments($this->comments, 0);
        $writer->append('CREATE');
        $writer->comments($this->comments, 1);
        $this->optOrReplace->write($writer);
        $writer->comments($this->comments, 2);
        $writer->append('AGGREGATE');
        $writer->comments($this->comments, 3);
        $this->funcName->write($writer);
        $writer->comments($this->comments, 4);
        $this->oldAggrDefinition->write($writer);
    }

    /**
     * Lists the values of this form, in writing order.
     *
     * @return list<\SqlSemantics\Statement\Element>
     */
    public function children(): array
    {
        return [$this->optOrReplace, $this->funcName, $this->oldAggrDefinition];
    }

    /**
     * Returns this value rebuilt around what the function answers for each value, keeping lexical fields and comments; itself when every answer is the value it was given.
     *
     * @param callable(\SqlSemantics\Statement\Element): \SqlSemantics\Statement\Element $replace
     */
    public function map(callable $replace): static
    {
        $mapped = [$this->replacement($this->optOrReplace, \SqlSemantics\Statement\Model\PostgreSql\Role\OptOrReplaceForm::class, $replace), $this->replacement($this->funcName, \SqlSemantics\Statement\Model\PostgreSql\Role\FuncNameForm::class, $replace), $this->replacement($this->oldAggrDefinition, \SqlSemantics\Statement\Model\PostgreSql\Role\OldAggrDefinitionForm::class, $replace)];

        return $mapped === [$this->optOrReplace, $this->funcName, $this->oldAggrDefinition] ? $this : new self($mapped[0], $mapped[1], $mapped[2], $this->comments);
    }

    /**
     * Returns a copy with a new optOrReplace, preserving every other field.
     */
    public function withOptOrReplace(\SqlSemantics\Statement\Model\PostgreSql\Role\OptOrReplaceForm $optOrReplace): self
    {
        return new self($optOrReplace, $this->funcName, $this->oldAggrDefinition, $this->comments);
    }

    /**
     * Returns a copy with a new funcName, preserving every other field.
     */
    public function withFuncName(\SqlSemantics\Statement\Model\PostgreSql\Role\FuncNameForm $funcName): self
    {
        return new self($this->optOrReplace, $funcName, $this->oldAggrDefinition, $this->comments);
    }

    /**
     * Returns a copy with a new oldAggrDefinition, preserving every other field.
     */
    public function withOldAggrDefinition(\SqlSemantics\Statement\Model\PostgreSql\Role\OldAggrDefinitionForm $oldAggrDefinition): self
    {
        return new self($this->optOrReplace, $this->funcName, $oldAggrDefinition, $this->comments);
    }

    /**
     * Returns a copy with a new comments, preserving every other field.
     */
    public function withComments(\SqlSemantics\Statement\Comments $comments): self
    {
        return new self($this->optOrReplace, $this->funcName, $this->oldAggrDefinition, $comments);
    }
}
