<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\PostgreSql\Value;

/**
 * The def_list SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\PostgreSql\Value\DefListWithDefListDefElem_7ca52b20 $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class DefListWithDefListDefElem_7ca52b20 implements \SqlSemantics\Statement\Model\PostgreSql\Role\DefListForm
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form; comments are kept by the position of the symbol each precedes.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\DefListForm $defList,
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\DefElemForm $defElem,
        public readonly \SqlSemantics\Statement\Comments $comments = new \SqlSemantics\Statement\Comments(),
    ) {
        $this->assert(\SqlSemantics\Statement\Model\PostgreSql\Contract\Contracts::contains($defList), 'The defList must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\PostgreSql\Contract\Contracts::contains($defElem), 'The defElem must be a generated immutable SQL value.');
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->comments($this->comments, 0);
        $this->defList->write($writer);
        $writer->comments($this->comments, 1);
        $writer->append(',');
        $writer->comments($this->comments, 2);
        $this->defElem->write($writer);
    }

    /**
     * Lists the values of this form, in writing order.
     *
     * @return list<\SqlSemantics\Statement\Element>
     */
    public function children(): array
    {
        return [$this->defList, $this->defElem];
    }

    /**
     * Returns this value rebuilt around what the function answers for each value, keeping lexical fields and comments; itself when every answer is the value it was given.
     *
     * @param callable(\SqlSemantics\Statement\Element): \SqlSemantics\Statement\Element $replace
     */
    public function map(callable $replace): static
    {
        $mapped = [$this->replacement($this->defList, \SqlSemantics\Statement\Model\PostgreSql\Role\DefListForm::class, $replace), $this->replacement($this->defElem, \SqlSemantics\Statement\Model\PostgreSql\Role\DefElemForm::class, $replace)];

        return $mapped === [$this->defList, $this->defElem] ? $this : new self($mapped[0], $mapped[1], $this->comments);
    }

    /**
     * Returns a copy with a new defList, preserving every other field.
     */
    public function withDefList(\SqlSemantics\Statement\Model\PostgreSql\Role\DefListForm $defList): self
    {
        return new self($defList, $this->defElem, $this->comments);
    }

    /**
     * Returns a copy with a new defElem, preserving every other field.
     */
    public function withDefElem(\SqlSemantics\Statement\Model\PostgreSql\Role\DefElemForm $defElem): self
    {
        return new self($this->defList, $defElem, $this->comments);
    }

    /**
     * Returns a copy with a new comments, preserving every other field.
     */
    public function withComments(\SqlSemantics\Statement\Comments $comments): self
    {
        return new self($this->defList, $this->defElem, $comments);
    }
}
