<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\PostgreSql\Value;

/**
 * The distinct_clause SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\PostgreSql\Value\DistinctClauseWithDistinct_f568a127 $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class DistinctClauseWithDistinct_f568a127 implements \SqlSemantics\Statement\Model\PostgreSql\Role\DistinctClauseForm, \SqlSemantics\Statement\Model\PostgreSql\Role\OptDistinctClauseForm
{
    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->append('DISTINCT');
    }
}
