<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\PostgreSql\Value;

/**
 * The DomainConstraintElem SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\PostgreSql\Value\DomainConstraintElemWithNotNullPConstraintAttributeSpec_d6e563a9 $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class DomainConstraintElemWithNotNullPConstraintAttributeSpec_d6e563a9 implements \SqlSemantics\Statement\Model\PostgreSql\Role\DomainConstraintForm, \SqlSemantics\Statement\Model\PostgreSql\Role\DomainConstraintElemForm
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\ConstraintAttributeSpecForm $constraintAttributeSpec,
    ) {
        $this->assert(\SqlSemantics\Statement\Model\PostgreSql\Contract\Contracts::contains($constraintAttributeSpec), 'The constraintAttributeSpec must be a generated immutable SQL value.');
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->append('NOT');
        $writer->append('NULL');
        $this->constraintAttributeSpec->write($writer);
    }

    /**
     * Returns a copy with a new constraintAttributeSpec, preserving every other field.
     */
    public function withConstraintAttributeSpec(\SqlSemantics\Statement\Model\PostgreSql\Role\ConstraintAttributeSpecForm $constraintAttributeSpec): self
    {
        return new self($constraintAttributeSpec);
    }
}
