<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\PostgreSql\Value;

/**
 * The drop_type_name SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\PostgreSql\Value\DropTypeNameWithServer_c2263eb9 $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class DropTypeNameWithServer_c2263eb9 implements \SqlSemantics\Statement\Model\PostgreSql\Role\DropTypeNameForm, \SqlSemantics\Statement\Model\PostgreSql\Role\ObjectTypeNameForm
{
    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->append('SERVER');
    }
}
