<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\PostgreSql\Value;

/**
 * The ExistingIndex SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\PostgreSql\Value\ExistingIndexWithUsingIndexName_67f993b2 $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class ExistingIndexWithUsingIndexName_67f993b2 implements \SqlSemantics\Statement\Model\PostgreSql\Role\ExistingIndexForm
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\NameForm $name,
    ) {
        $this->assert(\SqlSemantics\Statement\Model\PostgreSql\Contract\Contracts::contains($name), 'The name must be a generated immutable SQL value.');
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->append('USING');
        $writer->append('INDEX');
        $this->name->write($writer);
    }

    /**
     * Returns a copy with a new name, preserving every other field.
     */
    public function withName(\SqlSemantics\Statement\Model\PostgreSql\Role\NameForm $name): self
    {
        return new self($name);
    }
}
