<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\PostgreSql\Value;

/**
 * The frame_bound SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\PostgreSql\Value\FrameBoundWithAExprFollowing_6c932dc0 $value): string => (new \SqlSemantics\Statement\Statement($value))->toString();
 *     $write instanceof \Closure // => true
 */
final class FrameBoundWithAExprFollowing_6c932dc0 implements \SqlSemantics\Statement\Model\PostgreSql\Role\FrameBoundForm, \SqlSemantics\Statement\Model\PostgreSql\Role\FrameExtentForm
{
    /**
     * Supplies the SQL values of this form.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\AExprForm $aExpr,
    ) {
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $this->aExpr->write($writer);
        $writer->append('FOLLOWING');
    }
}
