<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\PostgreSql\Value;

/**
 * The func_arg_list SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\PostgreSql\Value\FuncArgListWithFuncArgListFuncArgExpr_7f3e8162 $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class FuncArgListWithFuncArgListFuncArgExpr_7f3e8162 implements \SqlSemantics\Statement\Model\PostgreSql\Role\FuncArgListForm, \SqlSemantics\Statement\Model\PostgreSql\Role\FuncArgListOptForm
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form; comments are kept by the position of the symbol each precedes.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\FuncArgListForm $funcArgList,
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\FuncArgExprForm $funcArgExpr,
        public readonly \SqlSemantics\Statement\Comments $comments = new \SqlSemantics\Statement\Comments(),
    ) {
        $this->assert(\SqlSemantics\Statement\Model\PostgreSql\Contract\Contracts::contains($funcArgList), 'The funcArgList must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\PostgreSql\Contract\Contracts::contains($funcArgExpr), 'The funcArgExpr must be a generated immutable SQL value.');
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->comments($this->comments, 0);
        $this->funcArgList->write($writer);
        $writer->comments($this->comments, 1);
        $writer->append(',');
        $writer->comments($this->comments, 2);
        $this->funcArgExpr->write($writer);
    }

    /**
     * Returns a copy with a new funcArgList, preserving every other field.
     */
    public function withFuncArgList(\SqlSemantics\Statement\Model\PostgreSql\Role\FuncArgListForm $funcArgList): self
    {
        return new self($funcArgList, $this->funcArgExpr, $this->comments);
    }

    /**
     * Returns a copy with a new funcArgExpr, preserving every other field.
     */
    public function withFuncArgExpr(\SqlSemantics\Statement\Model\PostgreSql\Role\FuncArgExprForm $funcArgExpr): self
    {
        return new self($this->funcArgList, $funcArgExpr, $this->comments);
    }

    /**
     * Returns a copy with a new comments, preserving every other field.
     */
    public function withComments(\SqlSemantics\Statement\Comments $comments): self
    {
        return new self($this->funcArgList, $this->funcArgExpr, $comments);
    }
}
