<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\PostgreSql\Value;

/**
 * The hash_partbound_elem SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\PostgreSql\Value\HashPartboundElemWithNonReservedWordIconst_0a70ae96 $value): string => (new \SqlSemantics\Statement\Statement($value))->toString();
 *     $write instanceof \Closure // => true
 */
final class HashPartboundElemWithNonReservedWordIconst_0a70ae96 implements \SqlSemantics\Statement\Model\PostgreSql\Role\HashPartboundForm, \SqlSemantics\Statement\Model\PostgreSql\Role\HashPartboundElemForm
{
    /**
     * Supplies the SQL values of this form.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\NonReservedWordForm $nonReservedWord,
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\IconstForm $iconst,
    ) {
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $this->nonReservedWord->write($writer);
        $this->iconst->write($writer);
    }
}
