<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\PostgreSql\Value;

/**
 * The IndexStmt SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\PostgreSql\Value\IndexStmtWithCreateOptUniqueIndexOptConcurrentlyOptSingleNameOnRelationExprAccessMethodC_99a5bd5e $value): string => (new \SqlSemantics\Statement\Statement($value))->toString();
 *     $write instanceof \Closure // => true
 */
final class IndexStmtWithCreateOptUniqueIndexOptConcurrentlyOptSingleNameOnRelationExprAccessMethodC_99a5bd5e implements \SqlSemantics\Statement\Model\PostgreSql\Role\IndexStmtForm, \SqlSemantics\Statement\Model\PostgreSql\Role\ParseToplevelForm, \SqlSemantics\Statement\Model\PostgreSql\Role\RoutineBodyStmtForm, \SqlSemantics\Statement\Model\PostgreSql\Role\SchemaStmtForm, \SqlSemantics\Statement\Model\PostgreSql\Role\StmtForm, \SqlSemantics\Statement\Model\PostgreSql\Role\StmtmultiForm, \SqlSemantics\Statement\Model\PostgreSql\Role\ToplevelStmtForm
{
    /**
     * Supplies the SQL values of this form.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\OptUniqueForm $optUnique,
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\OptConcurrentlyForm $optConcurrently,
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\OptSingleNameForm $optSingleName,
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\RelationExprForm $relationExpr,
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\AccessMethodClauseForm $accessMethodClause,
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\IndexParamsForm $indexParams,
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\OptIncludeForm $optInclude,
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\OptUniqueNullTreatmentForm $optUniqueNullTreatment,
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\OptReloptionsForm $optReloptions,
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\OptTableSpaceForm $optTableSpace,
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\WhereClauseForm $where,
    ) {
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->append('CREATE');
        $this->optUnique->write($writer);
        $writer->append('INDEX');
        $this->optConcurrently->write($writer);
        $this->optSingleName->write($writer);
        $writer->append('ON');
        $this->relationExpr->write($writer);
        $this->accessMethodClause->write($writer);
        $writer->append('(');
        $this->indexParams->write($writer);
        $writer->append(')');
        $this->optInclude->write($writer);
        $this->optUniqueNullTreatment->write($writer);
        $this->optReloptions->write($writer);
        $this->optTableSpace->write($writer);
        $this->where->write($writer);
    }
}
