<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\PostgreSql\Value;

/**
 * The indirection SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\PostgreSql\Value\IndirectionWithIndirectionIndirectionEl_48df823c $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class IndirectionWithIndirectionIndirectionEl_48df823c implements \SqlSemantics\Statement\Model\PostgreSql\Role\IndirectionForm
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form; comments are kept by the position of the symbol each precedes.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\IndirectionForm $indirection,
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\IndirectionElForm $indirectionEl,
        public readonly \SqlSemantics\Statement\Comments $comments = new \SqlSemantics\Statement\Comments(),
    ) {
        $this->assert(\SqlSemantics\Statement\Model\PostgreSql\Contract\Contracts::contains($indirection), 'The indirection must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\PostgreSql\Contract\Contracts::contains($indirectionEl), 'The indirectionEl must be a generated immutable SQL value.');
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->comments($this->comments, 0);
        $this->indirection->write($writer);
        $writer->comments($this->comments, 1);
        $this->indirectionEl->write($writer);
    }

    /**
     * Returns a copy with a new indirection, preserving every other field.
     */
    public function withIndirection(\SqlSemantics\Statement\Model\PostgreSql\Role\IndirectionForm $indirection): self
    {
        return new self($indirection, $this->indirectionEl, $this->comments);
    }

    /**
     * Returns a copy with a new indirectionEl, preserving every other field.
     */
    public function withIndirectionEl(\SqlSemantics\Statement\Model\PostgreSql\Role\IndirectionElForm $indirectionEl): self
    {
        return new self($this->indirection, $indirectionEl, $this->comments);
    }

    /**
     * Returns a copy with a new comments, preserving every other field.
     */
    public function withComments(\SqlSemantics\Statement\Comments $comments): self
    {
        return new self($this->indirection, $this->indirectionEl, $comments);
    }
}
