<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\PostgreSql\Value;

/**
 * The joined_table SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\PostgreSql\Value\JoinedTableWithJoinedTable_49114d90 $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class JoinedTableWithJoinedTable_49114d90 implements \SqlSemantics\Statement\Model\PostgreSql\Role\FromListForm, \SqlSemantics\Statement\Model\PostgreSql\Role\JoinedTableForm, \SqlSemantics\Statement\Model\PostgreSql\Role\TableRefForm
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\JoinedTableForm $joinedTable,
    ) {
        $this->assert(\SqlSemantics\Statement\Model\PostgreSql\Contract\Contracts::contains($joinedTable), 'The joinedTable must be a generated immutable SQL value.');
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->append('(');
        $this->joinedTable->write($writer);
        $writer->append(')');
    }

    /**
     * Returns a copy with a new joinedTable, preserving every other field.
     */
    public function withJoinedTable(\SqlSemantics\Statement\Model\PostgreSql\Role\JoinedTableForm $joinedTable): self
    {
        return new self($joinedTable);
    }
}
