<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\PostgreSql\Value;

/**
 * The json_table_column_definition SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\PostgreSql\Value\JsonTableColumnDefinitionWithColIdTypenameExistsJsonTableColumnPathClauseOptJsonOnErrorClauseOpt_d81d25e2 $value): string => (new \SqlSemantics\Statement\Statement($value))->toString();
 *     $write instanceof \Closure // => true
 */
final class JsonTableColumnDefinitionWithColIdTypenameExistsJsonTableColumnPathClauseOptJsonOnErrorClauseOpt_d81d25e2 implements \SqlSemantics\Statement\Model\PostgreSql\Role\JsonTableColumnDefinitionForm, \SqlSemantics\Statement\Model\PostgreSql\Role\JsonTableColumnDefinitionListForm
{
    /**
     * Supplies the SQL values of this form.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\ColIdForm $colId,
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\TypenameForm $typename,
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\JsonTableColumnPathClauseOptForm $jsonTableColumnPathClauseOpt,
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\JsonOnErrorClauseOptForm $jsonOnErrorClauseOpt,
    ) {
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $this->colId->write($writer);
        $this->typename->write($writer);
        $writer->append('EXISTS');
        $this->jsonTableColumnPathClauseOpt->write($writer);
        $this->jsonOnErrorClauseOpt->write($writer);
    }
}
