<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\PostgreSql\Value;

/**
 * The key_delete SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\PostgreSql\Value\KeyDeleteWithOnDeletePKeyAction_1457299d $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class KeyDeleteWithOnDeletePKeyAction_1457299d implements \SqlSemantics\Statement\Model\PostgreSql\Role\KeyActionsForm, \SqlSemantics\Statement\Model\PostgreSql\Role\KeyDeleteForm
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\KeyActionForm $keyAction,
    ) {
        $this->assert(\SqlSemantics\Statement\Model\PostgreSql\Contract\Contracts::contains($keyAction), 'The keyAction must be a generated immutable SQL value.');
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->append('ON');
        $writer->append('DELETE');
        $this->keyAction->write($writer);
    }

    /**
     * Returns a copy with a new keyAction, preserving every other field.
     */
    public function withKeyAction(\SqlSemantics\Statement\Model\PostgreSql\Role\KeyActionForm $keyAction): self
    {
        return new self($keyAction);
    }
}
