<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\PostgreSql\Value;

/**
 * The name_list SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\PostgreSql\Value\NameListWithNameListName_0786bfd5 $value): string => (new \SqlSemantics\Statement\Statement($value))->toString();
 *     $write instanceof \Closure // => true
 */
final class NameListWithNameListName_0786bfd5 implements \SqlSemantics\Statement\Model\PostgreSql\Role\NameListForm
{
    /**
     * Supplies the SQL values of this form.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\NameListForm $nameList,
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\NameForm $name,
    ) {
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $this->nameList->write($writer);
        $writer->append(',');
        $this->name->write($writer);
    }
}
