<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\PostgreSql\Value;

/**
 * The opclass_drop SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\PostgreSql\Value\OpclassDropWithFunctionIconstTypeList_648db824 $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class OpclassDropWithFunctionIconstTypeList_648db824 implements \SqlSemantics\Statement\Model\PostgreSql\Role\OpclassDropForm, \SqlSemantics\Statement\Model\PostgreSql\Role\OpclassDropListForm
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form; comments are kept by the position of the symbol each precedes.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\IconstForm $iconst,
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\TypeListForm $typeList,
        public readonly \SqlSemantics\Statement\Comments $comments = new \SqlSemantics\Statement\Comments(),
    ) {
        $this->assert(\SqlSemantics\Statement\Model\PostgreSql\Contract\Contracts::contains($iconst), 'The iconst must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\PostgreSql\Contract\Contracts::contains($typeList), 'The typeList must be a generated immutable SQL value.');
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->comments($this->comments, 0);
        $writer->append('FUNCTION');
        $writer->comments($this->comments, 1);
        $this->iconst->write($writer);
        $writer->comments($this->comments, 2);
        $writer->append('(');
        $writer->comments($this->comments, 3);
        $this->typeList->write($writer);
        $writer->comments($this->comments, 4);
        $writer->append(')');
    }

    /**
     * Returns a copy with a new iconst, preserving every other field.
     */
    public function withIconst(\SqlSemantics\Statement\Model\PostgreSql\Role\IconstForm $iconst): self
    {
        return new self($iconst, $this->typeList, $this->comments);
    }

    /**
     * Returns a copy with a new typeList, preserving every other field.
     */
    public function withTypeList(\SqlSemantics\Statement\Model\PostgreSql\Role\TypeListForm $typeList): self
    {
        return new self($this->iconst, $typeList, $this->comments);
    }

    /**
     * Returns a copy with a new comments, preserving every other field.
     */
    public function withComments(\SqlSemantics\Statement\Comments $comments): self
    {
        return new self($this->iconst, $this->typeList, $comments);
    }
}
