<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\PostgreSql\Value;

/**
 * The opt_nulls_order SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\PostgreSql\Value\OptNullsOrderWithNullsLaLastP_5577224a $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class OptNullsOrderWithNullsLaLastP_5577224a implements \SqlSemantics\Statement\Model\PostgreSql\Role\OptNullsOrderForm
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form.
     */
    public function __construct(
        public readonly string $nullsLa,
    ) {
        $this->assertMatchesPattern($nullsLa, \SqlSemantics\Statement\Model\PostgreSql\Contract\Contracts::SPELLINGS['NULLS_LA'], 'The nullsLa must be a complete NULLS_LA lexical spelling.');
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->append($this->nullsLa);
        $writer->append('LAST');
    }

    /**
     * Returns a copy with a new nullsLa, preserving every other field.
     */
    public function withNullsLa(string $nullsLa): self
    {
        return new self($nullsLa);
    }
}
