<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\PostgreSql\Value;

/**
 * The opt_provider SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\PostgreSql\Value\OptProviderWithForNonReservedWordOrSconst_d64fc618 $value): string => (new \SqlSemantics\Statement\Statement($value))->toString();
 *     $write instanceof \Closure // => true
 */
final class OptProviderWithForNonReservedWordOrSconst_d64fc618 implements \SqlSemantics\Statement\Model\PostgreSql\Role\OptProviderForm
{
    /**
     * Supplies the SQL values of this form.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\NonReservedWordOrSconstForm $nonReservedWordOrSconst,
    ) {
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->append('FOR');
        $this->nonReservedWordOrSconst->write($writer);
    }
}
