<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\PostgreSql\Value;

/**
 * The partition_cmd SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\PostgreSql\Value\PartitionCmdWithDetachPartitionQualifiedNameOptConcurrently_c41413df $value): string => (new \SqlSemantics\Statement\Statement($value))->toString();
 *     $write instanceof \Closure // => true
 */
final class PartitionCmdWithDetachPartitionQualifiedNameOptConcurrently_c41413df implements \SqlSemantics\Statement\Model\PostgreSql\Role\PartitionCmdForm
{
    /**
     * Supplies the SQL values of this form.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\QualifiedNameForm $qualifiedName,
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\OptConcurrentlyForm $optConcurrently,
    ) {
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->append('DETACH');
        $writer->append('PARTITION');
        $this->qualifiedName->write($writer);
        $this->optConcurrently->write($writer);
    }
}
