<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\PostgreSql\Value;

/**
 * The privilege_target SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\PostgreSql\Value\PrivilegeTargetWithAllRoutinesInPSchemaNameList_22b17595 $value): string => (new \SqlSemantics\Statement\Statement($value))->toString();
 *     $write instanceof \Closure // => true
 */
final class PrivilegeTargetWithAllRoutinesInPSchemaNameList_22b17595 implements \SqlSemantics\Statement\Model\PostgreSql\Role\PrivilegeTargetForm
{
    /**
     * Supplies the SQL values of this form.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\NameListForm $nameList,
    ) {
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->append('ALL');
        $writer->append('ROUTINES');
        $writer->append('IN');
        $writer->append('SCHEMA');
        $this->nameList->write($writer);
    }
}
