<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\PostgreSql\Value;

/**
 * The privilege SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\PostgreSql\Value\PrivilegeWithColIdOptColumnList_a43359d8 $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class PrivilegeWithColIdOptColumnList_a43359d8 implements \SqlSemantics\Statement\Model\PostgreSql\Role\PrivilegeForm, \SqlSemantics\Statement\Model\PostgreSql\Role\PrivilegeListForm, \SqlSemantics\Statement\Model\PostgreSql\Role\PrivilegesForm
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\ColIdForm $colId,
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\OptColumnListForm $optColumnList,
    ) {
        $this->assert(\SqlSemantics\Statement\Model\PostgreSql\Contract\Contracts::contains($colId), 'The colId must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\PostgreSql\Contract\Contracts::contains($optColumnList), 'The optColumnList must be a generated immutable SQL value.');
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $this->colId->write($writer);
        $this->optColumnList->write($writer);
    }

    /**
     * Returns a copy with a new colId, preserving every other field.
     */
    public function withColId(\SqlSemantics\Statement\Model\PostgreSql\Role\ColIdForm $colId): self
    {
        return new self($colId, $this->optColumnList);
    }

    /**
     * Returns a copy with a new optColumnList, preserving every other field.
     */
    public function withOptColumnList(\SqlSemantics\Statement\Model\PostgreSql\Role\OptColumnListForm $optColumnList): self
    {
        return new self($this->colId, $optColumnList);
    }
}
