<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\PostgreSql\Value;

/**
 * The RemoveOperStmt SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\PostgreSql\Value\RemoveOperStmtWithDropOperatorIfPExistsOperatorWithArgtypesListOptDropBehavior_08b4d09c $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class RemoveOperStmtWithDropOperatorIfPExistsOperatorWithArgtypesListOptDropBehavior_08b4d09c implements \SqlSemantics\Statement\Model\PostgreSql\Role\RemoveOperStmtForm, \SqlSemantics\Statement\Model\PostgreSql\Role\ParseToplevelForm, \SqlSemantics\Statement\Model\PostgreSql\Role\RoutineBodyStmtForm, \SqlSemantics\Statement\Model\PostgreSql\Role\StmtForm, \SqlSemantics\Statement\Model\PostgreSql\Role\StmtmultiForm, \SqlSemantics\Statement\Model\PostgreSql\Role\ToplevelStmtForm, \SqlSemantics\Statement\Command
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form; comments are kept by the position of the symbol each precedes.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\OperatorWithArgtypesListForm $operatorWithArgtypesList,
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\OptDropBehaviorForm $optDropBehavior,
        public readonly \SqlSemantics\Statement\Comments $comments = new \SqlSemantics\Statement\Comments(),
    ) {
        $this->assert(\SqlSemantics\Statement\Model\PostgreSql\Contract\Contracts::contains($operatorWithArgtypesList), 'The operatorWithArgtypesList must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\PostgreSql\Contract\Contracts::contains($optDropBehavior), 'The optDropBehavior must be a generated immutable SQL value.');
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->comments($this->comments, 0);
        $writer->append('DROP');
        $writer->comments($this->comments, 1);
        $writer->append('OPERATOR');
        $writer->comments($this->comments, 2);
        $writer->append('IF');
        $writer->comments($this->comments, 3);
        $writer->append('EXISTS');
        $writer->comments($this->comments, 4);
        $this->operatorWithArgtypesList->write($writer);
        $writer->comments($this->comments, 5);
        $this->optDropBehavior->write($writer);
    }

    /**
     * Returns a copy with a new operatorWithArgtypesList, preserving every other field.
     */
    public function withOperatorWithArgtypesList(\SqlSemantics\Statement\Model\PostgreSql\Role\OperatorWithArgtypesListForm $operatorWithArgtypesList): self
    {
        return new self($operatorWithArgtypesList, $this->optDropBehavior, $this->comments);
    }

    /**
     * Returns a copy with a new optDropBehavior, preserving every other field.
     */
    public function withOptDropBehavior(\SqlSemantics\Statement\Model\PostgreSql\Role\OptDropBehaviorForm $optDropBehavior): self
    {
        return new self($this->operatorWithArgtypesList, $optDropBehavior, $this->comments);
    }

    /**
     * Returns a copy with a new comments, preserving every other field.
     */
    public function withComments(\SqlSemantics\Statement\Comments $comments): self
    {
        return new self($this->operatorWithArgtypesList, $this->optDropBehavior, $comments);
    }
}
