<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\PostgreSql\Value;

/**
 * The RenameStmt SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\PostgreSql\Value\RenameStmtWithAlterSubscriptionNameRenameToName_e6ac83f2 $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class RenameStmtWithAlterSubscriptionNameRenameToName_e6ac83f2 implements \SqlSemantics\Statement\Model\PostgreSql\Role\RenameStmtForm, \SqlSemantics\Statement\Model\PostgreSql\Role\ParseToplevelForm, \SqlSemantics\Statement\Model\PostgreSql\Role\RoutineBodyStmtForm, \SqlSemantics\Statement\Model\PostgreSql\Role\StmtForm, \SqlSemantics\Statement\Model\PostgreSql\Role\StmtmultiForm, \SqlSemantics\Statement\Model\PostgreSql\Role\ToplevelStmtForm, \SqlSemantics\Statement\Command
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\NameForm $name,
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\NameForm $name2,
    ) {
        $this->assert(\SqlSemantics\Statement\Model\PostgreSql\Contract\Contracts::contains($name), 'The name must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\PostgreSql\Contract\Contracts::contains($name2), 'The name2 must be a generated immutable SQL value.');
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->append('ALTER');
        $writer->append('SUBSCRIPTION');
        $this->name->write($writer);
        $writer->append('RENAME');
        $writer->append('TO');
        $this->name2->write($writer);
    }

    /**
     * Returns a copy with a new name, preserving every other field.
     */
    public function withName(\SqlSemantics\Statement\Model\PostgreSql\Role\NameForm $name): self
    {
        return new self($name, $this->name2);
    }

    /**
     * Returns a copy with a new name2, preserving every other field.
     */
    public function withName2(\SqlSemantics\Statement\Model\PostgreSql\Role\NameForm $name2): self
    {
        return new self($this->name, $name2);
    }
}
