<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\PostgreSql\Value;

/**
 * The SeqOptElem SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\PostgreSql\Value\SeqOptElemWithRestart_5cee348c $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class SeqOptElemWithRestart_5cee348c implements \SqlSemantics\Statement\Model\PostgreSql\Role\OptSeqOptListForm, \SqlSemantics\Statement\Model\PostgreSql\Role\SeqOptElemForm, \SqlSemantics\Statement\Model\PostgreSql\Role\SeqOptListForm
{
    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->append('RESTART');
    }
}
