<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\PostgreSql\Value;

/**
 * The window_clause SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\PostgreSql\Value\WindowClauseWithWindowWindowDefinitionList_475a2a6b $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class WindowClauseWithWindowWindowDefinitionList_475a2a6b implements \SqlSemantics\Statement\Model\PostgreSql\Role\WindowClauseForm
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\WindowDefinitionListForm $windowDefinitionList,
    ) {
        $this->assert(\SqlSemantics\Statement\Model\PostgreSql\Contract\Contracts::contains($windowDefinitionList), 'The windowDefinitionList must be a generated immutable SQL value.');
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->append('WINDOW');
        $this->windowDefinitionList->write($writer);
    }

    /**
     * Returns a copy with a new windowDefinitionList, preserving every other field.
     */
    public function withWindowDefinitionList(\SqlSemantics\Statement\Model\PostgreSql\Role\WindowDefinitionListForm $windowDefinitionList): self
    {
        return new self($windowDefinitionList);
    }
}
