<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\PostgreSql\Value;

/**
 * The xmltable_column_option_el SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\PostgreSql\Value\XmltableColumnOptionElWithPathBExpr_b2376d8c $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class XmltableColumnOptionElWithPathBExpr_b2376d8c implements \SqlSemantics\Statement\Model\PostgreSql\Role\XmltableColumnOptionElForm, \SqlSemantics\Statement\Model\PostgreSql\Role\XmltableColumnOptionListForm
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form; comments are kept by the position of the symbol each precedes.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\PostgreSql\Role\BExprForm $bExpr,
        public readonly \SqlSemantics\Statement\Comments $comments = new \SqlSemantics\Statement\Comments(),
    ) {
        $this->assert(\SqlSemantics\Statement\Model\PostgreSql\Contract\Contracts::contains($bExpr), 'The bExpr must be a generated immutable SQL value.');
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->comments($this->comments, 0);
        $writer->append('PATH');
        $writer->comments($this->comments, 1);
        $this->bExpr->write($writer);
    }

    /**
     * Lists the values of this form, in writing order.
     *
     * @return list<\SqlSemantics\Statement\Element>
     */
    public function children(): array
    {
        return [$this->bExpr];
    }

    /**
     * Returns this value rebuilt around what the function answers for each value, keeping lexical fields and comments; itself when every answer is the value it was given.
     *
     * @param callable(\SqlSemantics\Statement\Element): \SqlSemantics\Statement\Element $replace
     */
    public function map(callable $replace): static
    {
        $mapped = [$this->replacement($this->bExpr, \SqlSemantics\Statement\Model\PostgreSql\Role\BExprForm::class, $replace)];

        return $mapped === [$this->bExpr] ? $this : new self($mapped[0], $this->comments);
    }

    /**
     * Returns a copy with a new bExpr, preserving every other field.
     */
    public function withBExpr(\SqlSemantics\Statement\Model\PostgreSql\Role\BExprForm $bExpr): self
    {
        return new self($bExpr, $this->comments);
    }

    /**
     * Returns a copy with a new comments, preserving every other field.
     */
    public function withComments(\SqlSemantics\Statement\Comments $comments): self
    {
        return new self($this->bExpr, $comments);
    }
}
