<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Choice;

/**
 * The and SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Choice\AndChoice_1c2990dc $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
enum AndChoice_1c2990dc: string implements \SqlSemantics\Statement\Model\MySql\Role\AndForm
{
    case UseAnd_bd972cc4 = 'AND';
    case Use_73e7b6f8 = '&&';

    /**
     * Writes the selected SQL option.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        foreach (explode(' ', $this->value) as $word) {
            $writer->append($word);
        }
    }
}
