<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Choice;

/**
 * The opt_bin_mod SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Choice\OptBinModChoice_e8ffc0d2 $value): string => (new \SqlSemantics\Statement\Statement($value))->toString();
 *     $write instanceof \Closure // => true
 */
enum OptBinModChoice_e8ffc0d2: string implements \SqlSemantics\Statement\Model\MySql\Role\OptBinModForm
{
    case Use_e3b0c442 = '';
    case UseBinary_4c77b56b = 'BINARY';

    /**
     * Writes the selected SQL option.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        foreach (explode(' ', $this->value) as $word) {
            $writer->append($word);
        }
    }
}
