<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Choice;

/**
 * The opt_checksum_type SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Choice\OptChecksumTypeChoice_7ff41d7d $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
enum OptChecksumTypeChoice_7ff41d7d: string implements \SqlSemantics\Statement\Model\MySql\Role\OptChecksumTypeForm
{
    case Use_e3b0c442 = '';
    case UseQuick_e0273b60 = 'QUICK';
    case UseExtended_9632d8ea = 'EXTENDED';

    /**
     * Writes the selected SQL option.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        foreach (explode(' ', $this->value) as $word) {
            $writer->append($word);
        }
    }
}
