<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Choice;

/**
 * The opt_outer SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Choice\OptOuterChoice_86cb63c7 $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
enum OptOuterChoice_86cb63c7: string implements \SqlSemantics\Statement\Model\MySql\Role\OptOuterForm
{
    case Use_e3b0c442 = '';
    case UseOuter_2c635ca0 = 'OUTER';

    /**
     * Writes the selected SQL option.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        foreach (explode(' ', $this->value) as $word) {
            $writer->append($word);
        }
    }
}
