<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Choice;

/**
 * The remember_end SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Choice\RememberEndChoice_055539df $value): string => (new \SqlSemantics\Statement\Statement($value))->toString();
 *     $write instanceof \Closure // => true
 */
enum RememberEndChoice_055539df: string implements \SqlSemantics\Statement\Model\MySql\Role\RememberEndForm
{
    case Use_e3b0c442 = '';

    /**
     * Writes the selected SQL option.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        foreach (explode(' ', $this->value) as $word) {
            $writer->append($word);
        }
    }
}
