<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Choice;

/**
 * The trigger_action_order SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Choice\TriggerActionOrderChoice_b52f2f95 $value): string => (new \SqlSemantics\Statement\Statement($value))->toString();
 *     $write instanceof \Closure // => true
 */
enum TriggerActionOrderChoice_b52f2f95: string implements \SqlSemantics\Statement\Model\MySql\Role\TriggerActionOrderForm
{
    case UseFollows_f734af59 = 'FOLLOWS';
    case UsePrecedes_bba1c15a = 'PRECEDES';

    /**
     * Writes the selected SQL option.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        foreach (explode(' ', $this->value) as $word) {
            $writer->append($word);
        }
    }
}
