$schema: 'https://raw.githubusercontent.com/k-kinzal/ztd-query-php/main/packages/requirements/schemas/config.schema.json'
version: 1
definitions:
  - 'requirements/*.yaml'
runners:
  unit:
    extension: phpunit
    command:
      - php
      - vendor/bin/phpunit
      - '--configuration'
      - phpunit.xml.dist
coverage:
  minimum: 100
