$schema: 'https://raw.githubusercontent.com/k-kinzal/ztd-query-php/main/packages/requirements/schemas/config.schema.json'
version: 1
definitions:
  - 'requirements/*.yaml'
runners:
  behavior:
    extension: behat
    command:
      - php
      - vendor/bin/behat
    timeout: 60
coverage:
  minimum: 96
  sources:
    bison-symbols: 93
    bison-rules: 100
