<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\Sqlite\Contract;

/**
 * Immutable model membership, lexical domains and operand binding strengths.
 *
 * @visibility SqlSemantics
 */
final class Contracts
{
    /**
     * Generated construction facts; no parser is consulted by a value.
     *
     * @var array<class-string<\SqlSemantics\Statement\Element>, true>
     */
    public const ELEMENTS = array (
  'SqlSemantics\\Statement\\Model\\Sqlite\\Choice\\AutoincChoice_d1be63bd' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Choice\\BetweenOpChoice_06f4f5f4' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Choice\\CreatekwChoice_bb5df1f3' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Choice\\DatabaseKwOptChoice_a5a26b1d' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Choice\\DistinctChoice_deb627ba' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Choice\\ExplainChoice_417275df' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Choice\\ForeachClauseChoice_a60da7c2' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Choice\\IfexistsChoice_1b8cb991' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Choice\\IfnotexistsChoice_f381f4e9' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Choice\\InOpChoice_0915428e' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Choice\\InitDeferredPredOptChoice_ed380d4f' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Choice\\KwcolumnOptChoice_eefdbfac' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Choice\\LpChoice_0ce700cc' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Choice\\NullsChoice_6b2c7d75' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Choice\\RaisetypeChoice_0819de2d' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Choice\\RefactChoice_2802cc9d' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Choice\\SavepointOptChoice_74ffdd90' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Choice\\ScanptChoice_055539df' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Choice\\ScantokChoice_055539df' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Choice\\SortorderChoice_01affc0e' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Choice\\TconscommaChoice_d7313e6d' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Choice\\TranstypeChoice_9594d9a4' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Choice\\UniqueflagChoice_996fc274' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Choice\\WqasChoice_5d67ccbe' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\AnylistWithAnylistAny_940e683b' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\AnylistWithAnylistLpAnylistRp_0c30e0aa' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\AnylistWith_b1da56a9' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\AsWithAsNm_f6e3a168' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\AsWithIds_1689a84e' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\AsWith_9dc353c5' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\CarglistWithCarglistCcons_d6c91d8e' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\CarglistWith_b1a2e344' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\CaseElseWithElseExpr_f8f4f7a0' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\CaseElseWith_4209e8da' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\CaseExprlistWithCaseExprlistWhenExprThenExpr_1993e882' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\CaseExprlistWithWhenExprThenExpr_fc6d9fa6' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\CaseOperandWith_b8923944' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\CconsWithAsGenerated_a8c85419' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\CconsWithCheckLpExprRp_a257354c' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\CconsWithCollateIds_f026273f' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\CconsWithConstraintNm_21d95a03' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\CconsWithDefaultLpExprRp_c9989710' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\CconsWithDefaultMinusScantokTerm_aee20286' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\CconsWithDefaultPlusScantokTerm_27a5c06c' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\CconsWithDefaultScantokId_263f0ac8' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\CconsWithDefaultScantokTerm_16444cab' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\CconsWithGeneratedAlwaysAsGenerated_49de3479' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\CconsWithNotNullOnconf_11cbf2a3' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\CconsWithNullOnconf_fb3a3126' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\CconsWithPrimaryKeySortorderOnconfAutoinc_23337c2b' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\CconsWithReferencesNmEidlistOptRefargs_77b203d0' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\CconsWithUniqueOnconf_426d13d8' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\CmdWithAlterTableAddColumnFullnameAddKwcolumnOptColumnnameCarglist_868ede0d' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\CmdWithAlterTableFullnameDropKwcolumnOptNm_73d19d46' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\CmdWithAlterTableFullnameRenameKwcolumnOptNmToNm_e1bbf896' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\CmdWithAlterTableFullnameRenameToNm_f687ccf9' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\CmdWithAnalyzeNmDbnm_88c42263' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\CmdWithAnalyze_4726546f' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\CmdWithAttachDatabaseKwOptExprAsExprKeyOpt_87608024' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\CmdWithBeginTranstypeTransOpt_d437fc17' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\CmdWithCommitEndTransOpt_ccca6149' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\CmdWithCreateTableCreateTableArgs_51837b7b' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\CmdWithCreateVtabLpVtabarglistRp_f47fc34c' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\CmdWithCreatekwTempViewIfnotexistsNmDbnmEidlistOptAsSelect_982c3d9a' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\CmdWithCreatekwTriggerDeclBeginTriggerCmdListEnd_8217e10b' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\CmdWithCreatekwUniqueflagIndexIfnotexistsNmDbnmOnNmLpSortlistRpWhereOpt_0880662b' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\CmdWithDetachDatabaseKwOptExpr_f7c66c8d' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\CmdWithDropIndexIfexistsFullname_44a2d8ce' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\CmdWithDropTableIfexistsFullname_cdf29e83' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\CmdWithDropTriggerIfexistsFullname_582f5f4c' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\CmdWithDropViewIfexistsFullname_a7db3715' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\CmdWithPragmaNmDbnmEqMinusNum_88ca56f4' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\CmdWithPragmaNmDbnmEqNmnum_e6b5c848' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\CmdWithPragmaNmDbnmLpMinusNumRp_74bb878f' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\CmdWithPragmaNmDbnmLpNmnumRp_c4072dd8' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\CmdWithPragmaNmDbnm_5bebe510' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\CmdWithReindexNmDbnm_c0d1653e' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\CmdWithReindex_e9f85aaa' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\CmdWithReleaseSavepointOptNm_f80bbcd2' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\CmdWithRollbackTransOptToSavepointOptNm_89eb621f' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\CmdWithRollbackTransOpt_00f0c935' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\CmdWithSavepointNm_bf1c3338' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\CmdWithVacuumNmVinto_13d1a32b' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\CmdWithVacuumVinto_5a4cdae3' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\CmdWithWithDeleteFromXfullnameIndexedOptWhereOptRet_9ab314d3' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\CmdWithWithInsertCmdIntoXfullnameIdlistOptDefaultValuesReturning_6fb1fd0c' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\CmdWithWithInsertCmdIntoXfullnameIdlistOptSelectUpsert_8f9aafcd' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\CmdWithWithUpdateOrconfXfullnameIndexedOptSetSetlistFromWhereOptRet_c2eca6e1' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\CmdlistWithCmdlistEcmd_d6dd245b' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\CollateWithCollateIds_8425b902' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\CollateWith_de5f77fb' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ColumnlistWithColumnlistCommaColumnnameCarglist_106fb537' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ColumnlistWithColumnnameCarglist_a318faf8' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ColumnnameWithNmTypetoken_92826a89' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ConslistOptWithCommaConslist_04f617dc' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ConslistOptWith_0b11f7d2' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ConslistWithConslistTconscommaTcons_c4260c11' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\CreateTableArgsWithAsSelect_edfabb86' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\CreateTableArgsWithLpColumnlistConslistOptRpTableOptionSet_9c826ddf' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\CreateTableWithCreatekwTempTableIfnotexistsNmDbnm_a2506378' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\CreateVtabWithCreatekwVirtualTableIfnotexistsNmDbnmUsingNm_51382012' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\DbnmWithDotNm_710678c7' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\DbnmWith_dce39c19' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\DeferSubclauseOptWith_34952d9b' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\DeferSubclauseWithDeferrableInitDeferredPredOpt_1dbafeef' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\DeferSubclauseWithNotDeferrableInitDeferredPredOpt_60b33c1f' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\EcmdWithCmdxSemi_b7577a8f' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\EcmdWithExplainCmdxSemi_177c493a' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\EcmdWithSemi_ed1109f6' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\EidlistOptWithLpEidlistRp_7b6e32ba' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\EidlistOptWith_c2a4c23e' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\EidlistWithEidlistCommaNmCollateSortorder_6ea64936' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\EidlistWithNmCollateSortorder_b27838a9' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ExprWithBitnotExpr_fb4e23b4' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ExprWithCaseCaseOperandCaseExprlistCaseElseEnd_f3c36399' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ExprWithCastLpExprAsTypetokenRp_15f33207' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ExprWithExistsLpSelectRp_c7d40730' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ExprWithExprAndExpr_33592aae' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ExprWithExprBetweenOpExprAndExpr_5e5d6d1b' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ExprWithExprBitandBitorLshiftRshiftExpr_67d895c2' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ExprWithExprCollateIds_f6a2b322' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ExprWithExprConcatExpr_2239f2bc' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ExprWithExprEqNeExpr_49d16f16' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ExprWithExprInOpLpExprlistRp_a0b7c2b5' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ExprWithExprInOpLpSelectRp_a20110e2' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ExprWithExprInOpNmDbnmParenExprlist_be04cc02' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ExprWithExprIsDistinctFromExpr_2d05c076' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ExprWithExprIsExpr_cfeb7fba' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ExprWithExprIsNotDistinctFromExpr_06cc5755' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ExprWithExprIsNotExpr_a631d709' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ExprWithExprIsnullNotnull_b1183766' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ExprWithExprLikeopExprEscapeExpr_5d4dd842' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ExprWithExprLikeopExpr_e761ed21' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ExprWithExprLtGtGeLeExpr_c64bb14c' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ExprWithExprNotNull_025d71af' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ExprWithExprOrExpr_fcc306b3' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ExprWithExprPlusMinusExpr_82e360dc' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ExprWithExprPtrExpr_6dab14bf' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ExprWithExprStarSlashRemExpr_6ca99fe8' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ExprWithIdjLpDistinctExprlistOrderBySortlistRpFilterOver_076d2e47' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ExprWithIdjLpDistinctExprlistOrderBySortlistRp_6aa5130a' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ExprWithIdjLpDistinctExprlistRpFilterOver_62523790' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ExprWithIdjLpDistinctExprlistRp_7162d1a1' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ExprWithIdjLpStarRpFilterOver_27a4a7eb' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ExprWithIdjLpStarRp_41781688' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ExprWithIdj_e1794d68' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ExprWithLpExprRp_ad646753' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ExprWithLpNexprlistCommaExprRp_b677307a' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ExprWithLpSelectRp_2c2be90a' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ExprWithNmDotNmDotNm_7d0c5b5a' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ExprWithNmDotNm_c54b4845' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ExprWithNotExpr_22095ba5' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ExprWithPlusMinusExpr_657f0f03' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ExprWithRaiseLpIgnoreRp_ccfbbaf2' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ExprWithRaiseLpRaisetypeCommaExprRp_5b2f59dd' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ExprWithVariable_0aa27fc0' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ExprlistWith_b354471e' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\FilterClauseWithFilterLpWhereExprRp_8633e3ce' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\FilterOverWithFilterClauseOverClause_2bea3cc5' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\FrameBoundEWithUnboundedFollowing_f324bf40' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\FrameBoundSWithUnboundedPreceding_3bf546a5' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\FrameBoundWithCurrentRow_9e076822' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\FrameBoundWithExprPrecedingFollowing_8e76d151' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\FrameExcludeOptWithExcludeFrameExclude_e06b1845' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\FrameExcludeOptWith_51524e1c' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\FrameExcludeWithCurrentRow_6eed7df3' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\FrameExcludeWithGroupTies_9fb942f2' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\FrameExcludeWithNoOthers_cc545c43' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\FrameOptWithRangeOrRowsBetweenFrameBoundSAndFrameBoundEFrameExcludeOpt_4d98dc77' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\FrameOptWithRangeOrRowsFrameBoundSFrameExcludeOpt_6d30675d' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\FrameOptWith_3ee819af' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\FromWithFromSeltablist_6e414a5b' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\FromWith_1d96487f' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\FullnameWithNmDotNm_4e1d9c77' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\GeneratedWithLpExprRpId_5d74118d' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\GeneratedWithLpExprRp_b1a94f09' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\GroupbyOptWithGroupByNexprlist_4a73c2cf' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\GroupbyOptWith_305dfc25' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\HavingOptWithHavingExpr_f311112e' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\HavingOptWith_cb82962d' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\IdlistOptWithLpIdlistRp_62ca8e2d' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\IdlistOptWith_1fa4fcd2' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\IdlistWithIdlistCommaNm_91e2994c' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\IndexedByWithIndexedByNm_70f3751d' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\IndexedByWithNotIndexed_d668bbbe' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\IndexedOptWith_f2a08353' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\InsertCmdWithInsertOrconf_17d8eea1' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\InsertCmdWithReplace_7e70f0cf' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\JoinopWithCommaJoin_2b032ba0' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\JoinopWithJoinKwJoin_4110763c' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\JoinopWithJoinKwNmJoin_869cddff' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\JoinopWithJoinKwNmNmJoin_bfbfa5b2' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\KeyOptWithKeyExpr_a14c915a' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\KeyOptWith_d69758aa' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\LikeopWithLikeKwMatch_1a9a5ee1' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\LikeopWithNotLikeKwMatch_e63ce34e' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\LimitOptWithLimitExprCommaExpr_1d4d2695' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\LimitOptWithLimitExprOffsetExpr_d2261940' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\LimitOptWithLimitExpr_b827c6a0' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\LimitOptWith_aab92ff6' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\MinusNumWithMinusNumber_9e51d37f' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\MultiselectOpWithExceptIntersect_f86e511a' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\MultiselectOpWithUnionAll_1d6b9617' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\MultiselectOpWithUnion_45e0b834' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\MvaluesWithMvaluesCommaLpNexprlistRp_fe975bc4' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\MvaluesWithValuesCommaLpNexprlistRp_cd8c14f9' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\NexprlistWithNexprlistCommaExpr_15af8daa' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\NmWithIdj_a2015ecf' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\NmWithString_4b1d9359' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\NmnumWithDefault_eda4f18c' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\NmnumWithDelete_0e682fa5' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\NmnumWithOn_2e23b74d' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\OnUsingWithOnExpr_b5a899fb' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\OnUsingWithUsingLpIdlistRp_691e2367' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\OnUsingWith_e9e4278d' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\OnconfWithOnConflictResolvetype_4edd828c' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\OnconfWith_28b2b21e' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\OneselectWithSelectDistinctSelcollistFromWhereOptGroupbyOptHavingOptOrderbyOptLimitOpt_218e0475' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\OneselectWithSelectDistinctSelcollistFromWhereOptGroupbyOptHavingOptWindowClauseOrderbyO_9a3dd714' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\OrconfWithOrResolvetype_f0ef4a84' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\OrconfWith_b80e7ae1' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\OrderbyOptWithOrderBySortlist_5aa58f40' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\OrderbyOptWith_87ddfe45' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\OverClauseWithOverLpWindowRp_f91aff11' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\OverClauseWithOverNm_34b90399' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ParenExprlistWithLpExprlistRp_6d8812f5' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ParenExprlistWith_f604e4a2' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\PlusNumWithNumber_52f2d00d' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\PlusNumWithPlusNumber_039178d8' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\RangeOrRowsWithRangeRowsGroups_a1c269da' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\RefargWithMatchNm_8834e4f9' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\RefargWithOnDeleteRefact_1b1d35b4' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\RefargWithOnInsertRefact_dedcfed8' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\RefargWithOnUpdateRefact_739fd957' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\RefargsWithRefargsRefarg_1dce60fb' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\RefargsWith_679d6942' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ResolvetypeWithIgnore_7fdbfe29' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ResolvetypeWithReplace_ee120ee4' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ReturningWithReturningSelcollist_e8199903' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ReturningWith_46f90fc5' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\SclpWithSelcollistComma_fd0bc772' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\SclpWith_2c42dcc1' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\SelcollistWithSclpScanptExprScanptAs_62f68771' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\SelcollistWithSclpScanptNmDotStar_bbe31973' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\SelcollistWithSclpScanptStar_bae6710f' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\SelectWithWithRecursiveWqlistSelectnowith_5f4629ff' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\SelectWithWithWqlistSelectnowith_dc3f10ec' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\SelectnowithWithSelectnowithMultiselectOpOneselect_7000656a' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\SeltablistWithStlPrefixLpSelectRpAsOnUsing_201b7267' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\SeltablistWithStlPrefixLpSeltablistRpAsOnUsing_e659a8d5' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\SeltablistWithStlPrefixNmDbnmAsIndexedByOnUsing_cb25a795' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\SeltablistWithStlPrefixNmDbnmAsOnUsing_848295d2' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\SeltablistWithStlPrefixNmDbnmLpExprlistRpAsOnUsing_8d2708de' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\SetlistWithLpIdlistRpEqExpr_1ebc160f' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\SetlistWithNmEqExpr_6216c267' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\SetlistWithSetlistCommaLpIdlistRpEqExpr_7f66f27b' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\SetlistWithSetlistCommaNmEqExpr_08ee1b3e' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\SortlistWithExprSortorderNulls_988a1693' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\SortlistWithSortlistCommaExprSortorderNulls_beac8704' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\StlPrefixWithSeltablistJoinop_d0edaade' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\StlPrefixWith_4d42bc16' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\TableOptionSetWithTableOptionSetCommaTableOption_ffea1324' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\TableOptionSetWith_cfb78063' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\TableOptionWithWithoutNm_d908fceb' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\TconsWithCheckLpExprRpOnconf_f04e4700' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\TconsWithConstraintNm_ca354ac2' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\TconsWithForeignKeyLpEidlistRpReferencesNmEidlistOptRefargsDeferSubclauseOpt_a2145070' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\TconsWithPrimaryKeyLpSortlistAutoincRpOnconf_724fc4cd' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\TconsWithUniqueLpSortlistRpOnconf_1bb4e282' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\TempWithTemp_af9945b3' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\TempWith_582c64db' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\TermWithCtimeKw_9aa2d016' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\TermWithInteger_298801b2' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\TermWithNullFloatBlob_0bfe6b30' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\TermWithQnumber_45fd67fa' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\TermWithString_e66cd9ed' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\TransOptWithTransactionNm_f694d58b' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\TransOptWithTransaction_ea573324' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\TransOptWith_6ac05548' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\TridxbyWithIndexedByNm_c201f940' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\TridxbyWithNotIndexed_6c190bec' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\TridxbyWith_da0128c6' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\TriggerCmdListWithTriggerCmdListTriggerCmdSemi_a3990e43' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\TriggerCmdListWithTriggerCmdSemi_34d876f1' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\TriggerCmdWithDeleteFromTrnmTridxbyWhereOptScanpt_587bfb70' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\TriggerCmdWithScanptInsertCmdIntoTrnmIdlistOptSelectUpsertScanpt_362fe131' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\TriggerCmdWithScanptSelectScanpt_2cdaedbb' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\TriggerCmdWithUpdateOrconfTrnmTridxbySetSetlistFromWhereOptScanpt_a7c2ea42' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\TriggerDeclWithTempTriggerIfnotexistsNmDbnmTriggerTimeTriggerEventOnFullnameForeachClauseW_09bb7d8c' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\TriggerEventWithDeleteInsert_67056f08' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\TriggerEventWithUpdateOfIdlist_1483bd2b' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\TriggerEventWithUpdate_6cc7e649' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\TriggerTimeWithBeforeAfter_fa3bc32b' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\TriggerTimeWithInsteadOf_85c866b5' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\TriggerTimeWith_053237f2' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\TrnmWithNmDotNm_3ea19d9c' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\TypenameWithIds_cf980f54' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\TypenameWithTypenameIds_bae45eaf' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\TypetokenWithTypenameLpSignedCommaSignedRp_f13470a9' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\TypetokenWithTypenameLpSignedRp_53bc47cf' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\TypetokenWith_6b66532f' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\UpsertWithOnConflictDoNothingReturning_162a31bb' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\UpsertWithOnConflictDoUpdateSetSetlistWhereOptReturning_18ff9ed4' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\UpsertWithOnConflictLpSortlistRpWhereOptDoNothingUpsert_820f0d71' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\UpsertWithOnConflictLpSortlistRpWhereOptDoUpdateSetSetlistWhereOptUpsert_b3d7f7ee' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\UpsertWithReturningSelcollist_c53e1ecb' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\UpsertWith_a11dcd45' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ValuesWithValuesLpNexprlistRp_eab5da94' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\VintoWithIntoExpr_bafc6484' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\VintoWith_b8f3b382' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\VtabargWithVtabargVtabargtoken_627d8ccd' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\VtabargWith_f1ee34eb' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\VtabarglistWithVtabarglistCommaVtabarg_297de28e' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\VtabargtokenWithAny_4183ebc7' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\VtabargtokenWithLpAnylistRp_95c44fdc' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\WhenClauseWithWhenExpr_6456c232' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\WhenClauseWith_c6e08bf6' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\WhereOptRetWithReturningSelcollist_f5e1123e' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\WhereOptRetWithWhereExprReturningSelcollist_679930c1' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\WhereOptRetWithWhereExpr_eede6fba' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\WhereOptRetWith_b0796d34' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\WhereOptWithWhereExpr_93445e09' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\WhereOptWith_765a2f1c' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\WindowClauseWithWindowWindowdefnList_0b8faffc' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\WindowWithNmFrameOpt_1ab36cb4' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\WindowWithNmOrderBySortlistFrameOpt_f01cd5ad' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\WindowWithNmPartitionByNexprlistOrderbyOptFrameOpt_8a8b5059' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\WindowWithOrderBySortlistFrameOpt_72d3f775' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\WindowWithPartitionByNexprlistOrderbyOptFrameOpt_1f69e129' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\WindowdefnListWithWindowdefnListCommaWindowdefn_384a44d1' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\WindowdefnWithNmAsLpWindowRp_10e246a1' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\WithWithWithRecursiveWqlist_4b8fcbef' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\WithWithWithWqlist_cbd69b56' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\WithWith_41afa5c9' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\WqitemWithWithnmEidlistOptWqasLpSelectRp_ba45400b' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\WqlistWithWqlistCommaWqitem_3ab99d95' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\XfullnameWithNmAsNm_0204e3b8' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\XfullnameWithNmDotNmAsNm_16c38d68' => true,
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\XfullnameWithNmDotNm_abe868cc' => true,
);
    /**
     * Generated construction facts; no parser is consulted by a value.
     *
     * @var array<string, string>
     */
    public const SPELLINGS = array (
  'ANY' => '~\\A(?:[A-Za-z_\\x80-\\xFF][A-Za-z_0-9$\\x80-\\xFF]*|"(?:[^"]|"")*"|`(?:[^`]|``)*`|\\[[^\\]]*\\]|\'(?:[^\']|\'\')*\'|[0-9]+|0[xX][0-9A-Fa-f]+|(?:[0-9]+\\.[0-9]*|\\.[0-9]+)(?:[eE][+-]?[0-9]+)?|[0-9]+[eE][+-]?[0-9]+|(?=[^ ]*_)(?:(?:[0-9](?:_?[0-9])*(?:\\.(?:[0-9](?:_?[0-9])*)?)?|\\.[0-9](?:_?[0-9])*)(?:[eE][+-]?[0-9](?:_?[0-9])*)?|0[xX][0-9A-Fa-f](?:_?[0-9A-Fa-f])*)|[xX]\'(?:[0-9A-Fa-f]{2})*\'|\\?[0-9]*|[:@$#](?=(?:::)*[A-Za-z_0-9$\\x80-\\xFF])(?:[A-Za-z_0-9$\\x80-\\xFF]|::)+(?:\\([^\\s)]*\\))?|;?|ABORT|ACTION|ADD|AFTER|ALL|ALTER|ALWAYS|ANALYZE|AND|AS|ASC|ATTACH|AUTOINCREMENT|BEFORE|BEGIN|BETWEEN|BY|CASCADE|CASE|CAST|CHECK|COLLATE|COLUMN|COMMIT|CONFLICT|CONSTRAINT|CREATE|CROSS|FULL|INNER|LEFT|NATURAL|OUTER|RIGHT|CURRENT|CURRENT_DATE|CURRENT_TIME|CURRENT_TIMESTAMP|DATABASE|DEFAULT|DEFERRABLE|DEFERRED|DELETE|DESC|DETACH|DISTINCT|DO|DROP|EACH|ELSE|END|ESCAPE|EXCEPT|EXCLUDE|EXCLUSIVE|EXISTS|EXPLAIN|FAIL|FILTER|FIRST|FOLLOWING|FOR|FOREIGN|FROM|GENERATED|GLOB|LIKE|REGEXP|GROUP|GROUPS|HAVING|IF|IGNORE|IMMEDIATE|IN|INDEX|INDEXED|INITIALLY|INSERT|INSTEAD|INTERSECT|INTO|IS|ISNULL|JOIN|KEY|LAST|LIMIT|MATCH|MATERIALIZED|NO|NOT|NOTHING|NOTNULL|NULL|NULLS|OF|OFFSET|ON|OR|ORDER|OTHERS|OVER|PARTITION|PLAN|PRAGMA|PRECEDING|PRIMARY|QUERY|RAISE|RANGE|RECURSIVE|REFERENCES|REINDEX|RELEASE|RENAME|REPLACE|RESTRICT|RETURNING|ROLLBACK|ROW|ROWS|SAVEPOINT|SELECT|SET|TABLE|TEMP|TEMPORARY|THEN|TIES|TO|TRANSACTION|TRIGGER|UNBOUNDED|UNION|UNIQUE|UPDATE|USING|VACUUM|VALUES|VIEW|VIRTUAL|WHEN|WHERE|WINDOW|WITH|WITHOUT|\\-\\>\\>|\\-\\>|\\|\\||\\=\\=|\\=|\\<\\=|\\<\\>|\\!\\=|\\>\\=|\\<\\<|\\>\\>|\\(|\\)|,|\\.|\\<|\\>|\\+|\\-|\\*|/|%|&|\\||\\~|COMMIT|END|[A-Za-z_\\x80-\\xFF][A-Za-z_0-9$\\x80-\\xFF]*|"(?:[^"]|"")*"|`(?:[^`]|``)*`|\\[[^\\]]*\\]|INDEXED|[A-Za-z_\\x80-\\xFF][A-Za-z_0-9$\\x80-\\xFF]*|"(?:[^"]|"")*"|`(?:[^`]|``)*`|\\[[^\\]]*\\]|\'(?:[^\']|\'\')*\'|[A-Za-z_\\x80-\\xFF][A-Za-z_0-9$\\x80-\\xFF]*|"(?:[^"]|"")*"|`(?:[^`]|``)*`|\\[[^\\]]*\\]|INDEXED|CROSS|FULL|INNER|LEFT|NATURAL|OUTER|RIGHT|EXCEPT|INTERSECT|,|JOIN|NULL|(?:[0-9]+\\.[0-9]*|\\.[0-9]+)(?:[eE][+-]?[0-9]+)?|[0-9]+[eE][+-]?[0-9]+|[xX]\'(?:[0-9A-Fa-f]{2})*\'|\\<|\\>|\\>\\=|\\<\\=|\\=\\=|\\=|\\<\\>|\\!\\=|&|\\||\\<\\<|\\>\\>|\\+|\\-|\\*|/|%|GLOB|LIKE|REGEXP|MATCH|ISNULL|NOTNULL|[0-9]+|0[xX][0-9A-Fa-f]+|(?:[0-9]+\\.[0-9]*|\\.[0-9]+)(?:[eE][+-]?[0-9]+)?|[0-9]+[eE][+-]?[0-9]+|BEFORE|AFTER|DELETE|INSERT|RANGE|ROWS|GROUPS|PRECEDING|FOLLOWING|GROUP|TIES)\\z~isD',
  'BEFORE|AFTER' => '~\\A(?:BEFORE|AFTER)\\z~isD',
  'BITAND|BITOR|LSHIFT|RSHIFT' => '~\\A(?:&|\\||\\<\\<|\\>\\>)\\z~isD',
  'COMMA|JOIN' => '~\\A(?:,|JOIN)\\z~isD',
  'COMMIT|END' => '~\\A(?:COMMIT|END)\\z~isD',
  'CTIME_KW' => '~\\A(?:CURRENT_DATE|CURRENT_TIME|CURRENT_TIMESTAMP)\\z~isD',
  'DELETE|INSERT' => '~\\A(?:DELETE|INSERT)\\z~isD',
  'EQ' => '~\\A(?:\\=\\=|\\=)\\z~isD',
  'EQ|NE' => '~\\A(?:\\=\\=|\\=|\\<\\>|\\!\\=)\\z~isD',
  'EXCEPT|INTERSECT' => '~\\A(?:EXCEPT|INTERSECT)\\z~isD',
  'GROUP|TIES' => '~\\A(?:GROUP|TIES)\\z~isD',
  'ID' => '~\\A(?:[A-Za-z_\\x80-\\xFF][A-Za-z_0-9$\\x80-\\xFF]*|"(?:[^"]|"")*"|`(?:[^`]|``)*`|\\[[^\\]]*\\])\\z~isD',
  'INTEGER' => '~\\A(?:[0-9]+|0[xX][0-9A-Fa-f]+)\\z~isD',
  'ISNULL|NOTNULL' => '~\\A(?:ISNULL|NOTNULL)\\z~isD',
  'JOIN_KW' => '~\\A(?:CROSS|FULL|INNER|LEFT|NATURAL|OUTER|RIGHT)\\z~isD',
  'LIKE_KW|MATCH' => '~\\A(?:GLOB|LIKE|REGEXP|MATCH)\\z~isD',
  'LT|GT|GE|LE' => '~\\A(?:\\<|\\>|\\>\\=|\\<\\=)\\z~isD',
  'NULL|FLOAT|BLOB' => '~\\A(?:NULL|(?:[0-9]+\\.[0-9]*|\\.[0-9]+)(?:[eE][+-]?[0-9]+)?|[0-9]+[eE][+-]?[0-9]+|[xX]\'(?:[0-9A-Fa-f]{2})*\')\\z~isD',
  'PLUS|MINUS' => '~\\A(?:\\+|\\-)\\z~isD',
  'PRECEDING|FOLLOWING' => '~\\A(?:PRECEDING|FOLLOWING)\\z~isD',
  'PTR' => '~\\A(?:\\-\\>\\>|\\-\\>)\\z~isD',
  'QNUMBER' => '~\\A(?:(?=[^ ]*_)(?:(?:[0-9](?:_?[0-9])*(?:\\.(?:[0-9](?:_?[0-9])*)?)?|\\.[0-9](?:_?[0-9])*)(?:[eE][+-]?[0-9](?:_?[0-9])*)?|0[xX][0-9A-Fa-f](?:_?[0-9A-Fa-f])*))\\z~isD',
  'RANGE|ROWS|GROUPS' => '~\\A(?:RANGE|ROWS|GROUPS)\\z~isD',
  'SEMI' => '~\\A(?:;?)\\z~isD',
  'STAR|SLASH|REM' => '~\\A(?:\\*|/|%)\\z~isD',
  'STRING' => '~\\A(?:\'(?:[^\']|\'\')*\')\\z~isD',
  'TEMP' => '~\\A(?:TEMP|TEMPORARY)\\z~isD',
  'VARIABLE' => '~\\A(?:\\?[0-9]*|[:@$#](?=(?:::)*[A-Za-z_0-9$\\x80-\\xFF])(?:[A-Za-z_0-9$\\x80-\\xFF]|::)+(?:\\([^\\s)]*\\))?)\\z~isD',
  'id' => '~\\A(?:[A-Za-z_\\x80-\\xFF][A-Za-z_0-9$\\x80-\\xFF]*|"(?:[^"]|"")*"|`(?:[^`]|``)*`|\\[[^\\]]*\\]|INDEXED)\\z~isD',
  'idj' => '~\\A(?:[A-Za-z_\\x80-\\xFF][A-Za-z_0-9$\\x80-\\xFF]*|"(?:[^"]|"")*"|`(?:[^`]|``)*`|\\[[^\\]]*\\]|INDEXED|CROSS|FULL|INNER|LEFT|NATURAL|OUTER|RIGHT)\\z~isD',
  'ids' => '~\\A(?:[A-Za-z_\\x80-\\xFF][A-Za-z_0-9$\\x80-\\xFF]*|"(?:[^"]|"")*"|`(?:[^`]|``)*`|\\[[^\\]]*\\]|\'(?:[^\']|\'\')*\')\\z~isD',
  'number' => '~\\A(?:[0-9]+|0[xX][0-9A-Fa-f]+|(?:[0-9]+\\.[0-9]*|\\.[0-9]+)(?:[eE][+-]?[0-9]+)?|[0-9]+[eE][+-]?[0-9]+)\\z~isD',
);
    /**
     * Generated construction facts; no parser is consulted by a value.
     *
     * @var array<class-string<\SqlSemantics\Statement\Element>, array<string, int>>
     */
    public const BINDING_POWERS = array (
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ExprWithBitnotExpr_fb4e23b4' =>
  array (
    'sqlite-3.47.2' => 12,
  ),
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ExprWithExprAndExpr_33592aae' =>
  array (
    'sqlite-3.47.2' => 2,
  ),
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ExprWithExprBetweenOpExprAndExpr_5e5d6d1b' =>
  array (
    'sqlite-3.47.2' => 4,
  ),
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ExprWithExprBitandBitorLshiftRshiftExpr_67d895c2' =>
  array (
    'sqlite-3.47.2' => 7,
  ),
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ExprWithExprCollateIds_f6a2b322' =>
  array (
    'sqlite-3.47.2' => 11,
  ),
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ExprWithExprConcatExpr_2239f2bc' =>
  array (
    'sqlite-3.47.2' => 10,
  ),
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ExprWithExprEqNeExpr_49d16f16' =>
  array (
    'sqlite-3.47.2' => 4,
  ),
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ExprWithExprInOpLpExprlistRp_a0b7c2b5' =>
  array (
    'sqlite-3.47.2' => 4,
  ),
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ExprWithExprInOpLpSelectRp_a20110e2' =>
  array (
    'sqlite-3.47.2' => 4,
  ),
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ExprWithExprInOpNmDbnmParenExprlist_be04cc02' =>
  array (
    'sqlite-3.47.2' => 4,
  ),
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ExprWithExprIsDistinctFromExpr_2d05c076' =>
  array (
    'sqlite-3.47.2' => 4,
  ),
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ExprWithExprIsExpr_cfeb7fba' =>
  array (
    'sqlite-3.47.2' => 4,
  ),
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ExprWithExprIsNotDistinctFromExpr_06cc5755' =>
  array (
    'sqlite-3.47.2' => 4,
  ),
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ExprWithExprIsNotExpr_a631d709' =>
  array (
    'sqlite-3.47.2' => 4,
  ),
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ExprWithExprIsnullNotnull_b1183766' =>
  array (
    'sqlite-3.47.2' => 4,
  ),
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ExprWithExprLikeopExprEscapeExpr_5d4dd842' =>
  array (
    'sqlite-3.47.2' => 4,
  ),
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ExprWithExprLikeopExpr_e761ed21' =>
  array (
    'sqlite-3.47.2' => 4,
  ),
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ExprWithExprLtGtGeLeExpr_c64bb14c' =>
  array (
    'sqlite-3.47.2' => 5,
  ),
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ExprWithExprNotNull_025d71af' =>
  array (
    'sqlite-3.47.2' => 3,
  ),
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ExprWithExprOrExpr_fcc306b3' =>
  array (
    'sqlite-3.47.2' => 1,
  ),
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ExprWithExprPlusMinusExpr_82e360dc' =>
  array (
    'sqlite-3.47.2' => 8,
  ),
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ExprWithExprPtrExpr_6dab14bf' =>
  array (
    'sqlite-3.47.2' => 10,
  ),
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ExprWithExprStarSlashRemExpr_6ca99fe8' =>
  array (
    'sqlite-3.47.2' => 9,
  ),
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ExprWithNotExpr_22095ba5' =>
  array (
    'sqlite-3.47.2' => 3,
  ),
  'SqlSemantics\\Statement\\Model\\Sqlite\\Value\\ExprWithPlusMinusExpr_657f0f03' =>
  array (
    'sqlite-3.47.2' => 12,
  ),
);

    /**
     * Answers whether a child belongs to this generated immutable vocabulary.
     */
    public static function contains(\SqlSemantics\Statement\Element $element): bool
    {
        return isset(self::ELEMENTS[$element::class]);
    }
}
