<?php

/**
 * The catalog of the storage engines, plugins, privileges, character sets and collations of a MySQL 8.4.7 server without extra plugins, as its SHOW statements list them.
 *
 * engines: SHOW ENGINES rows. plugins: SHOW PLUGINS rows. privileges: SHOW PRIVILEGES rows.
 * charsets: the description of each character set. collations: the sort length of each collation.
 * Read from a live 8.4.7 server.
 */

declare(strict_types=1);

return [
    'engines' => [
        ['ARCHIVE', 'YES', 'Archive storage engine', 'NO', 'NO', 'NO'],
        ['BLACKHOLE', 'YES', '/dev/null storage engine (anything you write to it disappears)', 'NO', 'NO', 'NO'],
        ['CSV', 'YES', 'CSV storage engine', 'NO', 'NO', 'NO'],
        ['FEDERATED', 'NO', 'Federated MySQL storage engine', null, null, null],
        ['InnoDB', 'DEFAULT', 'Supports transactions, row-level locking, and foreign keys', 'YES', 'YES', 'YES'],
        ['MEMORY', 'YES', 'Hash based, stored in memory, useful for temporary tables', 'NO', 'NO', 'NO'],
        ['MRG_MYISAM', 'YES', 'Collection of identical MyISAM tables', 'NO', 'NO', 'NO'],
        ['MyISAM', 'YES', 'MyISAM storage engine', 'NO', 'NO', 'NO'],
        ['ndbcluster', 'NO', 'Clustered, fault-tolerant tables', null, null, null],
        ['ndbinfo', 'NO', 'MySQL Cluster system information storage engine', null, null, null],
        ['PERFORMANCE_SCHEMA', 'YES', 'Performance Schema', 'NO', 'NO', 'NO'],
    ],
    'plugins' => [
        ['binlog', 'ACTIVE', 'STORAGE ENGINE', null, 'GPL'],
        ['sha256_password', 'ACTIVE', 'AUTHENTICATION', null, 'GPL'],
        ['caching_sha2_password', 'ACTIVE', 'AUTHENTICATION', null, 'GPL'],
        ['sha2_cache_cleaner', 'ACTIVE', 'AUDIT', null, 'GPL'],
        ['daemon_keyring_proxy_plugin', 'ACTIVE', 'DAEMON', null, 'GPL'],
        ['CSV', 'ACTIVE', 'STORAGE ENGINE', null, 'GPL'],
        ['MEMORY', 'ACTIVE', 'STORAGE ENGINE', null, 'GPL'],
        ['InnoDB', 'ACTIVE', 'STORAGE ENGINE', null, 'GPL'],
        ['INNODB_TRX', 'ACTIVE', 'INFORMATION SCHEMA', null, 'GPL'],
        ['INNODB_CMP', 'ACTIVE', 'INFORMATION SCHEMA', null, 'GPL'],
        ['INNODB_CMP_RESET', 'ACTIVE', 'INFORMATION SCHEMA', null, 'GPL'],
        ['INNODB_CMPMEM', 'ACTIVE', 'INFORMATION SCHEMA', null, 'GPL'],
        ['INNODB_CMPMEM_RESET', 'ACTIVE', 'INFORMATION SCHEMA', null, 'GPL'],
        ['INNODB_CMP_PER_INDEX', 'ACTIVE', 'INFORMATION SCHEMA', null, 'GPL'],
        ['INNODB_CMP_PER_INDEX_RESET', 'ACTIVE', 'INFORMATION SCHEMA', null, 'GPL'],
        ['INNODB_BUFFER_PAGE', 'ACTIVE', 'INFORMATION SCHEMA', null, 'GPL'],
        ['INNODB_BUFFER_PAGE_LRU', 'ACTIVE', 'INFORMATION SCHEMA', null, 'GPL'],
        ['INNODB_BUFFER_POOL_STATS', 'ACTIVE', 'INFORMATION SCHEMA', null, 'GPL'],
        ['INNODB_TEMP_TABLE_INFO', 'ACTIVE', 'INFORMATION SCHEMA', null, 'GPL'],
        ['INNODB_METRICS', 'ACTIVE', 'INFORMATION SCHEMA', null, 'GPL'],
        ['INNODB_FT_DEFAULT_STOPWORD', 'ACTIVE', 'INFORMATION SCHEMA', null, 'GPL'],
        ['INNODB_FT_DELETED', 'ACTIVE', 'INFORMATION SCHEMA', null, 'GPL'],
        ['INNODB_FT_BEING_DELETED', 'ACTIVE', 'INFORMATION SCHEMA', null, 'GPL'],
        ['INNODB_FT_CONFIG', 'ACTIVE', 'INFORMATION SCHEMA', null, 'GPL'],
        ['INNODB_FT_INDEX_CACHE', 'ACTIVE', 'INFORMATION SCHEMA', null, 'GPL'],
        ['INNODB_FT_INDEX_TABLE', 'ACTIVE', 'INFORMATION SCHEMA', null, 'GPL'],
        ['INNODB_TABLES', 'ACTIVE', 'INFORMATION SCHEMA', null, 'GPL'],
        ['INNODB_TABLESTATS', 'ACTIVE', 'INFORMATION SCHEMA', null, 'GPL'],
        ['INNODB_INDEXES', 'ACTIVE', 'INFORMATION SCHEMA', null, 'GPL'],
        ['INNODB_TABLESPACES', 'ACTIVE', 'INFORMATION SCHEMA', null, 'GPL'],
        ['INNODB_COLUMNS', 'ACTIVE', 'INFORMATION SCHEMA', null, 'GPL'],
        ['INNODB_VIRTUAL', 'ACTIVE', 'INFORMATION SCHEMA', null, 'GPL'],
        ['INNODB_CACHED_INDEXES', 'ACTIVE', 'INFORMATION SCHEMA', null, 'GPL'],
        ['INNODB_SESSION_TEMP_TABLESPACES', 'ACTIVE', 'INFORMATION SCHEMA', null, 'GPL'],
        ['MyISAM', 'ACTIVE', 'STORAGE ENGINE', null, 'GPL'],
        ['MRG_MYISAM', 'ACTIVE', 'STORAGE ENGINE', null, 'GPL'],
        ['PERFORMANCE_SCHEMA', 'ACTIVE', 'STORAGE ENGINE', null, 'GPL'],
        ['TempTable', 'ACTIVE', 'STORAGE ENGINE', null, 'GPL'],
        ['ARCHIVE', 'ACTIVE', 'STORAGE ENGINE', null, 'GPL'],
        ['BLACKHOLE', 'ACTIVE', 'STORAGE ENGINE', null, 'GPL'],
        ['FEDERATED', 'DISABLED', 'STORAGE ENGINE', null, 'GPL'],
        ['ndbcluster', 'DISABLED', 'STORAGE ENGINE', null, 'GPL'],
        ['ndbinfo', 'DISABLED', 'STORAGE ENGINE', null, 'GPL'],
        ['ndb_transid_mysql_connection_map', 'DISABLED', 'INFORMATION SCHEMA', null, 'GPL'],
        ['ngram', 'ACTIVE', 'FTPARSER', null, 'GPL'],
        ['mysqlx_cache_cleaner', 'ACTIVE', 'AUDIT', null, 'GPL'],
        ['mysqlx', 'ACTIVE', 'DAEMON', null, 'GPL'],
        ['mysql_native_password', 'DISABLED', 'AUTHENTICATION', null, 'GPL'],
    ],
    'privileges' => [
        ['Alter', 'Tables', 'To alter the table'],
        ['Alter routine', 'Functions,Procedures', 'To alter or drop stored functions/procedures'],
        ['Create', 'Databases,Tables,Indexes', 'To create new databases and tables'],
        ['Create routine', 'Databases', 'To use CREATE FUNCTION/PROCEDURE'],
        ['Create role', 'Server Admin', 'To create new roles'],
        ['Create temporary tables', 'Databases', 'To use CREATE TEMPORARY TABLE'],
        ['Create view', 'Tables', 'To create new views'],
        ['Create user', 'Server Admin', 'To create new users'],
        ['Delete', 'Tables', 'To delete existing rows'],
        ['Drop', 'Databases,Tables', 'To drop databases, tables, and views'],
        ['Drop role', 'Server Admin', 'To drop roles'],
        ['Event', 'Server Admin', 'To create, alter, drop and execute events'],
        ['Execute', 'Functions,Procedures', 'To execute stored routines'],
        ['File', 'File access on server', 'To read and write files on the server'],
        ['Grant option', 'Databases,Tables,Functions,Procedures', 'To give to other users those privileges you possess'],
        ['Index', 'Tables', 'To create or drop indexes'],
        ['Insert', 'Tables', 'To insert data into tables'],
        ['Lock tables', 'Databases', 'To use LOCK TABLES (together with SELECT privilege)'],
        ['Process', 'Server Admin', 'To view the plain text of currently executing queries'],
        ['Proxy', 'Server Admin', 'To make proxy user possible'],
        ['References', 'Databases,Tables', 'To have references on tables'],
        ['Reload', 'Server Admin', 'To reload or refresh tables, logs and privileges'],
        ['Replication client', 'Server Admin', 'To ask where the slave or master servers are'],
        ['Replication slave', 'Server Admin', 'To read binary log events from the master'],
        ['Select', 'Tables', 'To retrieve rows from table'],
        ['Show databases', 'Server Admin', 'To see all databases with SHOW DATABASES'],
        ['Show view', 'Tables', 'To see views with SHOW CREATE VIEW'],
        ['Shutdown', 'Server Admin', 'To shut down the server'],
        ['Super', 'Server Admin', 'To use KILL thread, SET GLOBAL, CHANGE REPLICATION SOURCE, etc.'],
        ['Trigger', 'Tables', 'To use triggers'],
        ['Create tablespace', 'Server Admin', 'To create/alter/drop tablespaces'],
        ['Update', 'Tables', 'To update existing rows'],
        ['Usage', 'Server Admin', 'No privileges - allow connect only'],
        ['AUDIT_ABORT_EXEMPT', 'Server Admin', ''],
        ['FIREWALL_EXEMPT', 'Server Admin', ''],
        ['OPTIMIZE_LOCAL_TABLE', 'Server Admin', ''],
        ['ALLOW_NONEXISTENT_DEFINER', 'Server Admin', ''],
        ['SET_ANY_DEFINER', 'Server Admin', ''],
        ['SENSITIVE_VARIABLES_OBSERVER', 'Server Admin', ''],
        ['AUTHENTICATION_POLICY_ADMIN', 'Server Admin', ''],
        ['GROUP_REPLICATION_STREAM', 'Server Admin', ''],
        ['FLUSH_PRIVILEGES', 'Server Admin', ''],
        ['XA_RECOVER_ADMIN', 'Server Admin', ''],
        ['CONNECTION_ADMIN', 'Server Admin', ''],
        ['CLONE_ADMIN', 'Server Admin', ''],
        ['ENCRYPTION_KEY_ADMIN', 'Server Admin', ''],
        ['INNODB_REDO_LOG_ARCHIVE', 'Server Admin', ''],
        ['SESSION_VARIABLES_ADMIN', 'Server Admin', ''],
        ['APPLICATION_PASSWORD_ADMIN', 'Server Admin', ''],
        ['REPLICATION_SLAVE_ADMIN', 'Server Admin', ''],
        ['BACKUP_ADMIN', 'Server Admin', ''],
        ['GROUP_REPLICATION_ADMIN', 'Server Admin', ''],
        ['SYSTEM_VARIABLES_ADMIN', 'Server Admin', ''],
        ['BINLOG_ADMIN', 'Server Admin', ''],
        ['PERSIST_RO_VARIABLES_ADMIN', 'Server Admin', ''],
        ['TRANSACTION_GTID_TAG', 'Server Admin', ''],
        ['PASSWORDLESS_USER_ADMIN', 'Server Admin', ''],
        ['ROLE_ADMIN', 'Server Admin', ''],
        ['INNODB_REDO_LOG_ENABLE', 'Server Admin', ''],
        ['RESOURCE_GROUP_USER', 'Server Admin', ''],
        ['BINLOG_ENCRYPTION_ADMIN', 'Server Admin', ''],
        ['SERVICE_CONNECTION_ADMIN', 'Server Admin', ''],
        ['SHOW_ROUTINE', 'Server Admin', ''],
        ['RESOURCE_GROUP_ADMIN', 'Server Admin', ''],
        ['SYSTEM_USER', 'Server Admin', ''],
        ['TABLE_ENCRYPTION_ADMIN', 'Server Admin', ''],
        ['TELEMETRY_LOG_ADMIN', 'Server Admin', ''],
        ['FLUSH_STATUS', 'Server Admin', ''],
        ['REPLICATION_APPLIER', 'Server Admin', ''],
        ['FLUSH_OPTIMIZER_COSTS', 'Server Admin', ''],
        ['AUDIT_ADMIN', 'Server Admin', ''],
        ['FLUSH_USER_RESOURCES', 'Server Admin', ''],
        ['FLUSH_TABLES', 'Server Admin', ''],
    ],
    'charsets' => [
        'armscii8' => 'ARMSCII-8 Armenian',
        'ascii' => 'US ASCII',
        'big5' => 'Big5 Traditional Chinese',
        'binary' => 'Binary pseudo charset',
        'cp1250' => 'Windows Central European',
        'cp1251' => 'Windows Cyrillic',
        'cp1256' => 'Windows Arabic',
        'cp1257' => 'Windows Baltic',
        'cp850' => 'DOS West European',
        'cp852' => 'DOS Central European',
        'cp866' => 'DOS Russian',
        'cp932' => 'SJIS for Windows Japanese',
        'dec8' => 'DEC West European',
        'eucjpms' => 'UJIS for Windows Japanese',
        'euckr' => 'EUC-KR Korean',
        'gb18030' => 'China National Standard GB18030',
        'gb2312' => 'GB2312 Simplified Chinese',
        'gbk' => 'GBK Simplified Chinese',
        'geostd8' => 'GEOSTD8 Georgian',
        'greek' => 'ISO 8859-7 Greek',
        'hebrew' => 'ISO 8859-8 Hebrew',
        'hp8' => 'HP West European',
        'keybcs2' => 'DOS Kamenicky Czech-Slovak',
        'koi8r' => 'KOI8-R Relcom Russian',
        'koi8u' => 'KOI8-U Ukrainian',
        'latin1' => 'cp1252 West European',
        'latin2' => 'ISO 8859-2 Central European',
        'latin5' => 'ISO 8859-9 Turkish',
        'latin7' => 'ISO 8859-13 Baltic',
        'macce' => 'Mac Central European',
        'macroman' => 'Mac West European',
        'sjis' => 'Shift-JIS Japanese',
        'swe7' => '7bit Swedish',
        'tis620' => 'TIS620 Thai',
        'ucs2' => 'UCS-2 Unicode',
        'ujis' => 'EUC-JP Japanese',
        'utf16' => 'UTF-16 Unicode',
        'utf16le' => 'UTF-16LE Unicode',
        'utf32' => 'UTF-32 Unicode',
        'utf8mb3' => 'UTF-8 Unicode',
        'utf8mb4' => 'UTF-8 Unicode',
    ],
    'collations' => [
        'armscii8_bin' => 1,
        'armscii8_general_ci' => 1,
        'ascii_bin' => 1,
        'ascii_general_ci' => 1,
        'big5_bin' => 1,
        'big5_chinese_ci' => 1,
        'binary' => 1,
        'cp1250_bin' => 1,
        'cp1250_croatian_ci' => 1,
        'cp1250_czech_cs' => 2,
        'cp1250_general_ci' => 1,
        'cp1250_polish_ci' => 1,
        'cp1251_bin' => 1,
        'cp1251_bulgarian_ci' => 1,
        'cp1251_general_ci' => 1,
        'cp1251_general_cs' => 1,
        'cp1251_ukrainian_ci' => 1,
        'cp1256_bin' => 1,
        'cp1256_general_ci' => 1,
        'cp1257_bin' => 1,
        'cp1257_general_ci' => 1,
        'cp1257_lithuanian_ci' => 1,
        'cp850_bin' => 1,
        'cp850_general_ci' => 1,
        'cp852_bin' => 1,
        'cp852_general_ci' => 1,
        'cp866_bin' => 1,
        'cp866_general_ci' => 1,
        'cp932_bin' => 1,
        'cp932_japanese_ci' => 1,
        'dec8_bin' => 1,
        'dec8_swedish_ci' => 1,
        'eucjpms_bin' => 1,
        'eucjpms_japanese_ci' => 1,
        'euckr_bin' => 1,
        'euckr_korean_ci' => 1,
        'gb18030_bin' => 1,
        'gb18030_chinese_ci' => 2,
        'gb18030_unicode_520_ci' => 8,
        'gb2312_bin' => 1,
        'gb2312_chinese_ci' => 1,
        'gbk_bin' => 1,
        'gbk_chinese_ci' => 1,
        'geostd8_bin' => 1,
        'geostd8_general_ci' => 1,
        'greek_bin' => 1,
        'greek_general_ci' => 1,
        'hebrew_bin' => 1,
        'hebrew_general_ci' => 1,
        'hp8_bin' => 1,
        'hp8_english_ci' => 1,
        'keybcs2_bin' => 1,
        'keybcs2_general_ci' => 1,
        'koi8r_bin' => 1,
        'koi8r_general_ci' => 1,
        'koi8u_bin' => 1,
        'koi8u_general_ci' => 1,
        'latin1_bin' => 1,
        'latin1_danish_ci' => 1,
        'latin1_general_ci' => 1,
        'latin1_general_cs' => 1,
        'latin1_german1_ci' => 1,
        'latin1_german2_ci' => 2,
        'latin1_spanish_ci' => 1,
        'latin1_swedish_ci' => 1,
        'latin2_bin' => 1,
        'latin2_croatian_ci' => 1,
        'latin2_czech_cs' => 4,
        'latin2_general_ci' => 1,
        'latin2_hungarian_ci' => 1,
        'latin5_bin' => 1,
        'latin5_turkish_ci' => 1,
        'latin7_bin' => 1,
        'latin7_estonian_cs' => 1,
        'latin7_general_ci' => 1,
        'latin7_general_cs' => 1,
        'macce_bin' => 1,
        'macce_general_ci' => 1,
        'macroman_bin' => 1,
        'macroman_general_ci' => 1,
        'sjis_bin' => 1,
        'sjis_japanese_ci' => 1,
        'swe7_bin' => 1,
        'swe7_swedish_ci' => 1,
        'tis620_bin' => 1,
        'tis620_thai_ci' => 4,
        'ucs2_bin' => 1,
        'ucs2_croatian_ci' => 8,
        'ucs2_czech_ci' => 8,
        'ucs2_danish_ci' => 8,
        'ucs2_esperanto_ci' => 8,
        'ucs2_estonian_ci' => 8,
        'ucs2_general_ci' => 1,
        'ucs2_general_mysql500_ci' => 1,
        'ucs2_german2_ci' => 8,
        'ucs2_hungarian_ci' => 8,
        'ucs2_icelandic_ci' => 8,
        'ucs2_latvian_ci' => 8,
        'ucs2_lithuanian_ci' => 8,
        'ucs2_persian_ci' => 8,
        'ucs2_polish_ci' => 8,
        'ucs2_romanian_ci' => 8,
        'ucs2_roman_ci' => 8,
        'ucs2_sinhala_ci' => 8,
        'ucs2_slovak_ci' => 8,
        'ucs2_slovenian_ci' => 8,
        'ucs2_spanish2_ci' => 8,
        'ucs2_spanish_ci' => 8,
        'ucs2_swedish_ci' => 8,
        'ucs2_turkish_ci' => 8,
        'ucs2_unicode_520_ci' => 8,
        'ucs2_unicode_ci' => 8,
        'ucs2_vietnamese_ci' => 8,
        'ujis_bin' => 1,
        'ujis_japanese_ci' => 1,
        'utf16le_bin' => 1,
        'utf16le_general_ci' => 1,
        'utf16_bin' => 1,
        'utf16_croatian_ci' => 8,
        'utf16_czech_ci' => 8,
        'utf16_danish_ci' => 8,
        'utf16_esperanto_ci' => 8,
        'utf16_estonian_ci' => 8,
        'utf16_general_ci' => 1,
        'utf16_german2_ci' => 8,
        'utf16_hungarian_ci' => 8,
        'utf16_icelandic_ci' => 8,
        'utf16_latvian_ci' => 8,
        'utf16_lithuanian_ci' => 8,
        'utf16_persian_ci' => 8,
        'utf16_polish_ci' => 8,
        'utf16_romanian_ci' => 8,
        'utf16_roman_ci' => 8,
        'utf16_sinhala_ci' => 8,
        'utf16_slovak_ci' => 8,
        'utf16_slovenian_ci' => 8,
        'utf16_spanish2_ci' => 8,
        'utf16_spanish_ci' => 8,
        'utf16_swedish_ci' => 8,
        'utf16_turkish_ci' => 8,
        'utf16_unicode_520_ci' => 8,
        'utf16_unicode_ci' => 8,
        'utf16_vietnamese_ci' => 8,
        'utf32_bin' => 1,
        'utf32_croatian_ci' => 8,
        'utf32_czech_ci' => 8,
        'utf32_danish_ci' => 8,
        'utf32_esperanto_ci' => 8,
        'utf32_estonian_ci' => 8,
        'utf32_general_ci' => 1,
        'utf32_german2_ci' => 8,
        'utf32_hungarian_ci' => 8,
        'utf32_icelandic_ci' => 8,
        'utf32_latvian_ci' => 8,
        'utf32_lithuanian_ci' => 8,
        'utf32_persian_ci' => 8,
        'utf32_polish_ci' => 8,
        'utf32_romanian_ci' => 8,
        'utf32_roman_ci' => 8,
        'utf32_sinhala_ci' => 8,
        'utf32_slovak_ci' => 8,
        'utf32_slovenian_ci' => 8,
        'utf32_spanish2_ci' => 8,
        'utf32_spanish_ci' => 8,
        'utf32_swedish_ci' => 8,
        'utf32_turkish_ci' => 8,
        'utf32_unicode_520_ci' => 8,
        'utf32_unicode_ci' => 8,
        'utf32_vietnamese_ci' => 8,
        'utf8mb3_bin' => 1,
        'utf8mb3_croatian_ci' => 8,
        'utf8mb3_czech_ci' => 8,
        'utf8mb3_danish_ci' => 8,
        'utf8mb3_esperanto_ci' => 8,
        'utf8mb3_estonian_ci' => 8,
        'utf8mb3_general_ci' => 1,
        'utf8mb3_general_mysql500_ci' => 1,
        'utf8mb3_german2_ci' => 8,
        'utf8mb3_hungarian_ci' => 8,
        'utf8mb3_icelandic_ci' => 8,
        'utf8mb3_latvian_ci' => 8,
        'utf8mb3_lithuanian_ci' => 8,
        'utf8mb3_persian_ci' => 8,
        'utf8mb3_polish_ci' => 8,
        'utf8mb3_romanian_ci' => 8,
        'utf8mb3_roman_ci' => 8,
        'utf8mb3_sinhala_ci' => 8,
        'utf8mb3_slovak_ci' => 8,
        'utf8mb3_slovenian_ci' => 8,
        'utf8mb3_spanish2_ci' => 8,
        'utf8mb3_spanish_ci' => 8,
        'utf8mb3_swedish_ci' => 8,
        'utf8mb3_tolower_ci' => 1,
        'utf8mb3_turkish_ci' => 8,
        'utf8mb3_unicode_520_ci' => 8,
        'utf8mb3_unicode_ci' => 8,
        'utf8mb3_vietnamese_ci' => 8,
        'utf8mb4_0900_ai_ci' => 0,
        'utf8mb4_0900_as_ci' => 0,
        'utf8mb4_0900_as_cs' => 0,
        'utf8mb4_0900_bin' => 1,
        'utf8mb4_bg_0900_ai_ci' => 0,
        'utf8mb4_bg_0900_as_cs' => 0,
        'utf8mb4_bin' => 1,
        'utf8mb4_bs_0900_ai_ci' => 0,
        'utf8mb4_bs_0900_as_cs' => 0,
        'utf8mb4_croatian_ci' => 8,
        'utf8mb4_cs_0900_ai_ci' => 0,
        'utf8mb4_cs_0900_as_cs' => 0,
        'utf8mb4_czech_ci' => 8,
        'utf8mb4_danish_ci' => 8,
        'utf8mb4_da_0900_ai_ci' => 0,
        'utf8mb4_da_0900_as_cs' => 0,
        'utf8mb4_de_pb_0900_ai_ci' => 0,
        'utf8mb4_de_pb_0900_as_cs' => 0,
        'utf8mb4_eo_0900_ai_ci' => 0,
        'utf8mb4_eo_0900_as_cs' => 0,
        'utf8mb4_esperanto_ci' => 8,
        'utf8mb4_estonian_ci' => 8,
        'utf8mb4_es_0900_ai_ci' => 0,
        'utf8mb4_es_0900_as_cs' => 0,
        'utf8mb4_es_trad_0900_ai_ci' => 0,
        'utf8mb4_es_trad_0900_as_cs' => 0,
        'utf8mb4_et_0900_ai_ci' => 0,
        'utf8mb4_et_0900_as_cs' => 0,
        'utf8mb4_general_ci' => 1,
        'utf8mb4_german2_ci' => 8,
        'utf8mb4_gl_0900_ai_ci' => 0,
        'utf8mb4_gl_0900_as_cs' => 0,
        'utf8mb4_hr_0900_ai_ci' => 0,
        'utf8mb4_hr_0900_as_cs' => 0,
        'utf8mb4_hungarian_ci' => 8,
        'utf8mb4_hu_0900_ai_ci' => 0,
        'utf8mb4_hu_0900_as_cs' => 0,
        'utf8mb4_icelandic_ci' => 8,
        'utf8mb4_is_0900_ai_ci' => 0,
        'utf8mb4_is_0900_as_cs' => 0,
        'utf8mb4_ja_0900_as_cs' => 0,
        'utf8mb4_ja_0900_as_cs_ks' => 24,
        'utf8mb4_latvian_ci' => 8,
        'utf8mb4_la_0900_ai_ci' => 0,
        'utf8mb4_la_0900_as_cs' => 0,
        'utf8mb4_lithuanian_ci' => 8,
        'utf8mb4_lt_0900_ai_ci' => 0,
        'utf8mb4_lt_0900_as_cs' => 0,
        'utf8mb4_lv_0900_ai_ci' => 0,
        'utf8mb4_lv_0900_as_cs' => 0,
        'utf8mb4_mn_cyrl_0900_ai_ci' => 0,
        'utf8mb4_mn_cyrl_0900_as_cs' => 0,
        'utf8mb4_nb_0900_ai_ci' => 0,
        'utf8mb4_nb_0900_as_cs' => 0,
        'utf8mb4_nn_0900_ai_ci' => 0,
        'utf8mb4_nn_0900_as_cs' => 0,
        'utf8mb4_persian_ci' => 8,
        'utf8mb4_pl_0900_ai_ci' => 0,
        'utf8mb4_pl_0900_as_cs' => 0,
        'utf8mb4_polish_ci' => 8,
        'utf8mb4_romanian_ci' => 8,
        'utf8mb4_roman_ci' => 8,
        'utf8mb4_ro_0900_ai_ci' => 0,
        'utf8mb4_ro_0900_as_cs' => 0,
        'utf8mb4_ru_0900_ai_ci' => 0,
        'utf8mb4_ru_0900_as_cs' => 0,
        'utf8mb4_sinhala_ci' => 8,
        'utf8mb4_sk_0900_ai_ci' => 0,
        'utf8mb4_sk_0900_as_cs' => 0,
        'utf8mb4_slovak_ci' => 8,
        'utf8mb4_slovenian_ci' => 8,
        'utf8mb4_sl_0900_ai_ci' => 0,
        'utf8mb4_sl_0900_as_cs' => 0,
        'utf8mb4_spanish2_ci' => 8,
        'utf8mb4_spanish_ci' => 8,
        'utf8mb4_sr_latn_0900_ai_ci' => 0,
        'utf8mb4_sr_latn_0900_as_cs' => 0,
        'utf8mb4_sv_0900_ai_ci' => 0,
        'utf8mb4_sv_0900_as_cs' => 0,
        'utf8mb4_swedish_ci' => 8,
        'utf8mb4_tr_0900_ai_ci' => 0,
        'utf8mb4_tr_0900_as_cs' => 0,
        'utf8mb4_turkish_ci' => 8,
        'utf8mb4_unicode_520_ci' => 8,
        'utf8mb4_unicode_ci' => 8,
        'utf8mb4_vietnamese_ci' => 8,
        'utf8mb4_vi_0900_ai_ci' => 0,
        'utf8mb4_vi_0900_as_cs' => 0,
        'utf8mb4_zh_0900_as_cs' => 0,
    ],
];
