<?php

declare(strict_types=1);

namespace SqlSemantics\Platform\MySql\Lowering\Dispatch;

/**
 * Names the family that lowers each alternative of the statement rules.
 *
 * Rule: MYSQL-STATEMENT-ROUTES-001. Scope: statement (5.6, 5.7) and
 * simple_statement (8.0 and later). Every alternative is a unit production
 * whose only symbol is the rule of one statement; the table names the
 * family that owns that rule in the family plan. The tables are generated
 * from the plan and cover every alternative of every shipped release.
 * Terminates: one table lookup. Status: Implemented.
 *
 * @visibility SqlSemantics\Platform\MySql
 */
final class StatementRoutes
{
    /**
     * The productions of the rule `statement` of MySQL 5.6 and 5.7.
     */
    private const LEGACY = [
        'statement: alter' => Family::Definition,
        'statement: analyze' => Family::Server,
        'statement: binlog_base64_event' => Family::Replication,
        'statement: call' => Family::Dml,
        'statement: change' => Family::Replication,
        'statement: check' => Family::Server,
        'statement: checksum' => Family::Server,
        'statement: commit' => Family::Server,
        'statement: create' => Family::Definition,
        'statement: deallocate' => Family::Dml,
        'statement: delete' => Family::Dml,
        'statement: describe' => Family::Utility,
        'statement: do' => Family::Dml,
        'statement: drop' => Family::Definition,
        'statement: execute' => Family::Dml,
        'statement: flush' => Family::Server,
        'statement: get_diagnostics' => Family::Routine,
        'statement: grant' => Family::Account,
        'statement: handler' => Family::Dml,
        'statement: help' => Family::Utility,
        'statement: insert' => Family::Dml,
        'statement: install' => Family::Server,
        'statement: kill' => Family::Server,
        'statement: load' => Family::Dml,
        'statement: lock' => Family::Server,
        'statement: optimize' => Family::Server,
        'statement: keycache' => Family::Server,
        'statement: partition_entry' => Family::TableChange,
        'statement: preload' => Family::Server,
        'statement: prepare' => Family::Dml,
        'statement: purge' => Family::Replication,
        'statement: release' => Family::Server,
        'statement: rename' => Family::TableChange,
        'statement: repair' => Family::Server,
        'statement: replace' => Family::Dml,
        'statement: reset' => Family::Replication,
        'statement: resignal_stmt' => Family::Routine,
        'statement: revoke' => Family::Account,
        'statement: rollback' => Family::Server,
        'statement: savepoint' => Family::Server,
        'statement: select' => Family::Query,
        'statement: set' => Family::Utility,
        'statement: signal_stmt' => Family::Routine,
        'statement: show' => Family::Utility,
        'statement: slave' => Family::Replication,
        'statement: start' => Family::Server,
        'statement: truncate' => Family::TableChange,
        'statement: uninstall' => Family::Server,
        'statement: unlock' => Family::Server,
        'statement: update' => Family::Dml,
        'statement: use' => Family::Utility,
        'statement: xa' => Family::Server,
        'statement: delete_stmt' => Family::Dml,
        'statement: do_stmt' => Family::Dml,
        'statement: group_replication' => Family::Replication,
        'statement: insert_stmt' => Family::Dml,
        'statement: parse_gcol_expr' => Family::TableDefinition,
        'statement: replace_stmt' => Family::Dml,
        'statement: shutdown_stmt' => Family::Server,
        'statement: update_stmt' => Family::Dml,
    ];

    /**
     * The productions of the rule `simple_statement` of MySQL 8.0 and later.
     */
    private const MODERN = [
        'simple_statement: alter_database_stmt' => Family::Server,
        'simple_statement: alter_event_stmt' => Family::Routine,
        'simple_statement: alter_function_stmt' => Family::Routine,
        'simple_statement: alter_instance_stmt' => Family::Server,
        'simple_statement: alter_logfile_stmt' => Family::Server,
        'simple_statement: alter_procedure_stmt' => Family::Routine,
        'simple_statement: alter_resource_group_stmt' => Family::Account,
        'simple_statement: alter_server_stmt' => Family::Server,
        'simple_statement: alter_tablespace_stmt' => Family::Server,
        'simple_statement: alter_undo_tablespace_stmt' => Family::Server,
        'simple_statement: alter_table_stmt' => Family::TableChange,
        'simple_statement: alter_user_stmt' => Family::Account,
        'simple_statement: alter_view_stmt' => Family::TableDefinition,
        'simple_statement: analyze_table_stmt' => Family::Server,
        'simple_statement: binlog_base64_event' => Family::Replication,
        'simple_statement: call_stmt' => Family::Dml,
        'simple_statement: change' => Family::Replication,
        'simple_statement: check_table_stmt' => Family::Server,
        'simple_statement: checksum' => Family::Server,
        'simple_statement: clone_stmt' => Family::Server,
        'simple_statement: commit' => Family::Server,
        'simple_statement: create' => Family::Definition,
        'simple_statement: create_index_stmt' => Family::TableDefinition,
        'simple_statement: create_resource_group_stmt' => Family::Account,
        'simple_statement: create_role_stmt' => Family::Account,
        'simple_statement: create_srs_stmt' => Family::Server,
        'simple_statement: create_table_stmt' => Family::TableDefinition,
        'simple_statement: deallocate' => Family::Dml,
        'simple_statement: delete_stmt' => Family::Dml,
        'simple_statement: describe_stmt' => Family::Utility,
        'simple_statement: do_stmt' => Family::Dml,
        'simple_statement: drop_database_stmt' => Family::Server,
        'simple_statement: drop_event_stmt' => Family::Routine,
        'simple_statement: drop_function_stmt' => Family::Routine,
        'simple_statement: drop_index_stmt' => Family::TableChange,
        'simple_statement: drop_logfile_stmt' => Family::Server,
        'simple_statement: drop_procedure_stmt' => Family::Routine,
        'simple_statement: drop_resource_group_stmt' => Family::Account,
        'simple_statement: drop_role_stmt' => Family::Account,
        'simple_statement: drop_server_stmt' => Family::Server,
        'simple_statement: drop_srs_stmt' => Family::Server,
        'simple_statement: drop_tablespace_stmt' => Family::Server,
        'simple_statement: drop_undo_tablespace_stmt' => Family::Server,
        'simple_statement: drop_table_stmt' => Family::TableChange,
        'simple_statement: drop_trigger_stmt' => Family::Routine,
        'simple_statement: drop_user_stmt' => Family::Account,
        'simple_statement: drop_view_stmt' => Family::TableDefinition,
        'simple_statement: execute' => Family::Dml,
        'simple_statement: explain_stmt' => Family::Utility,
        'simple_statement: flush' => Family::Server,
        'simple_statement: get_diagnostics' => Family::Routine,
        'simple_statement: group_replication' => Family::Replication,
        'simple_statement: grant' => Family::Account,
        'simple_statement: handler_stmt' => Family::Dml,
        'simple_statement: help' => Family::Utility,
        'simple_statement: import_stmt' => Family::Dml,
        'simple_statement: insert_stmt' => Family::Dml,
        'simple_statement: install_stmt' => Family::Server,
        'simple_statement: kill' => Family::Server,
        'simple_statement: load_stmt' => Family::Dml,
        'simple_statement: lock' => Family::Server,
        'simple_statement: optimize_table_stmt' => Family::Server,
        'simple_statement: keycache_stmt' => Family::Server,
        'simple_statement: preload_stmt' => Family::Server,
        'simple_statement: prepare' => Family::Dml,
        'simple_statement: purge' => Family::Replication,
        'simple_statement: release' => Family::Server,
        'simple_statement: rename' => Family::TableChange,
        'simple_statement: repair_table_stmt' => Family::Server,
        'simple_statement: replace_stmt' => Family::Dml,
        'simple_statement: reset' => Family::Replication,
        'simple_statement: resignal_stmt' => Family::Routine,
        'simple_statement: restart_server_stmt' => Family::Server,
        'simple_statement: revoke' => Family::Account,
        'simple_statement: rollback' => Family::Server,
        'simple_statement: savepoint' => Family::Server,
        'simple_statement: select_stmt' => Family::Query,
        'simple_statement: set' => Family::Utility,
        'simple_statement: set_resource_group_stmt' => Family::Account,
        'simple_statement: set_role_stmt' => Family::Account,
        'simple_statement: show_binary_logs_stmt' => Family::Utility,
        'simple_statement: show_binlog_events_stmt' => Family::Utility,
        'simple_statement: show_character_set_stmt' => Family::Utility,
        'simple_statement: show_collation_stmt' => Family::Utility,
        'simple_statement: show_columns_stmt' => Family::Utility,
        'simple_statement: show_count_errors_stmt' => Family::Utility,
        'simple_statement: show_count_warnings_stmt' => Family::Utility,
        'simple_statement: show_create_database_stmt' => Family::Utility,
        'simple_statement: show_create_event_stmt' => Family::Utility,
        'simple_statement: show_create_function_stmt' => Family::Utility,
        'simple_statement: show_create_procedure_stmt' => Family::Utility,
        'simple_statement: show_create_table_stmt' => Family::Utility,
        'simple_statement: show_create_trigger_stmt' => Family::Utility,
        'simple_statement: show_create_user_stmt' => Family::Utility,
        'simple_statement: show_create_view_stmt' => Family::Utility,
        'simple_statement: show_databases_stmt' => Family::Utility,
        'simple_statement: show_engine_logs_stmt' => Family::Utility,
        'simple_statement: show_engine_mutex_stmt' => Family::Utility,
        'simple_statement: show_engine_status_stmt' => Family::Utility,
        'simple_statement: show_engines_stmt' => Family::Utility,
        'simple_statement: show_errors_stmt' => Family::Utility,
        'simple_statement: show_events_stmt' => Family::Utility,
        'simple_statement: show_function_code_stmt' => Family::Utility,
        'simple_statement: show_function_status_stmt' => Family::Utility,
        'simple_statement: show_grants_stmt' => Family::Utility,
        'simple_statement: show_keys_stmt' => Family::Utility,
        'simple_statement: show_master_status_stmt' => Family::Utility,
        'simple_statement: show_open_tables_stmt' => Family::Utility,
        'simple_statement: show_plugins_stmt' => Family::Utility,
        'simple_statement: show_privileges_stmt' => Family::Utility,
        'simple_statement: show_procedure_code_stmt' => Family::Utility,
        'simple_statement: show_procedure_status_stmt' => Family::Utility,
        'simple_statement: show_processlist_stmt' => Family::Utility,
        'simple_statement: show_profile_stmt' => Family::Utility,
        'simple_statement: show_profiles_stmt' => Family::Utility,
        'simple_statement: show_relaylog_events_stmt' => Family::Utility,
        'simple_statement: show_replica_status_stmt' => Family::Utility,
        'simple_statement: show_replicas_stmt' => Family::Utility,
        'simple_statement: show_status_stmt' => Family::Utility,
        'simple_statement: show_table_status_stmt' => Family::Utility,
        'simple_statement: show_tables_stmt' => Family::Utility,
        'simple_statement: show_triggers_stmt' => Family::Utility,
        'simple_statement: show_variables_stmt' => Family::Utility,
        'simple_statement: show_warnings_stmt' => Family::Utility,
        'simple_statement: shutdown_stmt' => Family::Server,
        'simple_statement: signal_stmt' => Family::Routine,
        'simple_statement: start' => Family::Server,
        'simple_statement: start_replica_stmt' => Family::Replication,
        'simple_statement: stop_replica_stmt' => Family::Replication,
        'simple_statement: truncate_stmt' => Family::TableChange,
        'simple_statement: uninstall' => Family::Server,
        'simple_statement: unlock' => Family::Server,
        'simple_statement: update_stmt' => Family::Dml,
        'simple_statement: use' => Family::Utility,
        'simple_statement: xa' => Family::Server,
        'simple_statement: show_parse_tree_stmt' => Family::Utility,
        'simple_statement: show_binary_log_status_stmt' => Family::Utility,
        'simple_statement: change_replication_stmt' => Family::Replication,
    ];

    /**
     * Answers the family of a statement production, or null when the production is not a statement alternative.
     */
    public function family(string $signature): ?Family
    {
        return self::LEGACY[$signature] ?? self::MODERN[$signature] ?? null;
    }
}
