<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\PostgreSql\Choice;

/**
 * The json_quotes_clause_opt SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\PostgreSql\Choice\JsonQuotesClauseOptChoice_a08439ee $value): string => (new \SqlSemantics\Statement\Statement($value))->toString();
 *     $write instanceof \Closure // => true
 */
enum JsonQuotesClauseOptChoice_a08439ee: string implements \SqlSemantics\Statement\Model\PostgreSql\Role\JsonQuotesClauseOptForm
{
    case UseKeepQuotesOnScalarString_dcaf4d1c = 'KEEP QUOTES ON SCALAR STRING';
    case UseKeepQuotes_f2e52cc1 = 'KEEP QUOTES';
    case UseOmitQuotesOnScalarString_e94300a4 = 'OMIT QUOTES ON SCALAR STRING';
    case UseOmitQuotes_dd07b4e8 = 'OMIT QUOTES';
    case Use_e3b0c442 = '';

    /**
     * Writes the selected SQL option.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        foreach (explode(' ', $this->value) as $word) {
            $writer->append($word);
        }
    }
}
