<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\PostgreSql\Choice;

/**
 * The xml_whitespace_option SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\PostgreSql\Choice\XmlWhitespaceOptionChoice_a283f890 $value): string => (new \SqlSemantics\Statement\Statement($value))->toString();
 *     $write instanceof \Closure // => true
 */
enum XmlWhitespaceOptionChoice_a283f890: string implements \SqlSemantics\Statement\Model\PostgreSql\Role\XmlWhitespaceOptionForm
{
    case UsePreserveWhitespace_972b353f = 'PRESERVE WHITESPACE';
    case UseStripWhitespace_2d305f5f = 'STRIP WHITESPACE';
    case Use_e3b0c442 = '';

    /**
     * Writes the selected SQL option.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        foreach (explode(' ', $this->value) as $word) {
            $writer->append($word);
        }
    }
}
