<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\Sqlite\Value;

/**
 * The cmd SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\Sqlite\Value\CmdWithCreatekwTempViewIfnotexistsNmDbnmEidlistOptAsSelect_982c3d9a $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class CmdWithCreatekwTempViewIfnotexistsNmDbnmEidlistOptAsSelect_982c3d9a implements \SqlSemantics\Statement\Model\Sqlite\Role\CmdForm, \SqlSemantics\Statement\Model\Sqlite\Role\CmdxForm, \SqlSemantics\Statement\Command
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form; comments are kept by the position of the symbol each precedes.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\Sqlite\Role\CreatekwForm $createkw,
        public readonly \SqlSemantics\Statement\Model\Sqlite\Role\TempForm $temp,
        public readonly \SqlSemantics\Statement\Model\Sqlite\Role\IfnotexistsForm $ifnotexists,
        public readonly \SqlSemantics\Statement\Model\Sqlite\Role\NmForm $nm,
        public readonly \SqlSemantics\Statement\Model\Sqlite\Role\DbnmForm $dbnm,
        public readonly \SqlSemantics\Statement\Model\Sqlite\Role\EidlistOptForm $eidlistOpt,
        public readonly \SqlSemantics\Statement\Model\Sqlite\Role\SelectForm $select,
        public readonly \SqlSemantics\Statement\Comments $comments = new \SqlSemantics\Statement\Comments(),
    ) {
        $this->assert(\SqlSemantics\Statement\Model\Sqlite\Contract\Contracts::contains($createkw), 'The createkw must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\Sqlite\Contract\Contracts::contains($temp), 'The temp must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\Sqlite\Contract\Contracts::contains($ifnotexists), 'The ifnotexists must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\Sqlite\Contract\Contracts::contains($nm), 'The nm must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\Sqlite\Contract\Contracts::contains($dbnm), 'The dbnm must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\Sqlite\Contract\Contracts::contains($eidlistOpt), 'The eidlistOpt must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\Sqlite\Contract\Contracts::contains($select), 'The select must be a generated immutable SQL value.');
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->comments($this->comments, 0);
        $this->createkw->write($writer);
        $writer->comments($this->comments, 1);
        $this->temp->write($writer);
        $writer->comments($this->comments, 2);
        $writer->append('VIEW');
        $writer->comments($this->comments, 3);
        $this->ifnotexists->write($writer);
        $writer->comments($this->comments, 4);
        $this->nm->write($writer);
        $writer->comments($this->comments, 5);
        $this->dbnm->write($writer);
        $writer->comments($this->comments, 6);
        $this->eidlistOpt->write($writer);
        $writer->comments($this->comments, 7);
        $writer->append('AS');
        $writer->comments($this->comments, 8);
        $this->select->write($writer);
    }

    /**
     * Returns a copy with a new createkw, preserving every other field.
     */
    public function withCreatekw(\SqlSemantics\Statement\Model\Sqlite\Role\CreatekwForm $createkw): self
    {
        return new self($createkw, $this->temp, $this->ifnotexists, $this->nm, $this->dbnm, $this->eidlistOpt, $this->select, $this->comments);
    }

    /**
     * Returns a copy with a new temp, preserving every other field.
     */
    public function withTemp(\SqlSemantics\Statement\Model\Sqlite\Role\TempForm $temp): self
    {
        return new self($this->createkw, $temp, $this->ifnotexists, $this->nm, $this->dbnm, $this->eidlistOpt, $this->select, $this->comments);
    }

    /**
     * Returns a copy with a new ifnotexists, preserving every other field.
     */
    public function withIfnotexists(\SqlSemantics\Statement\Model\Sqlite\Role\IfnotexistsForm $ifnotexists): self
    {
        return new self($this->createkw, $this->temp, $ifnotexists, $this->nm, $this->dbnm, $this->eidlistOpt, $this->select, $this->comments);
    }

    /**
     * Returns a copy with a new nm, preserving every other field.
     */
    public function withNm(\SqlSemantics\Statement\Model\Sqlite\Role\NmForm $nm): self
    {
        return new self($this->createkw, $this->temp, $this->ifnotexists, $nm, $this->dbnm, $this->eidlistOpt, $this->select, $this->comments);
    }

    /**
     * Returns a copy with a new dbnm, preserving every other field.
     */
    public function withDbnm(\SqlSemantics\Statement\Model\Sqlite\Role\DbnmForm $dbnm): self
    {
        return new self($this->createkw, $this->temp, $this->ifnotexists, $this->nm, $dbnm, $this->eidlistOpt, $this->select, $this->comments);
    }

    /**
     * Returns a copy with a new eidlistOpt, preserving every other field.
     */
    public function withEidlistOpt(\SqlSemantics\Statement\Model\Sqlite\Role\EidlistOptForm $eidlistOpt): self
    {
        return new self($this->createkw, $this->temp, $this->ifnotexists, $this->nm, $this->dbnm, $eidlistOpt, $this->select, $this->comments);
    }

    /**
     * Returns a copy with a new select, preserving every other field.
     */
    public function withSelect(\SqlSemantics\Statement\Model\Sqlite\Role\SelectForm $select): self
    {
        return new self($this->createkw, $this->temp, $this->ifnotexists, $this->nm, $this->dbnm, $this->eidlistOpt, $select, $this->comments);
    }

    /**
     * Returns a copy with a new comments, preserving every other field.
     */
    public function withComments(\SqlSemantics\Statement\Comments $comments): self
    {
        return new self($this->createkw, $this->temp, $this->ifnotexists, $this->nm, $this->dbnm, $this->eidlistOpt, $this->select, $comments);
    }
}
