<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\Sqlite\Value;

/**
 * The expr SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\Sqlite\Value\ExprWithExprBitandBitorLshiftRshiftExpr_67d895c2 $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class ExprWithExprBitandBitorLshiftRshiftExpr_67d895c2 implements \SqlSemantics\Statement\Model\Sqlite\Role\CaseOperandForm, \SqlSemantics\Statement\Model\Sqlite\Role\ExprForm, \SqlSemantics\Statement\Model\Sqlite\Role\ExprlistForm, \SqlSemantics\Statement\Model\Sqlite\Role\NexprlistForm
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form; comments are kept by the position of the symbol each precedes.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\Sqlite\Role\ExprForm $expr,
        public readonly string $bitandBitorLshiftRshift,
        public readonly \SqlSemantics\Statement\Model\Sqlite\Role\ExprForm $expr2,
        public readonly \SqlSemantics\Statement\Comments $comments = new \SqlSemantics\Statement\Comments(),
    ) {
        $this->assert(\SqlSemantics\Statement\Model\Sqlite\Contract\Contracts::contains($expr), 'The expr must be a generated immutable SQL value.');
        $this->assertOperandBindingStrength($expr, \SqlSemantics\Statement\Model\Sqlite\Contract\Contracts::BINDING_POWERS, array (  'sqlite-3.47.2' => 7,));
        $this->assertMatchesPattern($bitandBitorLshiftRshift, \SqlSemantics\Statement\Model\Sqlite\Contract\Contracts::SPELLINGS['BITAND|BITOR|LSHIFT|RSHIFT'], 'The bitandBitorLshiftRshift must be a complete BITAND|BITOR|LSHIFT|RSHIFT lexical spelling.');
        $this->assert(\SqlSemantics\Statement\Model\Sqlite\Contract\Contracts::contains($expr2), 'The expr2 must be a generated immutable SQL value.');
        $this->assertOperandBindingStrength($expr2, \SqlSemantics\Statement\Model\Sqlite\Contract\Contracts::BINDING_POWERS, array (  'sqlite-3.47.2' => 8,));
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->comments($this->comments, 0);
        $this->expr->write($writer);
        $writer->comments($this->comments, 1);
        $writer->append($this->bitandBitorLshiftRshift);
        $writer->comments($this->comments, 2);
        $this->expr2->write($writer);
    }

    /**
     * Returns a copy with a new expr, preserving every other field.
     */
    public function withExpr(\SqlSemantics\Statement\Model\Sqlite\Role\ExprForm $expr): self
    {
        return new self($expr, $this->bitandBitorLshiftRshift, $this->expr2, $this->comments);
    }

    /**
     * Returns a copy with a new bitandBitorLshiftRshift, preserving every other field.
     */
    public function withBitandBitorLshiftRshift(string $bitandBitorLshiftRshift): self
    {
        return new self($this->expr, $bitandBitorLshiftRshift, $this->expr2, $this->comments);
    }

    /**
     * Returns a copy with a new expr2, preserving every other field.
     */
    public function withExpr2(\SqlSemantics\Statement\Model\Sqlite\Role\ExprForm $expr2): self
    {
        return new self($this->expr, $this->bitandBitorLshiftRshift, $expr2, $this->comments);
    }

    /**
     * Returns a copy with a new comments, preserving every other field.
     */
    public function withComments(\SqlSemantics\Statement\Comments $comments): self
    {
        return new self($this->expr, $this->bitandBitorLshiftRshift, $this->expr2, $comments);
    }
}
