<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\Sqlite\Value;

/**
 * The joinop SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\Sqlite\Value\JoinopWithCommaJoin_2b032ba0 $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class JoinopWithCommaJoin_2b032ba0 implements \SqlSemantics\Statement\Model\Sqlite\Role\JoinopForm
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form; comments are kept by the position of the symbol each precedes.
     */
    public function __construct(
        public readonly string $commaJoin,
        public readonly \SqlSemantics\Statement\Comments $comments = new \SqlSemantics\Statement\Comments(),
    ) {
        $this->assertMatchesPattern($commaJoin, \SqlSemantics\Statement\Model\Sqlite\Contract\Contracts::SPELLINGS['COMMA|JOIN'], 'The commaJoin must be a complete COMMA|JOIN lexical spelling.');
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->comments($this->comments, 0);
        $writer->append($this->commaJoin);
    }

    /**
     * Returns a copy with a new commaJoin, preserving every other field.
     */
    public function withCommaJoin(string $commaJoin): self
    {
        return new self($commaJoin, $this->comments);
    }

    /**
     * Returns a copy with a new comments, preserving every other field.
     */
    public function withComments(\SqlSemantics\Statement\Comments $comments): self
    {
        return new self($this->commaJoin, $comments);
    }
}
