<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\Sqlite\Value;

/**
 * The mvalues SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\Sqlite\Value\MvaluesWithValuesCommaLpNexprlistRp_cd8c14f9 $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class MvaluesWithValuesCommaLpNexprlistRp_cd8c14f9 implements \SqlSemantics\Statement\Model\Sqlite\Role\CmdForm, \SqlSemantics\Statement\Model\Sqlite\Role\CmdxForm, \SqlSemantics\Statement\Model\Sqlite\Role\MvaluesForm, \SqlSemantics\Statement\Model\Sqlite\Role\OneselectForm, \SqlSemantics\Statement\Model\Sqlite\Role\SelectForm, \SqlSemantics\Statement\Model\Sqlite\Role\SelectnowithForm, \SqlSemantics\Statement\Command
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\Sqlite\Role\ValuesForm $values,
        public readonly \SqlSemantics\Statement\Model\Sqlite\Role\NexprlistForm $nexprlist,
    ) {
        $this->assert(\SqlSemantics\Statement\Model\Sqlite\Contract\Contracts::contains($values), 'The values must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\Sqlite\Contract\Contracts::contains($nexprlist), 'The nexprlist must be a generated immutable SQL value.');
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $this->values->write($writer);
        $writer->append(',');
        $writer->append('(');
        $this->nexprlist->write($writer);
        $writer->append(')');
    }

    /**
     * Returns a copy with a new values, preserving every other field.
     */
    public function withValues(\SqlSemantics\Statement\Model\Sqlite\Role\ValuesForm $values): self
    {
        return new self($values, $this->nexprlist);
    }

    /**
     * Returns a copy with a new nexprlist, preserving every other field.
     */
    public function withNexprlist(\SqlSemantics\Statement\Model\Sqlite\Role\NexprlistForm $nexprlist): self
    {
        return new self($this->values, $nexprlist);
    }
}
