<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\Sqlite\Value;

/**
 * The nmnum SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\Sqlite\Value\NmnumWithDelete_0e682fa5 $value): string => (new \SqlSemantics\Statement\Statement($value))->toString();
 *     $write instanceof \Closure // => true
 */
final class NmnumWithDelete_0e682fa5 implements \SqlSemantics\Statement\Model\Sqlite\Role\NmnumForm
{
    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->append('DELETE');
    }
}
