<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\Sqlite\Value;

/**
 * The seltablist SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\Sqlite\Value\SeltablistWithStlPrefixLpSeltablistRpAsOnUsing_e659a8d5 $value): string => (new \SqlSemantics\Statement\Statement($value))->toString();
 *     $write instanceof \Closure // => true
 */
final class SeltablistWithStlPrefixLpSeltablistRpAsOnUsing_e659a8d5 implements \SqlSemantics\Statement\Model\Sqlite\Role\SeltablistForm
{
    /**
     * Supplies the SQL values of this form.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\Sqlite\Role\StlPrefixForm $stlPrefix,
        public readonly \SqlSemantics\Statement\Model\Sqlite\Role\SeltablistForm $seltablist,
        public readonly \SqlSemantics\Statement\Model\Sqlite\Role\AsForm $as,
        public readonly \SqlSemantics\Statement\Model\Sqlite\Role\OnUsingForm $onUsing,
    ) {
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $this->stlPrefix->write($writer);
        $writer->append('(');
        $this->seltablist->write($writer);
        $writer->append(')');
        $this->as->write($writer);
        $this->onUsing->write($writer);
    }
}
