<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\Sqlite\Value;

/**
 * The tcons SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\Sqlite\Value\TconsWithPrimaryKeyLpSortlistAutoincRpOnconf_724fc4cd $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class TconsWithPrimaryKeyLpSortlistAutoincRpOnconf_724fc4cd implements \SqlSemantics\Statement\Model\Sqlite\Role\ConslistForm, \SqlSemantics\Statement\Model\Sqlite\Role\TconsForm
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form; comments are kept by the position of the symbol each precedes.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\Sqlite\Role\SortlistForm $sortlist,
        public readonly \SqlSemantics\Statement\Model\Sqlite\Role\AutoincForm $autoinc,
        public readonly \SqlSemantics\Statement\Model\Sqlite\Role\OnconfForm $onconf,
        public readonly \SqlSemantics\Statement\Comments $comments = new \SqlSemantics\Statement\Comments(),
    ) {
        $this->assert(\SqlSemantics\Statement\Model\Sqlite\Contract\Contracts::contains($sortlist), 'The sortlist must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\Sqlite\Contract\Contracts::contains($autoinc), 'The autoinc must be a generated immutable SQL value.');
        $this->assert(\SqlSemantics\Statement\Model\Sqlite\Contract\Contracts::contains($onconf), 'The onconf must be a generated immutable SQL value.');
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->comments($this->comments, 0);
        $writer->append('PRIMARY');
        $writer->comments($this->comments, 1);
        $writer->append('KEY');
        $writer->comments($this->comments, 2);
        $writer->append('(');
        $writer->comments($this->comments, 3);
        $this->sortlist->write($writer);
        $writer->comments($this->comments, 4);
        $this->autoinc->write($writer);
        $writer->comments($this->comments, 5);
        $writer->append(')');
        $writer->comments($this->comments, 6);
        $this->onconf->write($writer);
    }

    /**
     * Lists the values of this form, in writing order.
     *
     * @return list<\SqlSemantics\Statement\Element>
     */
    public function children(): array
    {
        return [$this->sortlist, $this->autoinc, $this->onconf];
    }

    /**
     * Returns this value rebuilt around what the function answers for each value, keeping lexical fields and comments; itself when every answer is the value it was given.
     *
     * @param callable(\SqlSemantics\Statement\Element): \SqlSemantics\Statement\Element $replace
     */
    public function map(callable $replace): static
    {
        $mapped = [$this->replacement($this->sortlist, \SqlSemantics\Statement\Model\Sqlite\Role\SortlistForm::class, $replace), $this->replacement($this->autoinc, \SqlSemantics\Statement\Model\Sqlite\Role\AutoincForm::class, $replace), $this->replacement($this->onconf, \SqlSemantics\Statement\Model\Sqlite\Role\OnconfForm::class, $replace)];

        return $mapped === [$this->sortlist, $this->autoinc, $this->onconf] ? $this : new self($mapped[0], $mapped[1], $mapped[2], $this->comments);
    }

    /**
     * Returns a copy with a new sortlist, preserving every other field.
     */
    public function withSortlist(\SqlSemantics\Statement\Model\Sqlite\Role\SortlistForm $sortlist): self
    {
        return new self($sortlist, $this->autoinc, $this->onconf, $this->comments);
    }

    /**
     * Returns a copy with a new autoinc, preserving every other field.
     */
    public function withAutoinc(\SqlSemantics\Statement\Model\Sqlite\Role\AutoincForm $autoinc): self
    {
        return new self($this->sortlist, $autoinc, $this->onconf, $this->comments);
    }

    /**
     * Returns a copy with a new onconf, preserving every other field.
     */
    public function withOnconf(\SqlSemantics\Statement\Model\Sqlite\Role\OnconfForm $onconf): self
    {
        return new self($this->sortlist, $this->autoinc, $onconf, $this->comments);
    }

    /**
     * Returns a copy with a new comments, preserving every other field.
     */
    public function withComments(\SqlSemantics\Statement\Comments $comments): self
    {
        return new self($this->sortlist, $this->autoinc, $this->onconf, $comments);
    }
}
