<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\Sqlite\Value;

/**
 * The term SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\Sqlite\Value\TermWithQnumber_45fd67fa $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class TermWithQnumber_45fd67fa implements \SqlSemantics\Statement\Model\Sqlite\Role\CaseOperandForm, \SqlSemantics\Statement\Model\Sqlite\Role\ExprForm, \SqlSemantics\Statement\Model\Sqlite\Role\ExprlistForm, \SqlSemantics\Statement\Model\Sqlite\Role\NexprlistForm, \SqlSemantics\Statement\Model\Sqlite\Role\TermForm
{
    use \SqlSemantics\Statement\Assertion;

    /**
     * Supplies the SQL values of this form; comments are kept by the position of the symbol each precedes.
     */
    public function __construct(
        public readonly string $qnumber,
        public readonly \SqlSemantics\Statement\Comments $comments = new \SqlSemantics\Statement\Comments(),
    ) {
        $this->assertMatchesPattern($qnumber, \SqlSemantics\Statement\Model\Sqlite\Contract\Contracts::SPELLINGS['QNUMBER'], 'The qnumber must be a complete QNUMBER lexical spelling.');
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->comments($this->comments, 0);
        $writer->append($this->qnumber);
    }

    /**
     * Lists the values of this form, in writing order.
     *
     * @return list<\SqlSemantics\Statement\Element>
     */
    public function children(): array
    {
        return [];
    }

    /**
     * This form holds no values to replace.
     *
     * @param callable(\SqlSemantics\Statement\Element): \SqlSemantics\Statement\Element $replace
     */
    public function map(callable $replace): static
    {
        return $this;
    }

    /**
     * Returns a copy with a new qnumber, preserving every other field.
     */
    public function withQnumber(string $qnumber): self
    {
        return new self($qnumber, $this->comments);
    }

    /**
     * Returns a copy with a new comments, preserving every other field.
     */
    public function withComments(\SqlSemantics\Statement\Comments $comments): self
    {
        return new self($this->qnumber, $comments);
    }
}
