<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\Sqlite\Value;

/**
 * The typetoken SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\Sqlite\Value\TypetokenWith_6b66532f $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
final class TypetokenWith_6b66532f implements \SqlSemantics\Statement\Model\Sqlite\Role\TypetokenForm
{
    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {

    }
}
