<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The adm_partition SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\AdmPartitionWithPartitionSymHavePartitioningAllOrAltPartNameList_3852b767 $value): string => (new \SqlSemantics\Statement\Statement($value))->toString();
 *     $write instanceof \Closure // => true
 */
final class AdmPartitionWithPartitionSymHavePartitioningAllOrAltPartNameList_3852b767 implements \SqlSemantics\Statement\Model\MySql\Role\AdmPartitionForm
{
    /**
     * Supplies the SQL values of this form.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\MySql\Role\HavePartitioningForm $havePartitioning,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\AllOrAltPartNameListForm $allOrAltPartNameList,
    ) {
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->append('PARTITION');
        $this->havePartitioning->write($writer);
        $writer->append('(');
        $this->allOrAltPartNameList->write($writer);
        $writer->append(')');
    }
}
