<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The alter_view_stmt SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\AlterViewStmtWithAlterViewAlgorithmDefinerOptViewTail_6fe44f1c $value): string => (new \SqlSemantics\Statement\Statement($value))->toString();
 *     $write instanceof \Closure // => true
 */
final class AlterViewStmtWithAlterViewAlgorithmDefinerOptViewTail_6fe44f1c implements \SqlSemantics\Statement\Model\MySql\Role\AlterViewStmtForm, \SqlSemantics\Statement\Model\MySql\Role\EvSqlStmtForm, \SqlSemantics\Statement\Model\MySql\Role\EvSqlStmtInnerForm, \SqlSemantics\Statement\Model\MySql\Role\SimpleStatementForm, \SqlSemantics\Statement\Model\MySql\Role\SimpleStatementOrBeginForm, \SqlSemantics\Statement\Model\MySql\Role\SpProcStmtForm, \SqlSemantics\Statement\Model\MySql\Role\SpProcStmtStatementForm, \SqlSemantics\Statement\Model\MySql\Role\StoredRoutineBodyForm
{
    /**
     * Supplies the SQL values of this form.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\MySql\Role\ViewAlgorithmForm $viewAlgorithm,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\DefinerOptForm $definerOpt,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\ViewTailForm $viewTail,
    ) {
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->append('ALTER');
        $this->viewAlgorithm->write($writer);
        $this->definerOpt->write($writer);
        $this->viewTail->write($writer);
    }
}
