<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The explainable_stmt SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\ExplainableStmtWithOptExplainForSchemaDeleteStmt_262d4fa4 $value): string => (new \SqlSemantics\Statement\Statement($value))->toString();
 *     $write instanceof \Closure // => true
 */
final class ExplainableStmtWithOptExplainForSchemaDeleteStmt_262d4fa4 implements \SqlSemantics\Statement\Model\MySql\Role\ExplainableStmtForm
{
    /**
     * Supplies the SQL values of this form.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\MySql\Role\OptExplainForSchemaForm $optExplainForSchema,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\DeleteStmtForm $deleteStmt,
    ) {
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $this->optExplainForSchema->write($writer);
        $this->deleteStmt->write($writer);
    }
}
