<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The opt_ignore_unknown_user SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\OptIgnoreUnknownUserWithIgnoreSymUnknownSymUser_7983907d $value): string => (new \SqlSemantics\Statement\Statement($value))->toString();
 *     $write instanceof \Closure // => true
 */
final class OptIgnoreUnknownUserWithIgnoreSymUnknownSymUser_7983907d implements \SqlSemantics\Statement\Model\MySql\Role\OptIgnoreUnknownUserForm
{
    /**
     * Supplies the SQL values of this form.
     */
    public function __construct(
        public readonly string $user,
    ) {
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $writer->append('IGNORE');
        $writer->append('UNKNOWN');
        $writer->append($this->user);
    }
}
