<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The revoke_command SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\RevokeCommandWithGrantPrivilegesOnFunctionSymGrantIdentFromGrantList_994dfc87 $value): string => (new \SqlSemantics\Statement\Statement($value))->toString();
 *     $write instanceof \Closure // => true
 */
final class RevokeCommandWithGrantPrivilegesOnFunctionSymGrantIdentFromGrantList_994dfc87 implements \SqlSemantics\Statement\Model\MySql\Role\RevokeCommandForm
{
    /**
     * Supplies the SQL values of this form.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\MySql\Role\GrantPrivilegesForm $grantPrivileges,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\GrantIdentForm $grantIdent,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\GrantListForm $grantList,
    ) {
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $this->grantPrivileges->write($writer);
        $writer->append('ON');
        $writer->append('FUNCTION');
        $this->grantIdent->write($writer);
        $writer->append('FROM');
        $this->grantList->write($writer);
    }
}
