<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The sp_a_chistics SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\SpAChisticsWithSpAChisticsSpChistic_8a3f438b $value): string => (new \SqlSemantics\Statement\Statement($value))->toString();
 *     $write instanceof \Closure // => true
 */
final class SpAChisticsWithSpAChisticsSpChistic_8a3f438b implements \SqlSemantics\Statement\Model\MySql\Role\SpAChisticsForm
{
    /**
     * Supplies the SQL values of this form.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\MySql\Role\SpAChisticsForm $spAChistics,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\SpChisticForm $spChistic,
    ) {
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $this->spAChistics->write($writer);
        $this->spChistic->write($writer);
    }
}
