<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Value;

/**
 * The xid SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Value\XidWithTextStringTextStringUlongNum_75cb1bab $value): string => (new \SqlSemantics\Statement\Statement($value))->toString();
 *     $write instanceof \Closure // => true
 */
final class XidWithTextStringTextStringUlongNum_75cb1bab implements \SqlSemantics\Statement\Model\MySql\Role\XidForm
{
    /**
     * Supplies the SQL values of this form.
     */
    public function __construct(
        public readonly \SqlSemantics\Statement\Model\MySql\Role\TextStringForm $textString,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\TextStringForm $textString2,
        public readonly \SqlSemantics\Statement\Model\MySql\Role\UlongNumForm $ulongNum,
    ) {
    }

    /**
     * Writes SQL entirely from this value's fields.
     */
    public function write(\SqlSemantics\Statement\Writer $writer): void
    {
        $this->textString->write($writer);
        $writer->append(',');
        $this->textString2->write($writer);
        $writer->append(',');
        $this->ulongNum->write($writer);
    }
}
