<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Role;

/**
 * The get_diagnostics SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Role\GetDiagnosticsForm $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
interface GetDiagnosticsForm extends \SqlSemantics\Statement\Element
{
}
