<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Role;

/**
 * The opt_ts_nodegroup SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Role\OptTsNodegroupForm $value): string => (new \SqlSemantics\Statement\Statement($value))->toString();
 *     $write instanceof \Closure // => true
 */
interface OptTsNodegroupForm extends \SqlSemantics\Statement\Element
{
}
