<?php

declare(strict_types=1);

namespace SqlSemantics\Statement\Model\MySql\Role;

/**
 * The show_create_function_stmt SQL value; generated by bin/build-models.php.
 *
 * @visibility public
 * @example Accept a structured SQL value
 *     $write = static fn (\SqlSemantics\Statement\Model\MySql\Role\ShowCreateFunctionStmtForm $value): string => \SqlSemantics\Statement\Writer::render($value);
 *     $write instanceof \Closure // => true
 */
interface ShowCreateFunctionStmtForm extends \SqlSemantics\Statement\Element
{
}
