<?php

declare(strict_types=1);

namespace SqlFaker\MySql\Generation\Lexeme;

use SqlFaker\Grammar\Generation\Lexeme\LexemeGenerator;
use SqlFaker\Grammar\Generation\Lexeme\LexemeInput;
use SqlFaker\Grammar\Generation\Lexeme\MatchingLexemeGenerator;
use SqlFaker\Grammar\Generation\Version\VersionCase;
use SqlFaker\Grammar\Generation\Version\VersionedLexemeGenerator;

/**
 * Keyword dispatch shared by all checked-in MySQL releases, derived from their sql/lex.h declarations.
 */
final class CommonKeywordDefinitions
{
    private const TERMINALS = [
        'ACCESSIBLE_SYM', 'ACTION', 'ADD', 'ADDDATE_SYM', 'AFTER_SYM',
        'AGAINST', 'AGGREGATE_SYM', 'ALGORITHM_SYM', 'ALL', 'ALTER',
        'ANALYZE_SYM', 'AND_AND_SYM', 'AND_SYM', 'ANY_SYM', 'AS',
        'ASC', 'ASCII_SYM', 'ASENSITIVE_SYM', 'AT_SYM', 'AUTOEXTEND_SIZE_SYM',
        'AUTO_INC', 'AVG_ROW_LENGTH', 'AVG_SYM', 'BACKUP_SYM', 'BEFORE_SYM',
        'BEGIN_SYM', 'BETWEEN_SYM', 'BINLOG_SYM', 'BIT_SYM', 'BLOB_SYM',
        'BLOCK_SYM', 'BOOLEAN_SYM', 'BOOL_SYM', 'BOTH', 'BTREE_SYM',
        'BY', 'BYTE_SYM', 'CACHE_SYM', 'CALL_SYM', 'CASCADE',
        'CASCADED', 'CASE_SYM', 'CAST_SYM', 'CATALOG_NAME_SYM', 'CHAIN_SYM',
        'CHANGE', 'CHANGED', 'CHARSET', 'CHAR_SYM', 'CHECKSUM_SYM',
        'CHECK_SYM', 'CIPHER_SYM', 'CLASS_ORIGIN_SYM', 'CLIENT_SYM', 'CLOSE_SYM',
        'COALESCE', 'CODE_SYM', 'COLLATE_SYM', 'COLLATION_SYM', 'COLUMNS',
        'COLUMN_FORMAT_SYM', 'COLUMN_NAME_SYM', 'COLUMN_SYM', 'COMMENT_SYM', 'COMMITTED_SYM',
        'COMMIT_SYM', 'COMPACT_SYM', 'COMPLETION_SYM', 'COMPRESSED_SYM', 'CONCURRENT',
        'CONDITION_SYM', 'CONNECTION_SYM', 'CONSISTENT_SYM', 'CONSTRAINT', 'CONSTRAINT_CATALOG_SYM',
        'CONSTRAINT_NAME_SYM', 'CONSTRAINT_SCHEMA_SYM', 'CONTAINS_SYM', 'CONTEXT_SYM', 'CONTINUE_SYM',
        'CONVERT_SYM', 'COUNT_SYM', 'CPU_SYM', 'CREATE', 'CROSS',
        'CUBE_SYM', 'CURDATE', 'CURRENT_SYM', 'CURRENT_USER', 'CURSOR_NAME_SYM',
        'CURSOR_SYM', 'CURTIME', 'DATABASE', 'DATABASES', 'DATAFILE_SYM',
        'DATA_SYM', 'DATE_ADD_INTERVAL', 'DATE_SUB_INTERVAL', 'DATE_SYM', 'DAY_HOUR_SYM',
        'DAY_MICROSECOND_SYM', 'DAY_MINUTE_SYM', 'DAY_SECOND_SYM', 'DAY_SYM', 'DEALLOCATE_SYM',
        'DECIMAL_SYM', 'DECLARE_SYM', 'DEFAULT_AUTH_SYM', 'DEFINER_SYM', 'DELAYED_SYM',
        'DELAY_KEY_WRITE_SYM', 'DELETE_SYM', 'DESC', 'DESCRIBE', 'DETERMINISTIC_SYM',
        'DIAGNOSTICS_SYM', 'DIRECTORY_SYM', 'DISABLE_SYM', 'DISK_SYM', 'DISTINCT',
        'DIV_SYM', 'DOUBLE_SYM', 'DO_SYM', 'DROP', 'DUAL_SYM',
        'DUMPFILE', 'DUPLICATE_SYM', 'DYNAMIC_SYM', 'EACH_SYM', 'ELSE',
        'ELSEIF_SYM', 'ENABLE_SYM', 'ENCLOSED', 'END', 'ENDS_SYM',
        'ENGINES_SYM', 'ENGINE_SYM', 'EQ', 'EQUAL_SYM', 'ERRORS',
        'ERROR_SYM', 'ESCAPED', 'ESCAPE_SYM', 'EVENTS_SYM', 'EVENT_SYM',
        'EVERY_SYM', 'EXCHANGE_SYM', 'EXECUTE_SYM', 'EXISTS', 'EXIT_SYM',
        'EXPANSION_SYM', 'EXPIRE_SYM', 'EXPORT_SYM', 'EXTENDED_SYM', 'EXTENT_SIZE_SYM',
        'EXTRACT_SYM', 'FALSE_SYM', 'FAST_SYM', 'FAULTS_SYM', 'FETCH_SYM',
        'FILE_SYM', 'FIRST_SYM', 'FIXED_SYM', 'FLOAT_SYM', 'FLUSH_SYM',
        'FORCE_SYM', 'FOREIGN', 'FORMAT_SYM', 'FOR_SYM', 'FOUND_SYM',
        'FROM', 'FULL', 'FULLTEXT_SYM', 'FUNCTION_SYM', 'GE',
        'GENERAL', 'GEOMETRY_SYM', 'GET_FORMAT', 'GET_SYM', 'GLOBAL_SYM',
        'GRANT', 'GRANTS', 'GROUP_CONCAT_SYM', 'GROUP_SYM', 'GT_SYM',
        'HANDLER_SYM', 'HASH_SYM', 'HAVING', 'HELP_SYM', 'HIGH_PRIORITY',
        'HOSTS_SYM', 'HOST_SYM', 'HOUR_MICROSECOND_SYM', 'HOUR_MINUTE_SYM', 'HOUR_SECOND_SYM',
        'HOUR_SYM', 'IDENTIFIED_SYM', 'IF', 'IGNORE_SERVER_IDS_SYM', 'IGNORE_SYM',
        'IMPORT', 'INDEXES', 'INDEX_SYM', 'INITIAL_SIZE_SYM', 'INNER_SYM',
        'INOUT_SYM', 'INSENSITIVE_SYM', 'INSERT_METHOD', 'INSTALL_SYM', 'INTERVAL_SYM',
        'INTO', 'INT_SYM', 'INVOKER_SYM', 'IN_SYM', 'IO_AFTER_GTIDS',
        'IO_BEFORE_GTIDS', 'IO_SYM', 'IPC_SYM', 'IS', 'ISOLATION',
        'ISSUER_SYM', 'ITERATE_SYM', 'JOIN_SYM', 'KEYS', 'KEY_BLOCK_SIZE',
        'KEY_SYM', 'KILL_SYM', 'LANGUAGE_SYM', 'LAST_SYM', 'LE',
        'LEADING', 'LEAVES', 'LEAVE_SYM', 'LEFT', 'LESS_SYM',
        'LEVEL_SYM', 'LIKE', 'LIMIT', 'LINEAR_SYM', 'LINES',
        'LIST_SYM', 'LOAD', 'LOCAL_SYM', 'LOCKS_SYM', 'LOCK_SYM',
        'LOGFILE_SYM', 'LOGS_SYM', 'LONG_SYM', 'LOOP_SYM', 'LOW_PRIORITY',
        'LT', 'MASTER_SYM', 'MATCH', 'MAX_CONNECTIONS_PER_HOUR', 'MAX_QUERIES_PER_HOUR',
        'MAX_ROWS', 'MAX_SIZE_SYM', 'MAX_SYM', 'MAX_UPDATES_PER_HOUR', 'MAX_USER_CONNECTIONS_SYM',
        'MAX_VALUE_SYM', 'MEDIUM_SYM', 'MEMORY_SYM', 'MERGE_SYM', 'MESSAGE_TEXT_SYM',
        'MICROSECOND_SYM', 'MIGRATE_SYM', 'MINUTE_MICROSECOND_SYM', 'MINUTE_SECOND_SYM', 'MINUTE_SYM',
        'MIN_ROWS', 'MIN_SYM', 'MODE_SYM', 'MODIFIES_SYM', 'MODIFY_SYM',
        'MOD_SYM', 'MONTH_SYM', 'MUTEX_SYM', 'MYSQL_ERRNO_SYM', 'NAMES_SYM',
        'NAME_SYM', 'NATIONAL_SYM', 'NATURAL', 'NCHAR_SYM', 'NDBCLUSTER_SYM',
        'NE', 'NEW_SYM', 'NEXT_SYM', 'NODEGROUP_SYM', 'NONE_SYM',
        'NOT_SYM', 'NOW_SYM', 'NO_SYM', 'NO_WAIT_SYM', 'NO_WRITE_TO_BINLOG',
        'NULL_SYM', 'NUMBER_SYM', 'NUMERIC_SYM', 'NVARCHAR_SYM', 'OFFSET_SYM',
        'ONE_SYM', 'ONLY_SYM', 'OPEN_SYM', 'OPTIMIZE', 'OPTION',
        'OPTIONALLY', 'OPTIONS_SYM', 'ORDER_SYM', 'OR_OR_SYM', 'OR_SYM',
        'OUTFILE', 'OUT_SYM', 'OWNER_SYM', 'PACK_KEYS_SYM', 'PAGE_SYM',
        'PARSER_SYM', 'PARTIAL', 'PARTITIONING_SYM', 'PARTITIONS_SYM', 'PARTITION_SYM',
        'PASSWORD', 'PHASE_SYM', 'PLUGINS_SYM', 'PLUGIN_DIR_SYM', 'PLUGIN_SYM',
        'POINT_SYM', 'PORT_SYM', 'POSITION_SYM', 'PRECISION', 'PREPARE_SYM',
        'PRESERVE_SYM', 'PREV_SYM', 'PRIMARY_SYM', 'PRIVILEGES', 'PROCEDURE_SYM',
        'PROCESS', 'PROCESSLIST_SYM', 'PROFILES_SYM', 'PROFILE_SYM', 'PROXY_SYM',
        'PURGE', 'QUARTER_SYM', 'QUERY_SYM', 'QUICK', 'RANGE_SYM',
        'READS_SYM', 'READ_ONLY_SYM', 'READ_SYM', 'READ_WRITE_SYM', 'REBUILD_SYM',
        'RECOVER_SYM', 'REDO_BUFFER_SIZE_SYM', 'REDUNDANT_SYM', 'REFERENCES', 'REGEXP',
        'RELAY', 'RELAYLOG_SYM', 'RELAY_LOG_FILE_SYM', 'RELAY_LOG_POS_SYM', 'RELAY_THREAD',
        'RELEASE_SYM', 'RELOAD', 'REMOVE_SYM', 'RENAME', 'REORGANIZE_SYM',
        'REPAIR', 'REPEATABLE_SYM', 'REPEAT_SYM', 'REPLICATION', 'REQUIRE_SYM',
        'RESET_SYM', 'RESIGNAL_SYM', 'RESOURCES', 'RESTORE_SYM', 'RESTRICT',
        'RESUME_SYM', 'RETURNED_SQLSTATE_SYM', 'RETURNS_SYM', 'RETURN_SYM', 'REVERSE_SYM',
        'REVOKE', 'RIGHT', 'ROLLBACK_SYM', 'ROLLUP_SYM', 'ROUTINE_SYM',
        'ROWS_SYM', 'ROW_COUNT_SYM', 'ROW_FORMAT_SYM', 'ROW_SYM', 'RTREE_SYM',
        'SAVEPOINT_SYM', 'SCHEDULE_SYM', 'SCHEMA_NAME_SYM', 'SECOND_MICROSECOND_SYM', 'SECOND_SYM',
        'SECURITY_SYM', 'SELECT_SYM', 'SENSITIVE_SYM', 'SEPARATOR_SYM', 'SERIALIZABLE_SYM',
        'SERIAL_SYM', 'SERVER_SYM', 'SESSION_SYM', 'SHARE_SYM', 'SHIFT_LEFT',
        'SHIFT_RIGHT', 'SHOW', 'SHUTDOWN', 'SIGNAL_SYM', 'SIGNED_SYM',
        'SIMPLE_SYM', 'SLAVE', 'SLOW', 'SNAPSHOT_SYM', 'SOCKET_SYM',
        'SONAME_SYM', 'SOUNDS_SYM', 'SOURCE_SYM', 'SPATIAL_SYM', 'SPECIFIC_SYM',
        'SQLEXCEPTION_SYM', 'SQLSTATE_SYM', 'SQLWARNING_SYM', 'SQL_AFTER_GTIDS', 'SQL_AFTER_MTS_GAPS',
        'SQL_BEFORE_GTIDS', 'SQL_BIG_RESULT', 'SQL_BUFFER_RESULT', 'SQL_CALC_FOUND_ROWS', 'SQL_NO_CACHE_SYM',
        'SQL_SMALL_RESULT', 'SQL_SYM', 'SQL_THREAD', 'SSL_SYM', 'STARTING',
        'STARTS_SYM', 'START_SYM', 'STATS_AUTO_RECALC_SYM', 'STATS_PERSISTENT_SYM', 'STATS_SAMPLE_PAGES_SYM',
        'STATUS_SYM', 'STDDEV_SAMP_SYM', 'STD_SYM', 'STOP_SYM', 'STORAGE_SYM',
        'STRAIGHT_JOIN', 'STRING_SYM', 'SUBCLASS_ORIGIN_SYM', 'SUBDATE_SYM', 'SUBJECT_SYM',
        'SUBPARTITIONS_SYM', 'SUBPARTITION_SYM', 'SUBSTRING', 'SUM_SYM', 'SUPER_SYM',
        'SUSPEND_SYM', 'SWAPS_SYM', 'SWITCHES_SYM', 'SYSDATE', 'TABLES',
        'TABLE_CHECKSUM_SYM', 'TABLE_NAME_SYM', 'TABLE_SYM', 'TEMPORARY', 'TEMPTABLE_SYM',
        'TERMINATED', 'TEXT_SYM', 'THAN_SYM', 'THEN_SYM', 'TIMESTAMP_ADD',
        'TIMESTAMP_DIFF', 'TIME_SYM', 'TO_SYM', 'TRAILING', 'TRANSACTION_SYM',
        'TRIGGERS_SYM', 'TRIGGER_SYM', 'TRIM', 'TRUE_SYM', 'TRUNCATE_SYM',
        'TYPES_SYM', 'TYPE_SYM', 'UNCOMMITTED_SYM', 'UNDEFINED_SYM', 'UNDOFILE_SYM',
        'UNDO_BUFFER_SIZE_SYM', 'UNDO_SYM', 'UNICODE_SYM', 'UNINSTALL_SYM', 'UNION_SYM',
        'UNIQUE_SYM', 'UNKNOWN_SYM', 'UNLOCK_SYM', 'UNTIL_SYM', 'UPDATE_SYM',
        'UPGRADE_SYM', 'USAGE', 'USER', 'USE_FRM', 'USE_SYM',
        'USING', 'UTC_DATE_SYM', 'UTC_TIMESTAMP_SYM', 'UTC_TIME_SYM', 'VALUES',
        'VALUE_SYM', 'VARIABLES', 'VARIANCE_SYM', 'VARYING', 'VAR_SAMP_SYM',
        'VIEW_SYM', 'WAIT_SYM', 'WARNINGS', 'WEEK_SYM', 'WEIGHT_STRING_SYM',
        'WHEN_SYM', 'WHERE', 'WHILE_SYM', 'WITH', 'WORK_SYM',
        'WRAPPER_SYM', 'WRITE_SYM', 'X509_SYM', 'XA_SYM', 'XML_SYM',
        'XOR', 'YEAR_MONTH_SYM', 'YEAR_SYM',
    ];

    /**
     * Fixes the common keyword handler to the explicitly reviewed releases.
     */
    public function create(string $version, KeywordLexemeGenerator $keywords): LexemeGenerator
    {
        return new MatchingLexemeGenerator(
            static fn (LexemeInput $input): bool => in_array($input->terminal()->name, self::TERMINALS, true),
            new VersionedLexemeGenerator($version, new VersionCase(
                ['mysql-5.6.51', 'mysql-5.7.44', 'mysql-8.0.44', 'mysql-8.1.0', 'mysql-8.2.0', 'mysql-8.3.0', 'mysql-8.4.7', 'mysql-9.0.1', 'mysql-9.1.0'],
                $keywords,
                'mysql-common-keywords',
            )),
        );
    }
}
