name: Merge Gatekeeper

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - stacked
  check_suite:
    types:
      - completed
  status: {}

jobs:
  merge-gatekeeper:
    runs-on: ubuntu-latest
    permissions:
      checks: read
      statuses: read
    steps:
      - uses: upsidr/merge-gatekeeper@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          timeout: 1800
